// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val AcademicCap: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "AcademicCap",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(4.46f, 19.46f)
                quadTo(5.1f, 18.82f, 5.48f, 18.07f)
                quadTo(4.49f, 17.61f, 3.48f, 17.19f)
                quadTo(3.01f, 16.99f, 3.02f, 16.48f)
                quadTo(3.09f, 13.56f, 3.44f, 10.67f)
                quadTo(2.43f, 10.34f, 1.4f, 10.06f)
                quadTo(1.1f, 9.97f, 0.95f, 9.7f)
                quadTo(0.8f, 9.43f, 0.88f, 9.13f)
                quadTo(0.95f, 8.88f, 1.17f, 8.72f)
                quadTo(6.14f, 5.24f, 11.7f, 2.81f)
                quadTo(12f, 2.67f, 12.3f, 2.81f)
                quadTo(17.86f, 5.24f, 22.83f, 8.72f)
                quadTo(23.08f, 8.9f, 23.14f, 9.2f)
                quadTo(23.19f, 9.51f, 23.01f, 9.76f)
                quadTo(22.86f, 9.98f, 22.6f, 10.06f)
                quadTo(21.58f, 10.34f, 20.56f, 10.67f)
                quadTo(20.91f, 13.56f, 20.98f, 16.48f)
                quadTo(20.99f, 16.99f, 20.52f, 17.19f)
                quadTo(16.26f, 18.97f, 12.42f, 21.53f)
                quadTo(12f, 21.8f, 11.58f, 21.53f)
                quadTo(9.28f, 19.99f, 6.83f, 18.74f)
                quadTo(6.35f, 19.7f, 5.52f, 20.52f)
                quadTo(5.3f, 20.74f, 4.99f, 20.74f)
                quadTo(4.68f, 20.74f, 4.46f, 20.52f)
                quadTo(4.24f, 20.3f, 4.24f, 19.99f)
                quadTo(4.24f, 19.68f, 4.46f, 19.46f)
                close()
                moveTo(8.68f, 11.05f)
                quadTo(10.36f, 11.78f, 12f, 12.64f)
                quadTo(15.6f, 10.75f, 19.46f, 9.45f)
                quadTo(19.5f, 9.44f, 19.54f, 9.43f)
                quadTo(20.1f, 9.24f, 20.67f, 9.06f)
                quadTo(16.54f, 6.33f, 12f, 4.31f)
                quadTo(7.46f, 6.33f, 3.33f, 9.06f)
                quadTo(3.9f, 9.23f, 4.46f, 9.42f)
                quadTo(4.51f, 9.44f, 4.55f, 9.46f)
                quadTo(5.76f, 9.86f, 6.94f, 10.33f)
                quadTo(9.25f, 8.93f, 11.68f, 7.77f)
                quadTo(11.96f, 7.63f, 12.25f, 7.74f)
                quadTo(12.54f, 7.84f, 12.68f, 8.12f)
                quadTo(12.81f, 8.4f, 12.71f, 8.69f)
                quadTo(12.61f, 8.98f, 12.32f, 9.12f)
                quadTo(10.46f, 10.01f, 8.68f, 11.05f)
                close()
                moveTo(7.5f, 12.17f)
                lineTo(7.5f, 12.88f)
                quadTo(8.25f, 13.19f, 8.25f, 14.25f)
                quadTo(8.25f, 15.31f, 7.5f, 15.62f)
                lineTo(7.5f, 15.75f)
                quadTo(7.5f, 16.57f, 7.33f, 17.31f)
                quadTo(9.74f, 18.53f, 12f, 20.01f)
                quadTo(15.56f, 17.68f, 19.47f, 16f)
                quadTo(19.39f, 13.57f, 19.11f, 11.16f)
                quadTo(15.62f, 12.4f, 12.35f, 14.15f)
                quadTo(12f, 14.34f, 11.65f, 14.15f)
                quadTo(9.62f, 13.06f, 7.5f, 12.17f)
                close()
                moveTo(4.89f, 11.16f)
                quadTo(4.61f, 13.57f, 4.53f, 16f)
                quadTo(5.24f, 16.31f, 5.93f, 16.63f)
                quadTo(6f, 16.2f, 6f, 15.75f)
                lineTo(6f, 15.62f)
                quadTo(5.25f, 15.31f, 5.25f, 14.25f)
                quadTo(5.25f, 13.19f, 6f, 12.88f)
                lineTo(6f, 11.57f)
                quadTo(5.45f, 11.36f, 4.89f, 11.16f)
                close()
            }
        }.build()
}
