// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val AdjustmentsVertical: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "AdjustmentsVertical",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(11.25f, 20.25f)
                lineTo(11.25f, 11.17f)
                quadTo(9.75f, 10.84f, 9.75f, 9f)
                quadTo(9.75f, 7.16f, 11.25f, 6.83f)
                lineTo(11.25f, 3.75f)
                quadTo(11.25f, 3.44f, 11.47f, 3.22f)
                quadTo(11.69f, 3f, 12f, 3f)
                quadTo(12.31f, 3f, 12.53f, 3.22f)
                quadTo(12.75f, 3.44f, 12.75f, 3.75f)
                lineTo(12.75f, 6.83f)
                quadTo(14.25f, 7.16f, 14.25f, 9f)
                quadTo(14.25f, 10.84f, 12.75f, 11.17f)
                lineTo(12.75f, 20.25f)
                quadTo(12.75f, 20.56f, 12.53f, 20.78f)
                quadTo(12.31f, 21f, 12f, 21f)
                quadTo(11.69f, 21f, 11.47f, 20.78f)
                quadTo(11.25f, 20.56f, 11.25f, 20.25f)
                close()
                moveTo(5.25f, 20.25f)
                lineTo(5.25f, 17.17f)
                quadTo(3.75f, 16.84f, 3.75f, 15f)
                quadTo(3.75f, 13.16f, 5.25f, 12.83f)
                lineTo(5.25f, 3.75f)
                quadTo(5.25f, 3.44f, 5.47f, 3.22f)
                quadTo(5.69f, 3f, 6f, 3f)
                quadTo(6.31f, 3f, 6.53f, 3.22f)
                quadTo(6.75f, 3.44f, 6.75f, 3.75f)
                lineTo(6.75f, 12.83f)
                quadTo(8.25f, 13.16f, 8.25f, 15f)
                quadTo(8.25f, 16.84f, 6.75f, 17.17f)
                lineTo(6.75f, 20.25f)
                quadTo(6.75f, 20.56f, 6.53f, 20.78f)
                quadTo(6.31f, 21f, 6f, 21f)
                quadTo(5.69f, 21f, 5.47f, 20.78f)
                quadTo(5.25f, 20.56f, 5.25f, 20.25f)
                close()
                moveTo(17.25f, 20.25f)
                lineTo(17.25f, 17.17f)
                quadTo(15.75f, 16.84f, 15.75f, 15f)
                quadTo(15.75f, 13.16f, 17.25f, 12.83f)
                lineTo(17.25f, 3.75f)
                quadTo(17.25f, 3.44f, 17.47f, 3.22f)
                quadTo(17.69f, 3f, 18f, 3f)
                quadTo(18.31f, 3f, 18.53f, 3.22f)
                quadTo(18.75f, 3.44f, 18.75f, 3.75f)
                lineTo(18.75f, 12.83f)
                quadTo(20.25f, 13.16f, 20.25f, 15f)
                quadTo(20.25f, 16.84f, 18.75f, 17.17f)
                lineTo(18.75f, 20.25f)
                quadTo(18.75f, 20.56f, 18.53f, 20.78f)
                quadTo(18.31f, 21f, 18f, 21f)
                quadTo(17.69f, 21f, 17.47f, 20.78f)
                quadTo(17.25f, 20.56f, 17.25f, 20.25f)
                close()
                moveTo(6f, 14.25f)
                quadTo(5.25f, 14.25f, 5.25f, 15f)
                quadTo(5.25f, 15.75f, 6f, 15.75f)
                quadTo(6.75f, 15.75f, 6.75f, 15f)
                quadTo(6.75f, 14.25f, 6f, 14.25f)
                close()
                moveTo(12f, 8.25f)
                quadTo(11.25f, 8.25f, 11.25f, 9f)
                quadTo(11.25f, 9.75f, 12f, 9.75f)
                quadTo(12.75f, 9.75f, 12.75f, 9f)
                quadTo(12.75f, 8.25f, 12f, 8.25f)
                close()
                moveTo(18f, 14.25f)
                quadTo(17.25f, 14.25f, 17.25f, 15f)
                quadTo(17.25f, 15.75f, 18f, 15.75f)
                quadTo(18.75f, 15.75f, 18.75f, 15f)
                quadTo(18.75f, 14.25f, 18f, 14.25f)
                close()
            }
        }.build()
}
