// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val AdjustmentsHorizontal: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "AdjustmentsHorizontal",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(3.75f, 5.25f)
                lineTo(6.83f, 5.25f)
                quadTo(7.16f, 3.75f, 9f, 3.75f)
                quadTo(10.84f, 3.75f, 11.17f, 5.25f)
                lineTo(20.25f, 5.25f)
                quadTo(20.56f, 5.25f, 20.78f, 5.47f)
                quadTo(21f, 5.69f, 21f, 6f)
                quadTo(21f, 6.31f, 20.78f, 6.53f)
                quadTo(20.56f, 6.75f, 20.25f, 6.75f)
                lineTo(11.17f, 6.75f)
                quadTo(10.84f, 8.25f, 9f, 8.25f)
                quadTo(7.16f, 8.25f, 6.83f, 6.75f)
                lineTo(3.75f, 6.75f)
                quadTo(3.44f, 6.75f, 3.22f, 6.53f)
                quadTo(3f, 6.31f, 3f, 6f)
                quadTo(3f, 5.69f, 3.22f, 5.47f)
                quadTo(3.44f, 5.25f, 3.75f, 5.25f)
                close()
                moveTo(3.75f, 17.25f)
                lineTo(6.83f, 17.25f)
                quadTo(7.16f, 15.75f, 9f, 15.75f)
                quadTo(10.84f, 15.75f, 11.17f, 17.25f)
                lineTo(20.25f, 17.25f)
                quadTo(20.56f, 17.25f, 20.78f, 17.47f)
                quadTo(21f, 17.69f, 21f, 18f)
                quadTo(21f, 18.31f, 20.78f, 18.53f)
                quadTo(20.56f, 18.75f, 20.25f, 18.75f)
                lineTo(11.17f, 18.75f)
                quadTo(10.84f, 20.25f, 9f, 20.25f)
                quadTo(7.16f, 20.25f, 6.83f, 18.75f)
                lineTo(3.75f, 18.75f)
                quadTo(3.44f, 18.75f, 3.22f, 18.53f)
                quadTo(3f, 18.31f, 3f, 18f)
                quadTo(3f, 17.69f, 3.22f, 17.47f)
                quadTo(3.44f, 17.25f, 3.75f, 17.25f)
                close()
                moveTo(3.75f, 11.25f)
                lineTo(12.83f, 11.25f)
                quadTo(13.16f, 9.75f, 15f, 9.75f)
                quadTo(16.84f, 9.75f, 17.17f, 11.25f)
                lineTo(20.25f, 11.25f)
                quadTo(20.56f, 11.25f, 20.78f, 11.47f)
                quadTo(21f, 11.69f, 21f, 12f)
                quadTo(21f, 12.31f, 20.78f, 12.53f)
                quadTo(20.56f, 12.75f, 20.25f, 12.75f)
                lineTo(17.17f, 12.75f)
                quadTo(16.84f, 14.25f, 15f, 14.25f)
                quadTo(13.16f, 14.25f, 12.83f, 12.75f)
                lineTo(3.75f, 12.75f)
                quadTo(3.44f, 12.75f, 3.22f, 12.53f)
                quadTo(3f, 12.31f, 3f, 12f)
                quadTo(3f, 11.69f, 3.22f, 11.47f)
                quadTo(3.44f, 11.25f, 3.75f, 11.25f)
                close()
                moveTo(9.75f, 6f)
                quadTo(9.75f, 5.25f, 9f, 5.25f)
                quadTo(8.25f, 5.25f, 8.25f, 6f)
                quadTo(8.25f, 6.75f, 9f, 6.75f)
                quadTo(9.75f, 6.75f, 9.75f, 6f)
                close()
                moveTo(15.75f, 12f)
                quadTo(15.75f, 11.25f, 15f, 11.25f)
                quadTo(14.25f, 11.25f, 14.25f, 12f)
                quadTo(14.25f, 12.75f, 15f, 12.75f)
                quadTo(15.75f, 12.75f, 15.75f, 12f)
                close()
                moveTo(9.75f, 18f)
                quadTo(9.75f, 17.25f, 9f, 17.25f)
                quadTo(8.25f, 17.25f, 8.25f, 18f)
                quadTo(8.25f, 18.75f, 9f, 18.75f)
                quadTo(9.75f, 18.75f, 9.75f, 18f)
                close()
            }
        }.build()
}
