// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val ArchiveBoxXMark: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "ArchiveBoxXMark",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(20.96f, 8.23f)
                lineTo(20.37f, 18.18f)
                quadTo(20.21f, 21f, 17.38f, 21f)
                lineTo(6.62f, 21f)
                quadTo(3.79f, 21f, 3.63f, 18.18f)
                lineTo(3.04f, 8.23f)
                quadTo(1.5f, 8.07f, 1.5f, 6.38f)
                lineTo(1.5f, 4.88f)
                quadTo(1.5f, 3f, 3.38f, 3f)
                lineTo(20.62f, 3f)
                quadTo(22.5f, 3f, 22.5f, 4.88f)
                lineTo(22.5f, 6.38f)
                quadTo(22.5f, 8.07f, 20.96f, 8.23f)
                close()
                moveTo(4.54f, 8.25f)
                lineTo(5.12f, 18.09f)
                quadTo(5.21f, 19.5f, 6.62f, 19.5f)
                lineTo(17.38f, 19.5f)
                quadTo(18.79f, 19.5f, 18.88f, 18.09f)
                lineTo(19.45f, 8.25f)
                lineTo(4.54f, 8.25f)
                close()
                moveTo(3.38f, 6.75f)
                lineTo(3.74f, 6.75f)
                quadTo(3.76f, 6.75f, 3.77f, 6.75f)
                lineTo(20.23f, 6.75f)
                quadTo(20.24f, 6.75f, 20.26f, 6.75f)
                lineTo(20.62f, 6.75f)
                quadTo(21f, 6.75f, 21f, 6.38f)
                lineTo(21f, 4.88f)
                quadTo(21f, 4.5f, 20.62f, 4.5f)
                lineTo(3.38f, 4.5f)
                quadTo(3f, 4.5f, 3f, 4.88f)
                lineTo(3f, 6.38f)
                quadTo(3f, 6.75f, 3.38f, 6.75f)
                close()
                moveTo(10.28f, 11.1f)
                lineTo(12f, 12.81f)
                lineTo(13.72f, 11.1f)
                quadTo(13.94f, 10.88f, 14.25f, 10.88f)
                quadTo(14.56f, 10.88f, 14.78f, 11.1f)
                quadTo(15f, 11.31f, 15f, 11.62f)
                quadTo(15f, 11.94f, 14.78f, 12.15f)
                lineTo(13.06f, 13.88f)
                lineTo(14.78f, 15.6f)
                quadTo(15f, 15.81f, 15f, 16.12f)
                quadTo(15f, 16.44f, 14.78f, 16.66f)
                quadTo(14.56f, 16.88f, 14.25f, 16.88f)
                quadTo(13.94f, 16.88f, 13.72f, 16.66f)
                lineTo(12f, 14.94f)
                lineTo(10.28f, 16.66f)
                quadTo(10.06f, 16.88f, 9.75f, 16.88f)
                quadTo(9.44f, 16.88f, 9.22f, 16.66f)
                quadTo(9f, 16.44f, 9f, 16.12f)
                quadTo(9f, 15.81f, 9.22f, 15.6f)
                lineTo(10.94f, 13.88f)
                lineTo(9.22f, 12.15f)
                quadTo(9f, 11.94f, 9f, 11.62f)
                quadTo(9f, 11.31f, 9.22f, 11.1f)
                quadTo(9.44f, 10.88f, 9.75f, 10.88f)
                quadTo(10.06f, 10.88f, 10.28f, 11.1f)
                close()
            }
        }.build()
}
