// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val ArrowRightStartOnRectangle: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "ArrowRightStartOnRectangle",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(15f, 9f)
                lineTo(15f, 5.25f)
                quadTo(15f, 3.75f, 13.5f, 3.75f)
                lineTo(7.5f, 3.75f)
                quadTo(6f, 3.75f, 6f, 5.25f)
                lineTo(6f, 18.75f)
                quadTo(6f, 20.25f, 7.5f, 20.25f)
                lineTo(13.5f, 20.25f)
                quadTo(15f, 20.25f, 15f, 18.75f)
                lineTo(15f, 15f)
                quadTo(15f, 14.69f, 15.22f, 14.47f)
                quadTo(15.44f, 14.25f, 15.75f, 14.25f)
                quadTo(16.06f, 14.25f, 16.28f, 14.47f)
                quadTo(16.5f, 14.69f, 16.5f, 15f)
                lineTo(16.5f, 18.75f)
                quadTo(16.5f, 21.75f, 13.5f, 21.75f)
                lineTo(7.5f, 21.75f)
                quadTo(4.5f, 21.75f, 4.5f, 18.75f)
                lineTo(4.5f, 5.25f)
                quadTo(4.5f, 2.25f, 7.5f, 2.25f)
                lineTo(13.5f, 2.25f)
                quadTo(16.5f, 2.25f, 16.5f, 5.25f)
                lineTo(16.5f, 9f)
                quadTo(16.5f, 9.31f, 16.28f, 9.53f)
                quadTo(16.06f, 9.75f, 15.75f, 9.75f)
                quadTo(15.44f, 9.75f, 15.22f, 9.53f)
                quadTo(15f, 9.31f, 15f, 9f)
                close()
                moveTo(18.22f, 14.47f)
                lineTo(19.94f, 12.75f)
                lineTo(9f, 12.75f)
                quadTo(8.69f, 12.75f, 8.47f, 12.53f)
                quadTo(8.25f, 12.31f, 8.25f, 12f)
                quadTo(8.25f, 11.69f, 8.47f, 11.47f)
                quadTo(8.69f, 11.25f, 9f, 11.25f)
                lineTo(19.94f, 11.25f)
                lineTo(18.22f, 9.53f)
                quadTo(18f, 9.31f, 18f, 9f)
                quadTo(18f, 8.69f, 18.22f, 8.47f)
                quadTo(18.44f, 8.25f, 18.75f, 8.25f)
                quadTo(19.06f, 8.25f, 19.28f, 8.47f)
                lineTo(22.28f, 11.47f)
                quadTo(22.49f, 11.68f, 22.5f, 11.96f)
                quadTo(22.5f, 11.98f, 22.5f, 12f)
                quadTo(22.5f, 12.27f, 22.33f, 12.47f)
                quadTo(22.31f, 12.5f, 22.28f, 12.53f)
                lineTo(19.28f, 15.53f)
                quadTo(19.06f, 15.75f, 18.75f, 15.75f)
                quadTo(18.44f, 15.75f, 18.22f, 15.53f)
                quadTo(18f, 15.31f, 18f, 15f)
                quadTo(18f, 14.69f, 18.22f, 14.47f)
                close()
            }
        }.build()
}
