// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val ArrowDownOnSquareStack: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "ArrowDownOnSquareStack",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(7.5f, 8.25f)
                lineTo(6.75f, 8.25f)
                quadTo(5.25f, 8.25f, 5.25f, 9.75f)
                lineTo(5.25f, 17.25f)
                quadTo(5.25f, 18.75f, 6.75f, 18.75f)
                lineTo(14.25f, 18.75f)
                quadTo(15.75f, 18.75f, 15.75f, 17.25f)
                lineTo(15.75f, 9.75f)
                quadTo(15.75f, 8.25f, 14.25f, 8.25f)
                lineTo(13.5f, 8.25f)
                quadTo(13.19f, 8.25f, 12.97f, 8.03f)
                quadTo(12.75f, 7.81f, 12.75f, 7.5f)
                quadTo(12.75f, 7.19f, 12.97f, 6.97f)
                quadTo(13.19f, 6.75f, 13.5f, 6.75f)
                lineTo(14.25f, 6.75f)
                quadTo(17.25f, 6.75f, 17.25f, 9.75f)
                quadTo(20.25f, 9.75f, 20.25f, 12.75f)
                lineTo(20.25f, 20.25f)
                quadTo(20.25f, 23.25f, 17.25f, 23.25f)
                lineTo(9.75f, 23.25f)
                quadTo(6.75f, 23.25f, 6.75f, 20.25f)
                quadTo(3.75f, 20.25f, 3.75f, 17.25f)
                lineTo(3.75f, 9.75f)
                quadTo(3.75f, 6.75f, 6.75f, 6.75f)
                lineTo(7.5f, 6.75f)
                quadTo(7.81f, 6.75f, 8.03f, 6.97f)
                quadTo(8.25f, 7.19f, 8.25f, 7.5f)
                quadTo(8.25f, 7.81f, 8.03f, 8.03f)
                quadTo(7.81f, 8.25f, 7.5f, 8.25f)
                close()
                moveTo(8.03f, 10.72f)
                lineTo(9.75f, 12.44f)
                lineTo(9.75f, 1.5f)
                quadTo(9.75f, 1.19f, 9.97f, 0.97f)
                quadTo(10.19f, 0.75f, 10.5f, 0.75f)
                quadTo(10.81f, 0.75f, 11.03f, 0.97f)
                quadTo(11.25f, 1.19f, 11.25f, 1.5f)
                lineTo(11.25f, 12.44f)
                lineTo(12.97f, 10.72f)
                quadTo(13.19f, 10.5f, 13.5f, 10.5f)
                quadTo(13.81f, 10.5f, 14.03f, 10.72f)
                quadTo(14.25f, 10.94f, 14.25f, 11.25f)
                quadTo(14.25f, 11.56f, 14.03f, 11.78f)
                lineTo(11.03f, 14.78f)
                quadTo(10.81f, 15f, 10.5f, 15f)
                quadTo(10.23f, 15f, 10.03f, 14.83f)
                quadTo(10f, 14.81f, 9.97f, 14.78f)
                lineTo(6.97f, 11.78f)
                quadTo(6.75f, 11.56f, 6.75f, 11.25f)
                quadTo(6.75f, 10.94f, 6.97f, 10.72f)
                quadTo(7.19f, 10.5f, 7.5f, 10.5f)
                quadTo(7.81f, 10.5f, 8.03f, 10.72f)
                close()
                moveTo(8.25f, 20.25f)
                quadTo(8.25f, 21.75f, 9.75f, 21.75f)
                lineTo(17.25f, 21.75f)
                quadTo(18.75f, 21.75f, 18.75f, 20.25f)
                lineTo(18.75f, 12.75f)
                quadTo(18.75f, 11.25f, 17.25f, 11.25f)
                lineTo(17.25f, 17.25f)
                quadTo(17.25f, 20.25f, 14.25f, 20.25f)
                lineTo(8.25f, 20.25f)
                close()
            }
        }.build()
}
