// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val ArrowLeftCircle: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "ArrowLeftCircle",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(21.75f, 12f)
                quadTo(21.75f, 16.04f, 18.89f, 18.89f)
                quadTo(16.04f, 21.75f, 12f, 21.75f)
                quadTo(7.96f, 21.75f, 5.11f, 18.89f)
                quadTo(2.25f, 16.04f, 2.25f, 12f)
                quadTo(2.25f, 7.96f, 5.11f, 5.11f)
                quadTo(7.96f, 2.25f, 12f, 2.25f)
                quadTo(16.04f, 2.25f, 18.89f, 5.11f)
                quadTo(21.75f, 7.96f, 21.75f, 12f)
                close()
                moveTo(20.25f, 12f)
                quadTo(20.25f, 8.58f, 17.83f, 6.17f)
                quadTo(15.42f, 3.75f, 12f, 3.75f)
                quadTo(8.58f, 3.75f, 6.17f, 6.17f)
                quadTo(3.75f, 8.58f, 3.75f, 12f)
                quadTo(3.75f, 15.42f, 6.17f, 17.83f)
                quadTo(8.58f, 20.25f, 12f, 20.25f)
                quadTo(15.42f, 20.25f, 17.83f, 17.83f)
                quadTo(20.25f, 15.42f, 20.25f, 12f)
                close()
                moveTo(11.78f, 9.53f)
                lineTo(10.06f, 11.25f)
                lineTo(15.75f, 11.25f)
                quadTo(16.06f, 11.25f, 16.28f, 11.47f)
                quadTo(16.5f, 11.69f, 16.5f, 12f)
                quadTo(16.5f, 12.31f, 16.28f, 12.53f)
                quadTo(16.06f, 12.75f, 15.75f, 12.75f)
                lineTo(10.06f, 12.75f)
                lineTo(11.78f, 14.47f)
                quadTo(12f, 14.69f, 12f, 15f)
                quadTo(12f, 15.31f, 11.78f, 15.53f)
                quadTo(11.56f, 15.75f, 11.25f, 15.75f)
                quadTo(10.94f, 15.75f, 10.72f, 15.53f)
                lineTo(7.72f, 12.53f)
                lineTo(7.72f, 12.53f)
                quadTo(7.51f, 12.32f, 7.5f, 12.04f)
                quadTo(7.5f, 12.02f, 7.5f, 12f)
                quadTo(7.5f, 11.69f, 7.72f, 11.47f)
                lineTo(7.72f, 11.47f)
                lineTo(10.72f, 8.47f)
                quadTo(10.94f, 8.25f, 11.25f, 8.25f)
                quadTo(11.56f, 8.25f, 11.78f, 8.47f)
                quadTo(12f, 8.69f, 12f, 9f)
                quadTo(12f, 9.31f, 11.78f, 9.53f)
                close()
            }
        }.build()
}
