// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val ArrowsPointingIn: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "ArrowsPointingIn",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(14.25f, 9f)
                lineTo(14.25f, 4.5f)
                quadTo(14.25f, 4.19f, 14.47f, 3.97f)
                quadTo(14.69f, 3.75f, 15f, 3.75f)
                quadTo(15.31f, 3.75f, 15.53f, 3.97f)
                quadTo(15.75f, 4.19f, 15.75f, 4.5f)
                lineTo(15.75f, 7.19f)
                lineTo(19.72f, 3.22f)
                quadTo(19.94f, 3f, 20.25f, 3f)
                quadTo(20.56f, 3f, 20.78f, 3.22f)
                quadTo(21f, 3.44f, 21f, 3.75f)
                quadTo(21f, 4.06f, 20.78f, 4.28f)
                lineTo(16.81f, 8.25f)
                lineTo(19.5f, 8.25f)
                quadTo(19.81f, 8.25f, 20.03f, 8.47f)
                quadTo(20.25f, 8.69f, 20.25f, 9f)
                quadTo(20.25f, 9.31f, 20.03f, 9.53f)
                quadTo(19.81f, 9.75f, 19.5f, 9.75f)
                lineTo(15f, 9.75f)
                quadTo(14.69f, 9.75f, 14.47f, 9.53f)
                quadTo(14.25f, 9.31f, 14.25f, 9f)
                close()
                moveTo(9f, 9.75f)
                lineTo(4.5f, 9.75f)
                quadTo(4.19f, 9.75f, 3.97f, 9.53f)
                quadTo(3.75f, 9.31f, 3.75f, 9f)
                quadTo(3.75f, 8.69f, 3.97f, 8.47f)
                quadTo(4.19f, 8.25f, 4.5f, 8.25f)
                lineTo(7.19f, 8.25f)
                lineTo(3.22f, 4.28f)
                quadTo(3f, 4.06f, 3f, 3.75f)
                quadTo(3f, 3.44f, 3.22f, 3.22f)
                quadTo(3.44f, 3f, 3.75f, 3f)
                quadTo(4.06f, 3f, 4.28f, 3.22f)
                lineTo(8.25f, 7.19f)
                lineTo(8.25f, 4.5f)
                quadTo(8.25f, 4.19f, 8.47f, 3.97f)
                quadTo(8.69f, 3.75f, 9f, 3.75f)
                quadTo(9.31f, 3.75f, 9.53f, 3.97f)
                quadTo(9.75f, 4.19f, 9.75f, 4.5f)
                lineTo(9.75f, 9f)
                quadTo(9.75f, 9.31f, 9.53f, 9.53f)
                quadTo(9.31f, 9.75f, 9f, 9.75f)
                close()
                moveTo(9.75f, 15f)
                lineTo(9.75f, 19.5f)
                quadTo(9.75f, 19.81f, 9.53f, 20.03f)
                quadTo(9.31f, 20.25f, 9f, 20.25f)
                quadTo(8.69f, 20.25f, 8.47f, 20.03f)
                quadTo(8.25f, 19.81f, 8.25f, 19.5f)
                lineTo(8.25f, 16.81f)
                lineTo(4.28f, 20.78f)
                quadTo(4.06f, 21f, 3.75f, 21f)
                quadTo(3.44f, 21f, 3.22f, 20.78f)
                quadTo(3f, 20.56f, 3f, 20.25f)
                quadTo(3f, 19.94f, 3.22f, 19.72f)
                lineTo(7.19f, 15.75f)
                lineTo(4.5f, 15.75f)
                quadTo(4.19f, 15.75f, 3.97f, 15.53f)
                quadTo(3.75f, 15.31f, 3.75f, 15f)
                quadTo(3.75f, 14.69f, 3.97f, 14.47f)
                quadTo(4.19f, 14.25f, 4.5f, 14.25f)
                lineTo(9f, 14.25f)
                quadTo(9.27f, 14.25f, 9.47f, 14.42f)
                quadTo(9.5f, 14.44f, 9.53f, 14.47f)
                quadTo(9.75f, 14.69f, 9.75f, 15f)
                close()
                moveTo(15f, 14.25f)
                lineTo(19.5f, 14.25f)
                quadTo(19.81f, 14.25f, 20.03f, 14.47f)
                quadTo(20.25f, 14.69f, 20.25f, 15f)
                quadTo(20.25f, 15.31f, 20.03f, 15.53f)
                quadTo(19.81f, 15.75f, 19.5f, 15.75f)
                lineTo(16.81f, 15.75f)
                lineTo(20.78f, 19.72f)
                quadTo(21f, 19.94f, 21f, 20.25f)
                quadTo(21f, 20.56f, 20.78f, 20.78f)
                quadTo(20.56f, 21f, 20.25f, 21f)
                quadTo(19.94f, 21f, 19.72f, 20.78f)
                lineTo(15.75f, 16.81f)
                lineTo(15.75f, 19.5f)
                quadTo(15.75f, 19.81f, 15.53f, 20.03f)
                quadTo(15.31f, 20.25f, 15f, 20.25f)
                quadTo(14.69f, 20.25f, 14.47f, 20.03f)
                quadTo(14.25f, 19.81f, 14.25f, 19.5f)
                lineTo(14.25f, 15f)
                quadTo(14.25f, 14.73f, 14.42f, 14.53f)
                quadTo(14.44f, 14.5f, 14.47f, 14.47f)
                quadTo(14.68f, 14.26f, 14.96f, 14.25f)
                quadTo(14.98f, 14.25f, 15f, 14.25f)
                close()
            }
        }.build()
}
