// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val ArrowTopRightOnSquare: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "ArrowTopRightOnSquare",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(13.5f, 6.75f)
                lineTo(5.25f, 6.75f)
                quadTo(3.75f, 6.75f, 3.75f, 8.25f)
                lineTo(3.75f, 18.75f)
                quadTo(3.75f, 20.25f, 5.25f, 20.25f)
                lineTo(15.75f, 20.25f)
                quadTo(17.25f, 20.25f, 17.25f, 18.75f)
                lineTo(17.25f, 10.5f)
                quadTo(17.25f, 10.19f, 17.47f, 9.97f)
                quadTo(17.69f, 9.75f, 18f, 9.75f)
                quadTo(18.31f, 9.75f, 18.53f, 9.97f)
                quadTo(18.75f, 10.19f, 18.75f, 10.5f)
                lineTo(18.75f, 18.75f)
                quadTo(18.75f, 21.75f, 15.75f, 21.75f)
                lineTo(5.25f, 21.75f)
                quadTo(2.25f, 21.75f, 2.25f, 18.75f)
                lineTo(2.25f, 8.25f)
                quadTo(2.25f, 5.25f, 5.25f, 5.25f)
                lineTo(13.5f, 5.25f)
                quadTo(13.81f, 5.25f, 14.03f, 5.47f)
                quadTo(14.25f, 5.69f, 14.25f, 6f)
                quadTo(14.25f, 6.31f, 14.03f, 6.53f)
                quadTo(13.81f, 6.75f, 13.5f, 6.75f)
                close()
                moveTo(6.97f, 15.97f)
                lineTo(19.19f, 3.75f)
                lineTo(15.75f, 3.75f)
                quadTo(15.44f, 3.75f, 15.22f, 3.53f)
                quadTo(15f, 3.31f, 15f, 3f)
                quadTo(15f, 2.69f, 15.22f, 2.47f)
                quadTo(15.44f, 2.25f, 15.75f, 2.25f)
                lineTo(21f, 2.25f)
                lineTo(21f, 2.25f)
                quadTo(21.31f, 2.25f, 21.53f, 2.47f)
                quadTo(21.75f, 2.69f, 21.75f, 3f)
                lineTo(21.75f, 8.25f)
                quadTo(21.75f, 8.56f, 21.53f, 8.78f)
                quadTo(21.31f, 9f, 21f, 9f)
                quadTo(20.69f, 9f, 20.47f, 8.78f)
                quadTo(20.25f, 8.56f, 20.25f, 8.25f)
                lineTo(20.25f, 4.81f)
                lineTo(8.03f, 17.03f)
                quadTo(7.81f, 17.25f, 7.5f, 17.25f)
                quadTo(7.19f, 17.25f, 6.97f, 17.03f)
                quadTo(6.75f, 16.81f, 6.75f, 16.5f)
                quadTo(6.75f, 16.19f, 6.97f, 15.97f)
                close()
            }
        }.build()
}
