// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val ArrowsPointingOut: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "ArrowsPointingOut",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(20.25f, 21f)
                lineTo(15.75f, 21f)
                quadTo(15.44f, 21f, 15.22f, 20.78f)
                quadTo(15f, 20.56f, 15f, 20.25f)
                quadTo(15f, 19.94f, 15.22f, 19.72f)
                quadTo(15.44f, 19.5f, 15.75f, 19.5f)
                lineTo(18.44f, 19.5f)
                lineTo(14.47f, 15.53f)
                quadTo(14.25f, 15.31f, 14.25f, 15f)
                quadTo(14.25f, 14.69f, 14.47f, 14.47f)
                quadTo(14.69f, 14.25f, 15f, 14.25f)
                quadTo(15.31f, 14.25f, 15.53f, 14.47f)
                lineTo(19.5f, 18.44f)
                lineTo(19.5f, 15.75f)
                quadTo(19.5f, 15.44f, 19.72f, 15.22f)
                quadTo(19.94f, 15f, 20.25f, 15f)
                quadTo(20.56f, 15f, 20.78f, 15.22f)
                quadTo(21f, 15.44f, 21f, 15.75f)
                lineTo(21f, 20.25f)
                quadTo(21f, 20.56f, 20.78f, 20.78f)
                quadTo(20.57f, 20.99f, 20.29f, 21f)
                quadTo(20.27f, 21f, 20.25f, 21f)
                close()
                moveTo(21f, 3.75f)
                lineTo(21f, 8.25f)
                quadTo(21f, 8.56f, 20.78f, 8.78f)
                quadTo(20.56f, 9f, 20.25f, 9f)
                quadTo(19.94f, 9f, 19.72f, 8.78f)
                quadTo(19.5f, 8.56f, 19.5f, 8.25f)
                lineTo(19.5f, 5.56f)
                lineTo(15.53f, 9.53f)
                quadTo(15.31f, 9.75f, 15f, 9.75f)
                quadTo(14.69f, 9.75f, 14.47f, 9.53f)
                quadTo(14.25f, 9.31f, 14.25f, 9f)
                quadTo(14.25f, 8.69f, 14.47f, 8.47f)
                lineTo(18.44f, 4.5f)
                lineTo(15.75f, 4.5f)
                quadTo(15.44f, 4.5f, 15.22f, 4.28f)
                quadTo(15f, 4.06f, 15f, 3.75f)
                quadTo(15f, 3.44f, 15.22f, 3.22f)
                quadTo(15.44f, 3f, 15.75f, 3f)
                lineTo(20.25f, 3f)
                quadTo(20.52f, 3f, 20.72f, 3.17f)
                quadTo(20.75f, 3.19f, 20.78f, 3.22f)
                quadTo(21f, 3.44f, 21f, 3.75f)
                close()
                moveTo(3f, 20.25f)
                lineTo(3f, 15.75f)
                quadTo(3f, 15.44f, 3.22f, 15.22f)
                quadTo(3.44f, 15f, 3.75f, 15f)
                quadTo(4.06f, 15f, 4.28f, 15.22f)
                quadTo(4.5f, 15.44f, 4.5f, 15.75f)
                lineTo(4.5f, 18.44f)
                lineTo(8.47f, 14.47f)
                quadTo(8.69f, 14.25f, 9f, 14.25f)
                quadTo(9.31f, 14.25f, 9.53f, 14.47f)
                quadTo(9.75f, 14.69f, 9.75f, 15f)
                quadTo(9.75f, 15.31f, 9.53f, 15.53f)
                lineTo(5.56f, 19.5f)
                lineTo(8.25f, 19.5f)
                quadTo(8.56f, 19.5f, 8.78f, 19.72f)
                quadTo(9f, 19.94f, 9f, 20.25f)
                quadTo(9f, 20.56f, 8.78f, 20.78f)
                quadTo(8.56f, 21f, 8.25f, 21f)
                lineTo(3.75f, 21f)
                quadTo(3.44f, 21f, 3.22f, 20.78f)
                quadTo(3.01f, 20.57f, 3f, 20.29f)
                quadTo(3f, 20.27f, 3f, 20.25f)
                close()
                moveTo(3.75f, 3f)
                lineTo(8.25f, 3f)
                quadTo(8.56f, 3f, 8.78f, 3.22f)
                quadTo(9f, 3.44f, 9f, 3.75f)
                quadTo(9f, 4.06f, 8.78f, 4.28f)
                quadTo(8.56f, 4.5f, 8.25f, 4.5f)
                lineTo(5.56f, 4.5f)
                lineTo(9.53f, 8.47f)
                quadTo(9.75f, 8.69f, 9.75f, 9f)
                quadTo(9.75f, 9.31f, 9.53f, 9.53f)
                quadTo(9.31f, 9.75f, 9f, 9.75f)
                quadTo(8.69f, 9.75f, 8.47f, 9.53f)
                lineTo(4.5f, 5.56f)
                lineTo(4.5f, 8.25f)
                quadTo(4.5f, 8.56f, 4.28f, 8.78f)
                quadTo(4.06f, 9f, 3.75f, 9f)
                quadTo(3.44f, 9f, 3.22f, 8.78f)
                quadTo(3f, 8.56f, 3f, 8.25f)
                lineTo(3f, 3.75f)
                quadTo(3f, 3.44f, 3.22f, 3.22f)
                quadTo(3.44f, 3f, 3.75f, 3f)
                close()
            }
        }.build()
}
