// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Beaker: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "Beaker",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(9.65f, 2.36f)
                quadTo(9.67f, 2.36f, 9.7f, 2.36f)
                quadTo(12f, 2.14f, 14.3f, 2.36f)
                quadTo(14.33f, 2.36f, 14.35f, 2.36f)
                quadTo(14.74f, 2.4f, 15.1f, 2.44f)
                quadTo(15.4f, 2.48f, 15.59f, 2.73f)
                quadTo(15.78f, 2.97f, 15.74f, 3.28f)
                quadTo(15.7f, 3.59f, 15.46f, 3.78f)
                quadTo(15.25f, 3.94f, 15f, 3.94f)
                lineTo(15f, 8.82f)
                quadTo(15f, 9.44f, 15.44f, 9.88f)
                lineTo(20.3f, 14.74f)
                quadTo(20.34f, 14.77f, 20.37f, 14.81f)
                lineTo(21.73f, 16.17f)
                quadTo(22.97f, 17.41f, 22.5f, 19.07f)
                quadTo(22.01f, 20.75f, 20.26f, 21.05f)
                quadTo(16.16f, 21.75f, 12f, 21.75f)
                quadTo(7.82f, 21.75f, 3.74f, 21.05f)
                quadTo(1.99f, 20.75f, 1.5f, 19.07f)
                quadTo(1.02f, 17.41f, 2.27f, 16.17f)
                lineTo(4.44f, 14f)
                quadTo(4.47f, 13.96f, 4.51f, 13.93f)
                lineTo(8.56f, 9.88f)
                quadTo(9f, 9.44f, 9f, 8.82f)
                lineTo(9f, 3.94f)
                quadTo(8.75f, 3.94f, 8.54f, 3.78f)
                quadTo(8.3f, 3.59f, 8.26f, 3.28f)
                quadTo(8.22f, 2.97f, 8.41f, 2.73f)
                quadTo(8.6f, 2.48f, 8.9f, 2.44f)
                quadTo(9.26f, 2.4f, 9.65f, 2.36f)
                close()
                moveTo(19.57f, 16.13f)
                lineTo(18.41f, 16.42f)
                quadTo(14.9f, 17.29f, 11.66f, 15.67f)
                quadTo(8.92f, 14.3f, 5.95f, 15.04f)
                lineTo(5.38f, 15.18f)
                lineTo(3.33f, 17.23f)
                quadTo(2.71f, 17.85f, 2.94f, 18.65f)
                quadTo(3.17f, 19.43f, 3.99f, 19.57f)
                quadTo(7.95f, 20.25f, 12f, 20.25f)
                quadTo(16.03f, 20.25f, 20.01f, 19.57f)
                quadTo(20.83f, 19.43f, 21.05f, 18.65f)
                quadTo(21.29f, 17.85f, 20.67f, 17.23f)
                lineTo(19.57f, 16.13f)
                close()
                moveTo(10.5f, 3.8f)
                lineTo(10.5f, 8.82f)
                quadTo(10.5f, 10.06f, 9.62f, 10.94f)
                lineTo(7.25f, 13.31f)
                quadTo(9.88f, 13.1f, 12.34f, 14.33f)
                quadTo(15.08f, 15.7f, 18.05f, 14.96f)
                lineTo(18.33f, 14.89f)
                lineTo(14.38f, 10.94f)
                quadTo(13.5f, 10.06f, 13.5f, 8.82f)
                lineTo(13.5f, 3.8f)
                quadTo(12f, 3.7f, 10.5f, 3.8f)
                close()
            }
        }.build()
}
