// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val BellSnooze: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "BellSnooze",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(8.23f, 17.71f)
                quadTo(5.77f, 17.34f, 3.43f, 16.48f)
                quadTo(3.29f, 16.43f, 3.19f, 16.33f)
                quadTo(2.96f, 16.12f, 2.94f, 15.81f)
                quadTo(2.92f, 15.5f, 3.13f, 15.27f)
                quadTo(5.25f, 12.92f, 5.25f, 9.75f)
                lineTo(5.25f, 9f)
                quadTo(5.25f, 6.2f, 7.23f, 4.23f)
                quadTo(9.2f, 2.25f, 12f, 2.25f)
                quadTo(14.8f, 2.25f, 16.77f, 4.23f)
                quadTo(18.75f, 6.2f, 18.75f, 9f)
                lineTo(18.75f, 9.75f)
                quadTo(18.75f, 12.92f, 20.87f, 15.27f)
                quadTo(20.96f, 15.38f, 21.02f, 15.51f)
                quadTo(21.12f, 15.8f, 20.99f, 16.09f)
                quadTo(20.86f, 16.37f, 20.57f, 16.48f)
                quadTo(18.23f, 17.34f, 15.77f, 17.72f)
                quadTo(16.02f, 19.71f, 14.2f, 21.03f)
                quadTo(12f, 22.63f, 9.8f, 21.03f)
                quadTo(7.98f, 19.71f, 8.23f, 17.71f)
                close()
                moveTo(14.73f, 16.34f)
                quadTo(14.78f, 16.33f, 14.82f, 16.33f)
                quadTo(16.98f, 16.07f, 19.05f, 15.41f)
                quadTo(17.25f, 12.93f, 17.25f, 9.75f)
                lineTo(17.25f, 9f)
                quadTo(17.25f, 6.83f, 15.71f, 5.29f)
                quadTo(14.18f, 3.75f, 12f, 3.75f)
                quadTo(9.82f, 3.75f, 8.29f, 5.29f)
                quadTo(6.75f, 6.83f, 6.75f, 9f)
                lineTo(6.75f, 9.75f)
                quadTo(6.75f, 12.93f, 4.95f, 15.41f)
                quadTo(7.01f, 16.07f, 9.18f, 16.33f)
                quadTo(9.22f, 16.33f, 9.27f, 16.34f)
                quadTo(12f, 16.66f, 14.73f, 16.34f)
                close()
                moveTo(10.5f, 7.5f)
                lineTo(13.5f, 7.5f)
                quadTo(13.81f, 7.5f, 14.03f, 7.72f)
                quadTo(14.25f, 7.94f, 14.25f, 8.25f)
                quadTo(14.25f, 8.48f, 14.12f, 8.67f)
                lineTo(11.9f, 12f)
                lineTo(13.5f, 12f)
                quadTo(13.81f, 12f, 14.03f, 12.22f)
                quadTo(14.25f, 12.44f, 14.25f, 12.75f)
                quadTo(14.25f, 13.06f, 14.03f, 13.28f)
                quadTo(13.81f, 13.5f, 13.5f, 13.5f)
                lineTo(10.5f, 13.5f)
                quadTo(10.27f, 13.5f, 10.08f, 13.37f)
                quadTo(9.82f, 13.2f, 9.77f, 12.9f)
                quadTo(9.7f, 12.59f, 9.88f, 12.33f)
                lineTo(12.1f, 9f)
                lineTo(10.5f, 9f)
                quadTo(10.19f, 9f, 9.97f, 8.78f)
                quadTo(9.75f, 8.56f, 9.75f, 8.25f)
                quadTo(9.75f, 7.94f, 9.97f, 7.72f)
                quadTo(10.19f, 7.5f, 10.5f, 7.5f)
                close()
                moveTo(14.27f, 17.9f)
                quadTo(12f, 18.11f, 9.73f, 17.9f)
                quadTo(9.62f, 19.05f, 10.68f, 19.82f)
                quadTo(12f, 20.78f, 13.32f, 19.82f)
                quadTo(14.38f, 19.05f, 14.27f, 17.9f)
                close()
            }
        }.build()
}
