// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val BoltSlash: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "BoltSlash",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(7.92f, 8.98f)
                lineTo(2.47f, 3.53f)
                quadTo(2.25f, 3.31f, 2.25f, 3f)
                quadTo(2.25f, 2.69f, 2.47f, 2.47f)
                quadTo(2.69f, 2.25f, 3f, 2.25f)
                quadTo(3.31f, 2.25f, 3.53f, 2.47f)
                lineTo(8.44f, 7.38f)
                lineTo(13.7f, 1.74f)
                quadTo(13.91f, 1.51f, 14.22f, 1.5f)
                quadTo(14.54f, 1.49f, 14.76f, 1.7f)
                quadTo(15.09f, 2.01f, 14.97f, 2.45f)
                lineTo(12.98f, 9.75f)
                lineTo(20.25f, 9.75f)
                quadTo(20.56f, 9.75f, 20.78f, 9.97f)
                quadTo(21f, 10.19f, 21f, 10.5f)
                quadTo(21f, 10.8f, 20.8f, 11.01f)
                lineTo(16.59f, 15.53f)
                lineTo(21.53f, 20.47f)
                quadTo(21.75f, 20.69f, 21.75f, 21f)
                quadTo(21.75f, 21.31f, 21.53f, 21.53f)
                quadTo(21.31f, 21.75f, 21f, 21.75f)
                quadTo(20.69f, 21.75f, 20.47f, 21.53f)
                lineTo(15.02f, 16.08f)
                quadTo(15.01f, 16.07f, 15f, 16.06f)
                lineTo(7.93f, 8.99f)
                quadTo(7.92f, 8.98f, 7.92f, 8.98f)
                close()
                moveTo(12.14f, 15.85f)
                lineTo(11.27f, 19.02f)
                lineTo(12.95f, 17.23f)
                quadTo(13.16f, 17f, 13.47f, 16.99f)
                quadTo(13.78f, 16.98f, 14.01f, 17.19f)
                quadTo(14.23f, 17.4f, 14.24f, 17.71f)
                quadTo(14.26f, 18.02f, 14.04f, 18.25f)
                lineTo(10.3f, 22.26f)
                quadTo(9.99f, 22.59f, 9.55f, 22.47f)
                quadTo(9.25f, 22.39f, 9.1f, 22.12f)
                quadTo(8.95f, 21.85f, 9.03f, 21.55f)
                lineTo(10.69f, 15.46f)
                quadTo(10.77f, 15.16f, 11.04f, 15f)
                quadTo(11.31f, 14.85f, 11.61f, 14.93f)
                quadTo(11.91f, 15.01f, 12.06f, 15.28f)
                quadTo(12.22f, 15.55f, 12.14f, 15.85f)
                close()
                moveTo(9.26f, 14.25f)
                lineTo(3.75f, 14.25f)
                quadTo(3.44f, 14.25f, 3.22f, 14.03f)
                quadTo(3f, 13.81f, 3f, 13.5f)
                quadTo(3f, 13.2f, 3.2f, 12.99f)
                lineTo(5.86f, 10.14f)
                quadTo(6.07f, 9.91f, 6.38f, 9.9f)
                quadTo(6.69f, 9.89f, 6.92f, 10.1f)
                quadTo(7.15f, 10.31f, 7.16f, 10.62f)
                quadTo(7.17f, 10.94f, 6.96f, 11.16f)
                lineTo(5.48f, 12.75f)
                lineTo(9.26f, 12.75f)
                quadTo(9.57f, 12.75f, 9.79f, 12.97f)
                quadTo(10.01f, 13.19f, 10.01f, 13.5f)
                quadTo(10.01f, 13.81f, 9.79f, 14.03f)
                quadTo(9.57f, 14.25f, 9.26f, 14.25f)
                close()
                moveTo(15.52f, 14.46f)
                lineTo(18.52f, 11.25f)
                lineTo(12.31f, 11.25f)
                lineTo(15.52f, 14.46f)
                close()
                moveTo(11.29f, 10.23f)
                lineTo(12.73f, 4.98f)
                lineTo(9.5f, 8.44f)
                lineTo(11.29f, 10.23f)
                close()
            }
        }.build()
}
