// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val BookmarkSlash: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "BookmarkSlash",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(3.53f, 2.47f)
                lineTo(4.52f, 3.46f)
                quadTo(5.18f, 2.71f, 6.32f, 2.58f)
                quadTo(12f, 1.92f, 17.68f, 2.58f)
                quadTo(20.25f, 2.88f, 20.25f, 5.51f)
                lineTo(20.25f, 19.19f)
                lineTo(21.53f, 20.47f)
                quadTo(21.75f, 20.69f, 21.75f, 21f)
                quadTo(21.75f, 21.31f, 21.53f, 21.53f)
                quadTo(21.31f, 21.75f, 21f, 21.75f)
                quadTo(20.69f, 21.75f, 20.47f, 21.53f)
                lineTo(18.97f, 20.03f)
                lineTo(4.17f, 5.24f)
                quadTo(4.13f, 5.2f, 4.09f, 5.16f)
                lineTo(2.47f, 3.53f)
                quadTo(2.25f, 3.31f, 2.25f, 3f)
                quadTo(2.25f, 2.69f, 2.47f, 2.47f)
                quadTo(2.69f, 2.25f, 3f, 2.25f)
                quadTo(3.31f, 2.25f, 3.53f, 2.47f)
                close()
                moveTo(18.75f, 17.69f)
                lineTo(18.75f, 5.51f)
                quadTo(18.75f, 4.21f, 17.51f, 4.07f)
                quadTo(12f, 3.43f, 6.5f, 4.07f)
                quadTo(5.92f, 4.14f, 5.59f, 4.53f)
                lineTo(18.75f, 17.69f)
                close()
                moveTo(13.68f, 18.93f)
                lineTo(12f, 18.09f)
                lineTo(4.83f, 21.67f)
                quadTo(4.56f, 21.81f, 4.26f, 21.71f)
                quadTo(3.97f, 21.61f, 3.83f, 21.34f)
                quadTo(3.75f, 21.18f, 3.75f, 21f)
                lineTo(3.75f, 8.74f)
                quadTo(3.75f, 8.43f, 3.97f, 8.21f)
                quadTo(4.19f, 7.99f, 4.5f, 7.99f)
                quadTo(4.81f, 7.99f, 5.03f, 8.21f)
                quadTo(5.25f, 8.43f, 5.25f, 8.74f)
                lineTo(5.25f, 19.79f)
                lineTo(11.66f, 16.58f)
                quadTo(12f, 16.41f, 12.34f, 16.58f)
                lineTo(14.35f, 17.59f)
                quadTo(14.63f, 17.73f, 14.73f, 18.02f)
                quadTo(14.82f, 18.32f, 14.69f, 18.59f)
                quadTo(14.55f, 18.87f, 14.25f, 18.97f)
                quadTo(13.96f, 19.07f, 13.68f, 18.93f)
                close()
            }
        }.build()
}
