// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val BuildingLibrary: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "BuildingLibrary",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(3f, 20.25f)
                lineTo(3.75f, 20.25f)
                lineTo(3.75f, 10.33f)
                quadTo(3.75f, 10.05f, 3.93f, 9.84f)
                quadTo(4.11f, 9.63f, 4.38f, 9.59f)
                quadTo(8.16f, 9f, 12f, 9f)
                quadTo(15.83f, 9f, 19.62f, 9.59f)
                quadTo(19.89f, 9.63f, 20.07f, 9.84f)
                quadTo(20.25f, 10.05f, 20.25f, 10.33f)
                lineTo(20.25f, 20.25f)
                lineTo(21f, 20.25f)
                quadTo(21.31f, 20.25f, 21.53f, 20.47f)
                quadTo(21.75f, 20.69f, 21.75f, 21f)
                quadTo(21.75f, 21.31f, 21.53f, 21.53f)
                quadTo(21.31f, 21.75f, 21f, 21.75f)
                lineTo(3f, 21.75f)
                quadTo(2.69f, 21.75f, 2.47f, 21.53f)
                quadTo(2.25f, 21.31f, 2.25f, 21f)
                quadTo(2.25f, 20.69f, 2.47f, 20.47f)
                quadTo(2.69f, 20.25f, 3f, 20.25f)
                close()
                moveTo(18.75f, 20.25f)
                lineTo(18.75f, 10.98f)
                quadTo(15.39f, 10.5f, 12f, 10.5f)
                quadTo(8.6f, 10.5f, 5.25f, 10.98f)
                lineTo(5.25f, 20.25f)
                lineTo(7.5f, 20.25f)
                lineTo(7.5f, 12.75f)
                quadTo(7.5f, 12.44f, 7.72f, 12.22f)
                quadTo(7.94f, 12f, 8.25f, 12f)
                quadTo(8.56f, 12f, 8.78f, 12.22f)
                quadTo(9f, 12.44f, 9f, 12.75f)
                lineTo(9f, 20.25f)
                lineTo(11.25f, 20.25f)
                lineTo(11.25f, 12.75f)
                quadTo(11.25f, 12.44f, 11.47f, 12.22f)
                quadTo(11.69f, 12f, 12f, 12f)
                quadTo(12.31f, 12f, 12.53f, 12.22f)
                quadTo(12.75f, 12.44f, 12.75f, 12.75f)
                lineTo(12.75f, 20.25f)
                lineTo(15f, 20.25f)
                lineTo(15f, 12.75f)
                quadTo(15f, 12.44f, 15.22f, 12.22f)
                quadTo(15.44f, 12f, 15.75f, 12f)
                quadTo(16.06f, 12f, 16.28f, 12.22f)
                quadTo(16.5f, 12.44f, 16.5f, 12.75f)
                lineTo(16.5f, 20.25f)
                lineTo(18.75f, 20.25f)
                close()
                moveTo(2.58f, 8.38f)
                lineTo(11.58f, 2.38f)
                quadTo(12f, 2.1f, 12.42f, 2.38f)
                lineTo(21.42f, 8.38f)
                quadTo(21.68f, 8.55f, 21.73f, 8.85f)
                quadTo(21.8f, 9.16f, 21.62f, 9.42f)
                quadTo(21.45f, 9.68f, 21.15f, 9.73f)
                quadTo(20.84f, 9.8f, 20.58f, 9.62f)
                lineTo(12f, 3.9f)
                lineTo(3.42f, 9.62f)
                quadTo(3.16f, 9.8f, 2.85f, 9.73f)
                quadTo(2.55f, 9.68f, 2.38f, 9.42f)
                quadTo(2.2f, 9.16f, 2.27f, 8.85f)
                quadTo(2.33f, 8.55f, 2.58f, 8.38f)
                close()
                moveTo(12f, 6f)
                lineTo(12.01f, 6f)
                quadTo(12.32f, 6f, 12.54f, 6.22f)
                quadTo(12.76f, 6.44f, 12.76f, 6.75f)
                lineTo(12.76f, 6.76f)
                quadTo(12.76f, 7.07f, 12.54f, 7.29f)
                quadTo(12.32f, 7.51f, 12.01f, 7.51f)
                lineTo(12f, 7.51f)
                quadTo(11.69f, 7.51f, 11.47f, 7.29f)
                quadTo(11.25f, 7.07f, 11.25f, 6.76f)
                lineTo(11.25f, 6.75f)
                quadTo(11.25f, 6.44f, 11.47f, 6.22f)
                quadTo(11.69f, 6f, 12f, 6f)
                close()
            }
        }.build()
}
