// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val BuildingStorefront: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "BuildingStorefront",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(21f, 9.76f)
                lineTo(21f, 20.25f)
                lineTo(21.64f, 20.25f)
                quadTo(21.95f, 20.25f, 22.17f, 20.47f)
                quadTo(22.39f, 20.69f, 22.39f, 21f)
                quadTo(22.39f, 21.31f, 22.17f, 21.53f)
                quadTo(21.95f, 21.75f, 21.64f, 21.75f)
                lineTo(2.36f, 21.75f)
                quadTo(2.05f, 21.75f, 1.83f, 21.53f)
                quadTo(1.61f, 21.31f, 1.61f, 21f)
                quadTo(1.61f, 20.69f, 1.83f, 20.47f)
                quadTo(2.05f, 20.25f, 2.36f, 20.25f)
                lineTo(3f, 20.25f)
                lineTo(3f, 9.76f)
                quadTo(1.75f, 8.85f, 1.53f, 7.24f)
                quadTo(1.29f, 5.41f, 2.6f, 4.1f)
                lineTo(3.79f, 2.91f)
                quadTo(4.45f, 2.25f, 5.38f, 2.25f)
                lineTo(18.62f, 2.25f)
                quadTo(19.55f, 2.25f, 20.21f, 2.91f)
                lineTo(21.4f, 4.1f)
                quadTo(22.71f, 5.41f, 22.47f, 7.24f)
                quadTo(22.26f, 8.85f, 21f, 9.76f)
                close()
                moveTo(4.5f, 10.48f)
                lineTo(4.5f, 20.25f)
                lineTo(12.75f, 20.25f)
                lineTo(12.75f, 13.5f)
                quadTo(12.75f, 12f, 14.25f, 12f)
                lineTo(17.25f, 12f)
                quadTo(18.75f, 12f, 18.75f, 13.5f)
                lineTo(18.75f, 20.25f)
                lineTo(19.5f, 20.25f)
                lineTo(19.5f, 10.48f)
                quadTo(17.86f, 10.94f, 16.48f, 9.77f)
                quadTo(15.53f, 10.5f, 14.25f, 10.5f)
                quadTo(12.96f, 10.5f, 12f, 9.76f)
                quadTo(11.04f, 10.5f, 9.75f, 10.5f)
                quadTo(8.47f, 10.5f, 7.51f, 9.77f)
                quadTo(6.14f, 10.94f, 4.5f, 10.48f)
                close()
                moveTo(19.92f, 8.67f)
                quadTo(20.84f, 8.12f, 20.98f, 7.04f)
                quadTo(21.13f, 5.94f, 20.34f, 5.16f)
                lineTo(19.15f, 3.97f)
                quadTo(18.93f, 3.75f, 18.62f, 3.75f)
                lineTo(5.38f, 3.75f)
                quadTo(5.07f, 3.75f, 4.85f, 3.97f)
                lineTo(3.66f, 5.16f)
                quadTo(2.88f, 5.94f, 3.02f, 7.04f)
                quadTo(3.16f, 8.12f, 4.08f, 8.67f)
                quadTo(4.12f, 8.69f, 4.16f, 8.72f)
                quadTo(5.73f, 9.6f, 6.94f, 8.24f)
                quadTo(7.14f, 8.01f, 7.45f, 7.99f)
                quadTo(7.76f, 7.97f, 8f, 8.17f)
                quadTo(8.03f, 8.2f, 8.06f, 8.24f)
                quadTo(8.73f, 9f, 9.75f, 9f)
                quadTo(10.77f, 9f, 11.44f, 8.24f)
                quadTo(11.64f, 8.01f, 11.95f, 7.99f)
                quadTo(12.26f, 7.97f, 12.5f, 8.17f)
                quadTo(12.53f, 8.2f, 12.56f, 8.24f)
                quadTo(13.23f, 9f, 14.25f, 9f)
                quadTo(15.27f, 9f, 15.94f, 8.24f)
                quadTo(16.14f, 8.01f, 16.45f, 7.99f)
                quadTo(16.76f, 7.97f, 17f, 8.17f)
                quadTo(17.03f, 8.2f, 17.06f, 8.24f)
                quadTo(18.27f, 9.6f, 19.84f, 8.72f)
                quadTo(19.88f, 8.69f, 19.92f, 8.67f)
                close()
                moveTo(6.75f, 18.75f)
                quadTo(5.25f, 18.75f, 5.25f, 17.25f)
                lineTo(5.25f, 13.5f)
                quadTo(5.25f, 12f, 6.75f, 12f)
                lineTo(10.5f, 12f)
                quadTo(12f, 12f, 12f, 13.5f)
                lineTo(12f, 17.25f)
                quadTo(12f, 18.75f, 10.5f, 18.75f)
                close()
                moveTo(14.25f, 20.25f)
                lineTo(17.25f, 20.25f)
                lineTo(17.25f, 13.5f)
                lineTo(14.25f, 13.5f)
                lineTo(14.25f, 20.25f)
                close()
                moveTo(6.75f, 17.25f)
                lineTo(10.5f, 17.25f)
                lineTo(10.5f, 13.5f)
                lineTo(6.75f, 13.5f)
                close()
            }
        }.build()
}
