// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val ChartBarSquare: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "ChartBarSquare",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(6f, 21f)
                quadTo(3f, 21f, 3f, 18f)
                lineTo(3f, 6f)
                quadTo(3f, 3f, 6f, 3f)
                lineTo(18f, 3f)
                quadTo(21f, 3f, 21f, 6f)
                lineTo(21f, 18f)
                quadTo(21f, 21f, 18f, 21f)
                close()
                moveTo(6f, 19.5f)
                lineTo(18f, 19.5f)
                quadTo(19.5f, 19.5f, 19.5f, 18f)
                lineTo(19.5f, 6f)
                quadTo(19.5f, 4.5f, 18f, 4.5f)
                lineTo(6f, 4.5f)
                quadTo(4.5f, 4.5f, 4.5f, 6f)
                lineTo(4.5f, 18f)
                quadTo(4.5f, 19.5f, 6f, 19.5f)
                close()
                moveTo(17.25f, 7.5f)
                lineTo(17.25f, 16.5f)
                quadTo(17.25f, 16.81f, 17.03f, 17.03f)
                quadTo(16.81f, 17.25f, 16.5f, 17.25f)
                quadTo(16.19f, 17.25f, 15.97f, 17.03f)
                quadTo(15.75f, 16.81f, 15.75f, 16.5f)
                lineTo(15.75f, 7.5f)
                quadTo(15.75f, 7.19f, 15.97f, 6.97f)
                quadTo(16.19f, 6.75f, 16.5f, 6.75f)
                quadTo(16.81f, 6.75f, 17.03f, 6.97f)
                quadTo(17.25f, 7.19f, 17.25f, 7.5f)
                close()
                moveTo(14.25f, 9.75f)
                lineTo(14.25f, 16.5f)
                quadTo(14.25f, 16.81f, 14.03f, 17.03f)
                quadTo(13.81f, 17.25f, 13.5f, 17.25f)
                quadTo(13.19f, 17.25f, 12.97f, 17.03f)
                quadTo(12.75f, 16.81f, 12.75f, 16.5f)
                lineTo(12.75f, 9.75f)
                quadTo(12.75f, 9.44f, 12.97f, 9.22f)
                quadTo(13.19f, 9f, 13.5f, 9f)
                quadTo(13.81f, 9f, 14.03f, 9.22f)
                quadTo(14.25f, 9.44f, 14.25f, 9.75f)
                close()
                moveTo(11.25f, 12f)
                lineTo(11.25f, 16.5f)
                quadTo(11.25f, 16.81f, 11.03f, 17.03f)
                quadTo(10.81f, 17.25f, 10.5f, 17.25f)
                quadTo(10.19f, 17.25f, 9.97f, 17.03f)
                quadTo(9.75f, 16.81f, 9.75f, 16.5f)
                lineTo(9.75f, 12f)
                quadTo(9.75f, 11.69f, 9.97f, 11.47f)
                quadTo(10.19f, 11.25f, 10.5f, 11.25f)
                quadTo(10.81f, 11.25f, 11.03f, 11.47f)
                quadTo(11.25f, 11.69f, 11.25f, 12f)
                close()
                moveTo(8.25f, 14.25f)
                lineTo(8.25f, 16.5f)
                quadTo(8.25f, 16.81f, 8.03f, 17.03f)
                quadTo(7.81f, 17.25f, 7.5f, 17.25f)
                quadTo(7.19f, 17.25f, 6.97f, 17.03f)
                quadTo(6.75f, 16.81f, 6.75f, 16.5f)
                lineTo(6.75f, 14.25f)
                quadTo(6.75f, 13.94f, 6.97f, 13.72f)
                quadTo(7.19f, 13.5f, 7.5f, 13.5f)
                quadTo(7.81f, 13.5f, 8.03f, 13.72f)
                quadTo(8.25f, 13.94f, 8.25f, 14.25f)
                close()
            }
        }.build()
}
