// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val ChatBubbleBottomCenterText: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "ChatBubbleBottomCenterText",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(1.5f, 12.76f)
                lineTo(1.5f, 6.74f)
                quadTo(1.5f, 3.26f, 4.85f, 2.77f)
                quadTo(8.39f, 2.25f, 12f, 2.25f)
                quadTo(15.6f, 2.25f, 19.15f, 2.77f)
                quadTo(22.5f, 3.26f, 22.5f, 6.74f)
                lineTo(22.5f, 12.76f)
                quadTo(22.5f, 16.24f, 19.15f, 16.73f)
                quadTo(17.42f, 16.98f, 15.67f, 17.11f)
                quadTo(15.48f, 17.13f, 15.38f, 17.28f)
                lineTo(12.62f, 21.42f)
                quadTo(12.54f, 21.54f, 12.42f, 21.62f)
                quadTo(12.16f, 21.8f, 11.85f, 21.73f)
                quadTo(11.55f, 21.67f, 11.38f, 21.42f)
                lineTo(8.62f, 17.29f)
                quadTo(8.52f, 17.13f, 8.32f, 17.11f)
                quadTo(6.58f, 16.98f, 4.85f, 16.73f)
                quadTo(1.5f, 16.24f, 1.5f, 12.76f)
                close()
                moveTo(3f, 12.76f)
                quadTo(3f, 14.94f, 5.07f, 15.24f)
                quadTo(6.75f, 15.49f, 8.44f, 15.62f)
                quadTo(9.36f, 15.69f, 9.87f, 16.45f)
                lineTo(12f, 19.65f)
                lineTo(14.13f, 16.45f)
                quadTo(14.65f, 15.68f, 15.57f, 15.62f)
                quadTo(17.26f, 15.49f, 18.93f, 15.24f)
                quadTo(21f, 14.94f, 21f, 12.76f)
                lineTo(21f, 6.74f)
                quadTo(21f, 4.56f, 18.93f, 4.25f)
                quadTo(15.49f, 3.75f, 12f, 3.75f)
                quadTo(8.5f, 3.75f, 5.07f, 4.25f)
                quadTo(3f, 4.56f, 3f, 6.74f)
                lineTo(3f, 12.76f)
                close()
                moveTo(7.5f, 7.5f)
                lineTo(16.5f, 7.5f)
                quadTo(16.81f, 7.5f, 17.03f, 7.72f)
                quadTo(17.25f, 7.94f, 17.25f, 8.25f)
                quadTo(17.25f, 8.56f, 17.03f, 8.78f)
                quadTo(16.81f, 9f, 16.5f, 9f)
                lineTo(7.5f, 9f)
                quadTo(7.19f, 9f, 6.97f, 8.78f)
                quadTo(6.75f, 8.56f, 6.75f, 8.25f)
                quadTo(6.75f, 7.94f, 6.97f, 7.72f)
                quadTo(7.19f, 7.5f, 7.5f, 7.5f)
                close()
                moveTo(7.5f, 10.5f)
                lineTo(12f, 10.5f)
                quadTo(12.31f, 10.5f, 12.53f, 10.72f)
                quadTo(12.75f, 10.94f, 12.75f, 11.25f)
                quadTo(12.75f, 11.56f, 12.53f, 11.78f)
                quadTo(12.31f, 12f, 12f, 12f)
                lineTo(7.5f, 12f)
                quadTo(7.19f, 12f, 6.97f, 11.78f)
                quadTo(6.75f, 11.56f, 6.75f, 11.25f)
                quadTo(6.75f, 10.94f, 6.97f, 10.72f)
                quadTo(7.19f, 10.5f, 7.5f, 10.5f)
                close()
            }
        }.build()
}
