// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val ChatBubbleLeftRight: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "ChatBubbleLeftRight",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(11.09f, 17.73f)
                lineTo(7.28f, 21.53f)
                quadTo(7.06f, 21.75f, 6.75f, 21.75f)
                quadTo(6.44f, 21.75f, 6.22f, 21.53f)
                quadTo(6f, 21.31f, 6f, 21f)
                lineTo(6f, 16.97f)
                quadTo(5.46f, 16.91f, 4.91f, 16.84f)
                quadTo(1.5f, 16.4f, 1.5f, 12.86f)
                lineTo(1.5f, 6.64f)
                quadTo(1.5f, 3.1f, 4.91f, 2.66f)
                quadTo(8.06f, 2.25f, 11.25f, 2.25f)
                quadTo(14.43f, 2.25f, 17.59f, 2.66f)
                quadTo(21f, 3.1f, 21f, 6.64f)
                lineTo(21f, 8.01f)
                quadTo(22.5f, 8.74f, 22.5f, 10.61f)
                lineTo(22.5f, 14.89f)
                quadTo(22.5f, 17.61f, 19.83f, 17.83f)
                quadTo(19.66f, 17.85f, 19.5f, 17.86f)
                lineTo(19.5f, 20.25f)
                quadTo(19.5f, 20.56f, 19.28f, 20.78f)
                quadTo(19.06f, 21f, 18.75f, 21f)
                quadTo(18.44f, 21f, 18.22f, 20.78f)
                lineTo(15.44f, 18f)
                quadTo(13.55f, 17.99f, 11.67f, 17.84f)
                quadTo(11.37f, 17.81f, 11.09f, 17.73f)
                close()
                moveTo(9.76f, 16.93f)
                quadTo(9f, 16.14f, 9f, 14.89f)
                lineTo(9f, 10.61f)
                quadTo(9f, 7.89f, 11.66f, 7.67f)
                quadTo(15.58f, 7.34f, 19.5f, 7.64f)
                lineTo(19.5f, 6.64f)
                quadTo(19.5f, 4.42f, 17.39f, 4.15f)
                quadTo(14.34f, 3.75f, 11.25f, 3.75f)
                quadTo(8.16f, 3.75f, 5.11f, 4.15f)
                quadTo(3f, 4.42f, 3f, 6.64f)
                lineTo(3f, 12.86f)
                quadTo(3f, 15.08f, 5.11f, 15.35f)
                quadTo(5.97f, 15.47f, 6.82f, 15.54f)
                quadTo(7.11f, 15.57f, 7.3f, 15.79f)
                quadTo(7.5f, 16f, 7.5f, 16.29f)
                lineTo(7.5f, 19.19f)
                lineTo(9.76f, 16.93f)
                close()
                moveTo(19.97f, 9.21f)
                quadTo(19.85f, 9.18f, 19.71f, 9.16f)
                quadTo(15.75f, 8.84f, 11.79f, 9.16f)
                quadTo(10.5f, 9.27f, 10.5f, 10.61f)
                lineTo(10.5f, 14.89f)
                quadTo(10.5f, 15.75f, 11.21f, 16.16f)
                quadTo(11.26f, 16.18f, 11.29f, 16.2f)
                quadTo(11.53f, 16.32f, 11.79f, 16.34f)
                quadTo(13.76f, 16.5f, 15.75f, 16.5f)
                quadTo(16.06f, 16.5f, 16.28f, 16.72f)
                lineTo(18f, 18.44f)
                lineTo(18f, 17.16f)
                quadTo(18f, 16.86f, 18.2f, 16.64f)
                quadTo(18.41f, 16.43f, 18.71f, 16.41f)
                quadTo(19.14f, 16.39f, 19.71f, 16.34f)
                quadTo(21f, 16.23f, 21f, 14.89f)
                lineTo(21f, 10.61f)
                quadTo(21f, 9.56f, 20.06f, 9.24f)
                quadTo(20.02f, 9.23f, 19.97f, 9.21f)
                close()
            }
        }.build()
}
