// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val CheckBadge: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "CheckBadge",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(21.75f, 12f)
                lineTo(21.75f, 12f)
                quadTo(21.75f, 14.1f, 20.21f, 15.4f)
                quadTo(20.38f, 17.41f, 18.89f, 18.89f)
                quadTo(17.41f, 20.38f, 15.4f, 20.21f)
                quadTo(14.1f, 21.75f, 12f, 21.75f)
                quadTo(9.9f, 21.75f, 8.6f, 20.21f)
                quadTo(6.59f, 20.38f, 5.11f, 18.89f)
                quadTo(3.62f, 17.41f, 3.79f, 15.4f)
                quadTo(2.25f, 14.1f, 2.25f, 12f)
                quadTo(2.25f, 9.9f, 3.79f, 8.6f)
                quadTo(3.62f, 6.59f, 5.11f, 5.11f)
                quadTo(6.59f, 3.62f, 8.6f, 3.79f)
                quadTo(9.9f, 2.25f, 12f, 2.25f)
                quadTo(14.1f, 2.25f, 15.4f, 3.79f)
                quadTo(17.41f, 3.62f, 18.89f, 5.11f)
                quadTo(20.38f, 6.59f, 20.21f, 8.6f)
                quadTo(21.75f, 9.9f, 21.75f, 12f)
                close()
                moveTo(20.25f, 12f)
                quadTo(20.25f, 10.44f, 18.98f, 9.55f)
                quadTo(18.59f, 9.27f, 18.67f, 8.8f)
                quadTo(18.94f, 7.27f, 17.83f, 6.17f)
                quadTo(16.73f, 5.06f, 15.2f, 5.33f)
                quadTo(14.73f, 5.41f, 14.46f, 5.03f)
                quadTo(13.56f, 3.75f, 12f, 3.75f)
                quadTo(10.44f, 3.75f, 9.55f, 5.02f)
                quadTo(9.27f, 5.41f, 8.8f, 5.33f)
                quadTo(7.27f, 5.06f, 6.17f, 6.17f)
                quadTo(5.06f, 7.27f, 5.33f, 8.8f)
                quadTo(5.41f, 9.27f, 5.03f, 9.54f)
                quadTo(3.75f, 10.44f, 3.75f, 12f)
                quadTo(3.75f, 13.56f, 5.02f, 14.45f)
                quadTo(5.41f, 14.73f, 5.33f, 15.2f)
                quadTo(5.06f, 16.73f, 6.17f, 17.83f)
                quadTo(7.27f, 18.94f, 8.8f, 18.67f)
                quadTo(9.27f, 18.59f, 9.54f, 18.98f)
                quadTo(10.44f, 20.25f, 12f, 20.25f)
                quadTo(13.56f, 20.25f, 14.45f, 18.98f)
                quadTo(14.73f, 18.59f, 15.2f, 18.67f)
                quadTo(16.73f, 18.94f, 17.83f, 17.83f)
                quadTo(18.94f, 16.73f, 18.67f, 15.2f)
                quadTo(18.59f, 14.73f, 18.98f, 14.46f)
                quadTo(20.25f, 13.56f, 20.25f, 12f)
                close()
                moveTo(9.53f, 12.22f)
                lineTo(11.15f, 13.84f)
                lineTo(14.39f, 9.31f)
                quadTo(14.57f, 9.06f, 14.88f, 9.01f)
                quadTo(15.18f, 8.96f, 15.44f, 9.14f)
                quadTo(15.69f, 9.32f, 15.74f, 9.63f)
                quadTo(15.79f, 9.93f, 15.61f, 10.19f)
                lineTo(11.86f, 15.44f)
                quadTo(11.82f, 15.49f, 11.78f, 15.53f)
                quadTo(11.56f, 15.75f, 11.25f, 15.75f)
                quadTo(10.94f, 15.75f, 10.72f, 15.53f)
                lineTo(8.47f, 13.28f)
                quadTo(8.25f, 13.06f, 8.25f, 12.75f)
                quadTo(8.25f, 12.44f, 8.47f, 12.22f)
                quadTo(8.69f, 12f, 9f, 12f)
                quadTo(9.31f, 12f, 9.53f, 12.22f)
                close()
            }
        }.build()
}
