// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val ClipboardDocumentCheck: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "ClipboardDocumentCheck",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(17.68f, 3.12f)
                quadTo(18f, 3.14f, 18.33f, 3.17f)
                quadTo(21f, 3.39f, 21f, 6.11f)
                lineTo(21f, 16.5f)
                quadTo(21f, 19.5f, 18f, 19.5f)
                lineTo(16.5f, 19.5f)
                lineTo(16.5f, 20.62f)
                quadTo(16.5f, 22.5f, 14.62f, 22.5f)
                lineTo(4.88f, 22.5f)
                quadTo(3f, 22.5f, 3f, 20.62f)
                lineTo(3f, 9.38f)
                quadTo(3f, 7.5f, 4.88f, 7.5f)
                lineTo(7.5f, 7.5f)
                lineTo(7.5f, 6.11f)
                quadTo(7.5f, 3.39f, 10.17f, 3.17f)
                quadTo(10.5f, 3.14f, 10.82f, 3.12f)
                quadTo(11.56f, 1.5f, 13.5f, 1.5f)
                lineTo(15f, 1.5f)
                quadTo(16.94f, 1.5f, 17.68f, 3.12f)
                close()
                moveTo(8.25f, 9f)
                lineTo(4.88f, 9f)
                quadTo(4.5f, 9f, 4.5f, 9.38f)
                lineTo(4.5f, 20.62f)
                quadTo(4.5f, 21f, 4.88f, 21f)
                lineTo(14.62f, 21f)
                quadTo(15f, 21f, 15f, 20.62f)
                lineTo(15f, 9.38f)
                quadTo(15f, 9f, 14.62f, 9f)
                lineTo(8.25f, 9f)
                close()
                moveTo(10.5f, 4.65f)
                quadTo(10.4f, 4.66f, 10.29f, 4.66f)
                quadTo(9f, 4.77f, 9f, 6.11f)
                lineTo(9f, 7.5f)
                lineTo(14.62f, 7.5f)
                quadTo(16.5f, 7.5f, 16.5f, 9.38f)
                lineTo(16.5f, 18f)
                lineTo(18f, 18f)
                quadTo(19.5f, 18f, 19.5f, 16.5f)
                lineTo(19.5f, 6.11f)
                quadTo(19.5f, 4.77f, 18.21f, 4.66f)
                quadTo(18.1f, 4.66f, 18f, 4.65f)
                quadTo(17.93f, 6f, 16.5f, 6f)
                lineTo(12f, 6f)
                quadTo(10.57f, 6f, 10.5f, 4.65f)
                close()
                moveTo(8.03f, 15.22f)
                lineTo(8.94f, 16.13f)
                lineTo(11.41f, 13.03f)
                quadTo(11.61f, 12.79f, 11.92f, 12.76f)
                quadTo(12.23f, 12.72f, 12.47f, 12.91f)
                quadTo(12.71f, 13.11f, 12.74f, 13.42f)
                quadTo(12.78f, 13.73f, 12.59f, 13.97f)
                lineTo(9.59f, 17.72f)
                quadTo(9.56f, 17.75f, 9.53f, 17.78f)
                quadTo(9.31f, 18f, 9f, 18f)
                quadTo(8.69f, 18f, 8.47f, 17.78f)
                lineTo(6.97f, 16.28f)
                quadTo(6.75f, 16.06f, 6.75f, 15.75f)
                quadTo(6.75f, 15.44f, 6.97f, 15.22f)
                quadTo(7.19f, 15f, 7.5f, 15f)
                quadTo(7.81f, 15f, 8.03f, 15.22f)
                close()
                moveTo(12.05f, 4.1f)
                quadTo(12f, 4.3f, 12f, 4.5f)
                lineTo(16.5f, 4.5f)
                quadTo(16.5f, 4.3f, 16.45f, 4.1f)
                quadTo(16.43f, 4.06f, 16.42f, 4.01f)
                quadTo(16.08f, 3f, 15f, 3f)
                lineTo(13.5f, 3f)
                quadTo(12.42f, 3f, 12.08f, 4.01f)
                quadTo(12.07f, 4.06f, 12.05f, 4.1f)
                close()
            }
        }.build()
}
