// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val CloudArrowDown: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "CloudArrowDown",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(6.75f, 20.25f)
                lineTo(6.75f, 20.25f)
                quadTo(2.27f, 20.25f, 1.56f, 15.83f)
                quadTo(0.9f, 11.73f, 4.51f, 10.23f)
                quadTo(4.32f, 8.21f, 5.46f, 6.45f)
                quadTo(6.79f, 4.41f, 9.16f, 3.87f)
                quadTo(11.53f, 3.33f, 13.61f, 4.59f)
                quadTo(15.37f, 5.66f, 16.07f, 7.51f)
                quadTo(17.83f, 7.24f, 19.18f, 8.63f)
                quadTo(20.56f, 10.03f, 20.22f, 11.82f)
                quadTo(23.03f, 13.23f, 22.42f, 16.56f)
                quadTo(21.75f, 20.24f, 18f, 20.25f)
                close()
                moveTo(6.75f, 18.75f)
                lineTo(18f, 18.75f)
                quadTo(20.5f, 18.75f, 20.95f, 16.29f)
                quadTo(21.39f, 13.83f, 19.06f, 12.94f)
                quadTo(18.78f, 12.84f, 18.65f, 12.56f)
                quadTo(18.52f, 12.28f, 18.62f, 11.99f)
                quadTo(19.09f, 10.68f, 18.11f, 9.68f)
                quadTo(17.13f, 8.68f, 15.8f, 9.11f)
                quadTo(15.78f, 9.12f, 15.76f, 9.12f)
                quadTo(15.46f, 9.2f, 15.19f, 9.04f)
                quadTo(14.93f, 8.88f, 14.85f, 8.58f)
                quadTo(13.75f, 4.36f, 9.49f, 5.33f)
                quadTo(5.24f, 6.3f, 6.08f, 10.58f)
                quadTo(6.13f, 10.86f, 5.99f, 11.1f)
                quadTo(5.84f, 11.35f, 5.57f, 11.44f)
                quadTo(2.54f, 12.44f, 3.04f, 15.6f)
                quadTo(3.55f, 18.75f, 6.75f, 18.75f)
                close()
                moveTo(12.75f, 9.75f)
                lineTo(12.75f, 14.69f)
                lineTo(14.47f, 12.97f)
                quadTo(14.69f, 12.75f, 15f, 12.75f)
                quadTo(15.31f, 12.75f, 15.53f, 12.97f)
                quadTo(15.75f, 13.19f, 15.75f, 13.5f)
                quadTo(15.75f, 13.81f, 15.53f, 14.03f)
                lineTo(12.53f, 17.03f)
                quadTo(12.31f, 17.25f, 12f, 17.25f)
                quadTo(11.69f, 17.25f, 11.47f, 17.03f)
                lineTo(11.47f, 17.03f)
                lineTo(8.47f, 14.03f)
                quadTo(8.25f, 13.81f, 8.25f, 13.5f)
                quadTo(8.25f, 13.19f, 8.47f, 12.97f)
                quadTo(8.69f, 12.75f, 9f, 12.75f)
                quadTo(9.31f, 12.75f, 9.53f, 12.97f)
                lineTo(11.25f, 14.69f)
                lineTo(11.25f, 9.75f)
                quadTo(11.25f, 9.44f, 11.47f, 9.22f)
                quadTo(11.69f, 9f, 12f, 9f)
                quadTo(12.31f, 9f, 12.53f, 9.22f)
                quadTo(12.75f, 9.44f, 12.75f, 9.75f)
                close()
            }
        }.build()
}
