// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Cube: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "Cube",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(11.57f, 22.37f)
                lineTo(2.62f, 17.15f)
                quadTo(2.25f, 16.93f, 2.25f, 16.5f)
                lineTo(2.25f, 7.56f)
                quadTo(2.25f, 7.53f, 2.25f, 7.5f)
                quadTo(2.25f, 7.4f, 2.27f, 7.3f)
                quadTo(2.3f, 7.21f, 2.35f, 7.13f)
                quadTo(2.4f, 7.04f, 2.47f, 6.97f)
                quadTo(2.54f, 6.9f, 2.63f, 6.85f)
                quadTo(2.65f, 6.83f, 2.67f, 6.82f)
                lineTo(11.62f, 1.6f)
                quadTo(12f, 1.38f, 12.38f, 1.6f)
                lineTo(21.33f, 6.82f)
                quadTo(21.35f, 6.83f, 21.37f, 6.85f)
                quadTo(21.46f, 6.9f, 21.53f, 6.97f)
                quadTo(21.6f, 7.04f, 21.65f, 7.12f)
                quadTo(21.7f, 7.21f, 21.73f, 7.3f)
                quadTo(21.75f, 7.4f, 21.75f, 7.5f)
                quadTo(21.75f, 7.53f, 21.75f, 7.56f)
                lineTo(21.75f, 16.5f)
                quadTo(21.75f, 16.93f, 21.38f, 17.15f)
                lineTo(12.43f, 22.37f)
                quadTo(12.4f, 22.39f, 12.37f, 22.4f)
                quadTo(12.29f, 22.45f, 12.2f, 22.48f)
                quadTo(12.1f, 22.5f, 12f, 22.5f)
                quadTo(11.9f, 22.5f, 11.8f, 22.48f)
                quadTo(11.71f, 22.45f, 11.63f, 22.4f)
                quadTo(11.6f, 22.39f, 11.57f, 22.37f)
                close()
                moveTo(19.51f, 7.5f)
                lineTo(12f, 3.12f)
                lineTo(4.49f, 7.5f)
                lineTo(12f, 11.88f)
                lineTo(19.51f, 7.5f)
                close()
                moveTo(11.25f, 13.18f)
                lineTo(3.75f, 8.81f)
                lineTo(3.75f, 16.07f)
                lineTo(11.25f, 20.44f)
                lineTo(11.25f, 13.18f)
                close()
                moveTo(12.75f, 20.44f)
                lineTo(20.25f, 16.07f)
                lineTo(20.25f, 8.81f)
                lineTo(12.75f, 13.18f)
                lineTo(12.75f, 20.44f)
                close()
            }
        }.build()
}
