// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val CurrencyDollar: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "CurrencyDollar",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(21.75f, 12f)
                quadTo(21.75f, 16.04f, 18.89f, 18.89f)
                quadTo(16.04f, 21.75f, 12f, 21.75f)
                quadTo(7.96f, 21.75f, 5.11f, 18.89f)
                quadTo(2.25f, 16.04f, 2.25f, 12f)
                quadTo(2.25f, 7.96f, 5.11f, 5.11f)
                quadTo(7.96f, 2.25f, 12f, 2.25f)
                quadTo(16.04f, 2.25f, 18.89f, 5.11f)
                quadTo(21.75f, 7.96f, 21.75f, 12f)
                close()
                moveTo(20.25f, 12f)
                quadTo(20.25f, 8.58f, 17.83f, 6.17f)
                quadTo(15.42f, 3.75f, 12f, 3.75f)
                quadTo(8.58f, 3.75f, 6.17f, 6.17f)
                quadTo(3.75f, 8.58f, 3.75f, 12f)
                quadTo(3.75f, 15.42f, 6.17f, 17.83f)
                quadTo(8.58f, 20.25f, 12f, 20.25f)
                quadTo(15.42f, 20.25f, 17.83f, 17.83f)
                quadTo(20.25f, 15.42f, 20.25f, 12f)
                close()
                moveTo(12.75f, 6f)
                lineTo(12.75f, 6.68f)
                quadTo(13.61f, 6.89f, 14.47f, 7.57f)
                lineTo(14.88f, 7.9f)
                quadTo(15.13f, 8.1f, 15.16f, 8.4f)
                quadTo(15.2f, 8.71f, 15.01f, 8.96f)
                quadTo(14.81f, 9.2f, 14.5f, 9.23f)
                quadTo(14.19f, 9.27f, 13.95f, 9.08f)
                lineTo(13.54f, 8.75f)
                quadTo(13.14f, 8.43f, 12.75f, 8.28f)
                lineTo(12.75f, 11.3f)
                quadTo(13.78f, 11.46f, 14.57f, 12.06f)
                quadTo(15.75f, 12.94f, 15.75f, 14.25f)
                quadTo(15.75f, 15.56f, 14.57f, 16.44f)
                quadTo(13.66f, 17.12f, 12.75f, 17.32f)
                lineTo(12.75f, 18f)
                quadTo(12.75f, 18.31f, 12.53f, 18.53f)
                quadTo(12.31f, 18.75f, 12f, 18.75f)
                quadTo(11.69f, 18.75f, 11.47f, 18.53f)
                quadTo(11.25f, 18.31f, 11.25f, 18f)
                lineTo(11.25f, 17.32f)
                quadTo(10.34f, 17.12f, 9.43f, 16.44f)
                lineTo(8.55f, 15.78f)
                quadTo(8.3f, 15.6f, 8.26f, 15.29f)
                quadTo(8.21f, 14.98f, 8.4f, 14.73f)
                quadTo(8.59f, 14.48f, 8.89f, 14.44f)
                quadTo(9.2f, 14.4f, 9.45f, 14.58f)
                lineTo(10.33f, 15.24f)
                quadTo(10.79f, 15.59f, 11.25f, 15.74f)
                lineTo(11.25f, 12.69f)
                quadTo(10.28f, 12.53f, 9.53f, 11.93f)
                quadTo(8.42f, 11.04f, 8.42f, 9.75f)
                quadTo(8.42f, 8.46f, 9.53f, 7.57f)
                quadTo(10.39f, 6.89f, 11.25f, 6.68f)
                lineTo(11.25f, 6f)
                quadTo(11.25f, 5.69f, 11.47f, 5.47f)
                quadTo(11.69f, 5.25f, 12f, 5.25f)
                quadTo(12.31f, 5.25f, 12.53f, 5.47f)
                quadTo(12.75f, 5.69f, 12.75f, 6f)
                close()
                moveTo(12.75f, 12.83f)
                lineTo(12.75f, 15.74f)
                quadTo(13.21f, 15.59f, 13.67f, 15.24f)
                quadTo(14.25f, 14.81f, 14.25f, 14.25f)
                quadTo(14.25f, 13.69f, 13.67f, 13.26f)
                quadTo(13.27f, 12.96f, 12.75f, 12.83f)
                close()
                moveTo(11.25f, 8.28f)
                quadTo(10.86f, 8.43f, 10.46f, 8.75f)
                quadTo(9.92f, 9.18f, 9.92f, 9.75f)
                quadTo(9.92f, 10.32f, 10.46f, 10.75f)
                quadTo(10.81f, 11.03f, 11.25f, 11.15f)
                lineTo(11.25f, 8.28f)
                close()
            }
        }.build()
}
