// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val CurrencyEuro: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "CurrencyEuro",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(21.75f, 12f)
                quadTo(21.75f, 16.04f, 18.89f, 18.89f)
                quadTo(16.04f, 21.75f, 12f, 21.75f)
                quadTo(7.96f, 21.75f, 5.11f, 18.89f)
                quadTo(2.25f, 16.04f, 2.25f, 12f)
                quadTo(2.25f, 7.96f, 5.11f, 5.11f)
                quadTo(7.96f, 2.25f, 12f, 2.25f)
                quadTo(16.04f, 2.25f, 18.89f, 5.11f)
                quadTo(21.75f, 7.96f, 21.75f, 12f)
                close()
                moveTo(20.25f, 12f)
                quadTo(20.25f, 8.58f, 17.83f, 6.17f)
                quadTo(15.42f, 3.75f, 12f, 3.75f)
                quadTo(8.58f, 3.75f, 6.17f, 6.17f)
                quadTo(3.75f, 8.58f, 3.75f, 12f)
                quadTo(3.75f, 15.42f, 6.17f, 17.83f)
                quadTo(8.58f, 20.25f, 12f, 20.25f)
                quadTo(15.42f, 20.25f, 17.83f, 17.83f)
                quadTo(20.25f, 15.42f, 20.25f, 12f)
                close()
                moveTo(14f, 8.46f)
                quadTo(11.4f, 7.55f, 9.75f, 9.75f)
                lineTo(12.75f, 9.75f)
                quadTo(13.06f, 9.75f, 13.28f, 9.97f)
                quadTo(13.5f, 10.19f, 13.5f, 10.5f)
                quadTo(13.5f, 10.81f, 13.28f, 11.03f)
                quadTo(13.06f, 11.25f, 12.75f, 11.25f)
                lineTo(9.01f, 11.25f)
                quadTo(8.82f, 12f, 9.01f, 12.75f)
                lineTo(12.75f, 12.75f)
                quadTo(13.06f, 12.75f, 13.28f, 12.97f)
                quadTo(13.5f, 13.19f, 13.5f, 13.5f)
                quadTo(13.5f, 13.81f, 13.28f, 14.03f)
                quadTo(13.06f, 14.25f, 12.75f, 14.25f)
                lineTo(9.75f, 14.25f)
                quadTo(11.4f, 16.45f, 14f, 15.54f)
                quadTo(14.29f, 15.43f, 14.57f, 15.57f)
                quadTo(14.85f, 15.7f, 14.96f, 15.99f)
                quadTo(15.06f, 16.29f, 14.93f, 16.57f)
                quadTo(14.79f, 16.85f, 14.5f, 16.95f)
                quadTo(10.84f, 18.24f, 8.53f, 15.12f)
                quadTo(8.21f, 14.69f, 7.98f, 14.25f)
                lineTo(7.5f, 14.25f)
                quadTo(7.19f, 14.25f, 6.97f, 14.03f)
                quadTo(6.75f, 13.81f, 6.75f, 13.5f)
                quadTo(6.75f, 13.19f, 6.97f, 12.97f)
                quadTo(7.17f, 12.77f, 7.45f, 12.75f)
                quadTo(7.31f, 12f, 7.45f, 11.25f)
                quadTo(7.17f, 11.23f, 6.97f, 11.03f)
                quadTo(6.75f, 10.81f, 6.75f, 10.5f)
                quadTo(6.75f, 10.19f, 6.97f, 9.97f)
                quadTo(7.19f, 9.75f, 7.5f, 9.75f)
                lineTo(7.98f, 9.75f)
                quadTo(8.21f, 9.31f, 8.53f, 8.88f)
                quadTo(10.84f, 5.76f, 14.5f, 7.05f)
                quadTo(14.79f, 7.15f, 14.93f, 7.43f)
                quadTo(15.06f, 7.71f, 14.96f, 8.01f)
                quadTo(14.85f, 8.3f, 14.57f, 8.43f)
                quadTo(14.29f, 8.57f, 14f, 8.46f)
                close()
            }
        }.build()
}
