// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val CurrencyRupee: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "CurrencyRupee",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(21.75f, 12f)
                quadTo(21.75f, 16.04f, 18.89f, 18.89f)
                quadTo(16.04f, 21.75f, 12f, 21.75f)
                quadTo(7.96f, 21.75f, 5.11f, 18.89f)
                quadTo(2.25f, 16.04f, 2.25f, 12f)
                quadTo(2.25f, 7.96f, 5.11f, 5.11f)
                quadTo(7.96f, 2.25f, 12f, 2.25f)
                quadTo(16.04f, 2.25f, 18.89f, 5.11f)
                quadTo(21.75f, 7.96f, 21.75f, 12f)
                close()
                moveTo(20.25f, 12f)
                quadTo(20.25f, 8.58f, 17.83f, 6.17f)
                quadTo(15.42f, 3.75f, 12f, 3.75f)
                quadTo(8.58f, 3.75f, 6.17f, 6.17f)
                quadTo(3.75f, 8.58f, 3.75f, 12f)
                quadTo(3.75f, 15.42f, 6.17f, 17.83f)
                quadTo(8.58f, 20.25f, 12f, 20.25f)
                quadTo(15.42f, 20.25f, 17.83f, 17.83f)
                quadTo(20.25f, 15.42f, 20.25f, 12f)
                close()
                moveTo(15f, 9f)
                lineTo(13.74f, 9f)
                quadTo(14.1f, 9.62f, 14.21f, 10.5f)
                lineTo(15f, 10.5f)
                quadTo(15.31f, 10.5f, 15.53f, 10.72f)
                quadTo(15.75f, 10.94f, 15.75f, 11.25f)
                quadTo(15.75f, 11.56f, 15.53f, 11.78f)
                quadTo(15.31f, 12f, 15f, 12f)
                lineTo(14.21f, 12f)
                quadTo(13.87f, 14.86f, 10.8f, 14.99f)
                lineTo(12.53f, 16.72f)
                quadTo(12.75f, 16.94f, 12.75f, 17.25f)
                quadTo(12.75f, 17.56f, 12.53f, 17.78f)
                quadTo(12.31f, 18f, 12f, 18f)
                quadTo(11.69f, 18f, 11.47f, 17.78f)
                lineTo(8.47f, 14.78f)
                quadTo(8.25f, 14.56f, 8.25f, 14.25f)
                quadTo(8.25f, 13.94f, 8.47f, 13.72f)
                quadTo(8.69f, 13.5f, 9f, 13.5f)
                lineTo(10.5f, 13.5f)
                quadTo(12.34f, 13.5f, 12.67f, 12f)
                lineTo(9f, 12f)
                quadTo(8.69f, 12f, 8.47f, 11.78f)
                quadTo(8.25f, 11.56f, 8.25f, 11.25f)
                quadTo(8.25f, 10.94f, 8.47f, 10.72f)
                quadTo(8.69f, 10.5f, 9f, 10.5f)
                lineTo(12.67f, 10.5f)
                quadTo(12.34f, 9f, 10.5f, 9f)
                lineTo(9f, 9f)
                quadTo(8.69f, 9f, 8.47f, 8.78f)
                quadTo(8.25f, 8.56f, 8.25f, 8.25f)
                quadTo(8.25f, 7.94f, 8.47f, 7.72f)
                quadTo(8.69f, 7.5f, 9f, 7.5f)
                lineTo(15f, 7.5f)
                quadTo(15.31f, 7.5f, 15.53f, 7.72f)
                quadTo(15.75f, 7.94f, 15.75f, 8.25f)
                quadTo(15.75f, 8.56f, 15.53f, 8.78f)
                quadTo(15.31f, 9f, 15f, 9f)
                close()
            }
        }.build()
}
