// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val DocumentCurrencyPound: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "DocumentCurrencyPound",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(10.5f, 1.5f)
                quadTo(14.54f, 1.5f, 17.39f, 4.36f)
                quadTo(20.25f, 7.21f, 20.25f, 11.25f)
                lineTo(20.25f, 20.62f)
                quadTo(20.25f, 22.5f, 18.38f, 22.5f)
                lineTo(5.62f, 22.5f)
                quadTo(3.75f, 22.5f, 3.75f, 20.62f)
                lineTo(3.75f, 3.38f)
                quadTo(3.75f, 1.5f, 5.62f, 1.5f)
                close()
                moveTo(10.12f, 3f)
                lineTo(8.25f, 3f)
                lineTo(5.62f, 3f)
                quadTo(5.25f, 3f, 5.25f, 3.38f)
                lineTo(5.25f, 20.62f)
                quadTo(5.25f, 21f, 5.62f, 21f)
                lineTo(18.38f, 21f)
                quadTo(18.75f, 21f, 18.75f, 20.62f)
                lineTo(18.75f, 11.62f)
                quadTo(18.75f, 9f, 16.12f, 9f)
                lineTo(14.62f, 9f)
                quadTo(12.75f, 9f, 12.75f, 7.12f)
                lineTo(12.75f, 5.62f)
                quadTo(12.75f, 4.54f, 11.98f, 3.77f)
                quadTo(11.21f, 3f, 10.12f, 3f)
                close()
                moveTo(14.34f, 12.66f)
                quadTo(13.12f, 11.44f, 11.62f, 12.3f)
                quadTo(10.13f, 13.16f, 10.57f, 14.83f)
                lineTo(10.62f, 15f)
                lineTo(12f, 15f)
                quadTo(12.31f, 15f, 12.53f, 15.22f)
                quadTo(12.75f, 15.44f, 12.75f, 15.75f)
                quadTo(12.75f, 16.06f, 12.53f, 16.28f)
                quadTo(12.31f, 16.5f, 12f, 16.5f)
                lineTo(10.91f, 16.5f)
                quadTo(10.95f, 17.01f, 10.87f, 17.52f)
                quadTo(11.73f, 17.37f, 12.61f, 17.66f)
                quadTo(13.44f, 17.94f, 14.23f, 17.55f)
                lineTo(14.66f, 17.33f)
                quadTo(14.94f, 17.19f, 15.24f, 17.29f)
                quadTo(15.53f, 17.39f, 15.67f, 17.66f)
                quadTo(15.81f, 17.94f, 15.71f, 18.24f)
                quadTo(15.61f, 18.53f, 15.34f, 18.67f)
                lineTo(14.9f, 18.89f)
                quadTo(13.56f, 19.56f, 12.14f, 19.09f)
                quadTo(11.31f, 18.81f, 10.53f, 19.2f)
                lineTo(10.09f, 19.42f)
                quadTo(9.8f, 19.56f, 9.5f, 19.46f)
                quadTo(9.21f, 19.35f, 9.07f, 19.07f)
                quadTo(8.94f, 18.79f, 9.04f, 18.5f)
                lineTo(9.2f, 18.06f)
                quadTo(9.48f, 17.29f, 9.41f, 16.5f)
                lineTo(8.25f, 16.5f)
                quadTo(7.94f, 16.5f, 7.72f, 16.28f)
                quadTo(7.5f, 16.06f, 7.5f, 15.75f)
                quadTo(7.5f, 15.44f, 7.72f, 15.22f)
                quadTo(7.94f, 15f, 8.25f, 15f)
                lineTo(9.07f, 15f)
                quadTo(8.48f, 12.38f, 10.87f, 11f)
                quadTo(13.37f, 9.56f, 15.4f, 11.6f)
                quadTo(15.62f, 11.82f, 15.62f, 12.13f)
                quadTo(15.62f, 12.44f, 15.4f, 12.66f)
                quadTo(15.18f, 12.88f, 14.87f, 12.88f)
                quadTo(14.56f, 12.88f, 14.34f, 12.66f)
                close()
                moveTo(18.11f, 8f)
                quadTo(17.51f, 6.59f, 16.33f, 5.42f)
                quadTo(15.16f, 4.24f, 13.75f, 3.64f)
                quadTo(14.25f, 4.53f, 14.25f, 5.62f)
                lineTo(14.25f, 7.12f)
                quadTo(14.25f, 7.5f, 14.62f, 7.5f)
                lineTo(16.12f, 7.5f)
                quadTo(17.22f, 7.5f, 18.11f, 8f)
                close()
            }
        }.build()
}
