// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val DocumentCurrencyBangladeshi: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "DocumentCurrencyBangladeshi",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(10.5f, 1.5f)
                quadTo(14.54f, 1.5f, 17.39f, 4.36f)
                quadTo(20.25f, 7.21f, 20.25f, 11.25f)
                lineTo(20.25f, 20.62f)
                quadTo(20.25f, 22.5f, 18.38f, 22.5f)
                lineTo(5.62f, 22.5f)
                quadTo(3.75f, 22.5f, 3.75f, 20.62f)
                lineTo(3.75f, 3.38f)
                quadTo(3.75f, 1.5f, 5.62f, 1.5f)
                close()
                moveTo(10.12f, 3f)
                lineTo(8.25f, 3f)
                lineTo(5.62f, 3f)
                quadTo(5.25f, 3f, 5.25f, 3.38f)
                lineTo(5.25f, 20.62f)
                quadTo(5.25f, 21f, 5.62f, 21f)
                lineTo(18.38f, 21f)
                quadTo(18.75f, 21f, 18.75f, 20.62f)
                lineTo(18.75f, 11.62f)
                quadTo(18.75f, 9f, 16.12f, 9f)
                lineTo(14.62f, 9f)
                quadTo(12.75f, 9f, 12.75f, 7.12f)
                lineTo(12.75f, 5.62f)
                quadTo(12.75f, 4.54f, 11.98f, 3.77f)
                quadTo(11.21f, 3f, 10.12f, 3f)
                close()
                moveTo(7.72f, 9.97f)
                lineTo(7.94f, 9.75f)
                quadTo(8.65f, 9.04f, 9.57f, 9.43f)
                quadTo(10.5f, 9.81f, 10.5f, 10.81f)
                lineTo(10.5f, 12.75f)
                lineTo(15.75f, 12.75f)
                quadTo(16.06f, 12.75f, 16.28f, 12.97f)
                quadTo(16.5f, 13.19f, 16.5f, 13.5f)
                quadTo(16.5f, 13.81f, 16.28f, 14.03f)
                quadTo(16.06f, 14.25f, 15.75f, 14.25f)
                lineTo(10.5f, 14.25f)
                lineTo(10.5f, 17.25f)
                quadTo(10.5f, 17.61f, 10.71f, 17.71f)
                quadTo(13.31f, 18.95f, 14.6f, 16.5f)
                lineTo(14.25f, 16.5f)
                quadTo(13.94f, 16.5f, 13.72f, 16.28f)
                quadTo(13.5f, 16.06f, 13.5f, 15.75f)
                quadTo(13.5f, 15.44f, 13.72f, 15.22f)
                quadTo(13.94f, 15f, 14.25f, 15f)
                lineTo(14.76f, 15f)
                quadTo(15.49f, 15f, 15.93f, 15.57f)
                quadTo(16.41f, 16.21f, 16.06f, 16.94f)
                quadTo(15.26f, 18.62f, 13.5f, 19.24f)
                quadTo(11.75f, 19.86f, 10.07f, 19.07f)
                quadTo(9f, 18.56f, 9f, 17.25f)
                lineTo(9f, 14.25f)
                lineTo(8.25f, 14.25f)
                quadTo(7.94f, 14.25f, 7.72f, 14.03f)
                quadTo(7.5f, 13.81f, 7.5f, 13.5f)
                quadTo(7.5f, 13.19f, 7.72f, 12.97f)
                quadTo(7.94f, 12.75f, 8.25f, 12.75f)
                lineTo(9f, 12.75f)
                lineTo(9f, 10.81f)
                lineTo(8.78f, 11.03f)
                quadTo(8.56f, 11.25f, 8.25f, 11.25f)
                quadTo(7.94f, 11.25f, 7.72f, 11.03f)
                quadTo(7.5f, 10.81f, 7.5f, 10.5f)
                quadTo(7.5f, 10.19f, 7.72f, 9.97f)
                close()
                moveTo(18.11f, 8f)
                quadTo(17.51f, 6.59f, 16.33f, 5.42f)
                quadTo(15.16f, 4.24f, 13.75f, 3.64f)
                quadTo(14.25f, 4.53f, 14.25f, 5.62f)
                lineTo(14.25f, 7.12f)
                quadTo(14.25f, 7.5f, 14.62f, 7.5f)
                lineTo(16.12f, 7.5f)
                quadTo(17.22f, 7.5f, 18.11f, 8f)
                close()
            }
        }.build()
}
