// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val DocumentMagnifyingGlass: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "DocumentMagnifyingGlass",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(10.5f, 1.5f)
                quadTo(14.54f, 1.5f, 17.39f, 4.36f)
                quadTo(20.25f, 7.21f, 20.25f, 11.25f)
                lineTo(20.25f, 19.88f)
                quadTo(20.25f, 21.75f, 18.38f, 21.75f)
                lineTo(5.62f, 21.75f)
                quadTo(3.75f, 21.75f, 3.75f, 19.88f)
                lineTo(3.75f, 3.38f)
                quadTo(3.75f, 1.5f, 5.62f, 1.5f)
                close()
                moveTo(10.12f, 3f)
                lineTo(8.25f, 3f)
                lineTo(5.62f, 3f)
                quadTo(5.25f, 3f, 5.25f, 3.38f)
                lineTo(5.25f, 19.88f)
                quadTo(5.25f, 20.25f, 5.62f, 20.25f)
                lineTo(18.38f, 20.25f)
                quadTo(18.75f, 20.25f, 18.75f, 19.88f)
                lineTo(18.75f, 11.62f)
                quadTo(18.75f, 9f, 16.12f, 9f)
                lineTo(14.62f, 9f)
                quadTo(12.75f, 9f, 12.75f, 7.12f)
                lineTo(12.75f, 5.62f)
                quadTo(12.75f, 4.54f, 11.98f, 3.77f)
                quadTo(11.21f, 3f, 10.12f, 3f)
                close()
                moveTo(15f, 13.88f)
                quadTo(15f, 15.03f, 14.6f, 15.79f)
                lineTo(15.53f, 16.72f)
                quadTo(15.75f, 16.94f, 15.75f, 17.25f)
                quadTo(15.75f, 17.56f, 15.53f, 17.78f)
                quadTo(15.31f, 18f, 15f, 18f)
                quadTo(14.69f, 18f, 14.47f, 17.78f)
                lineTo(13.54f, 16.85f)
                quadTo(12.78f, 17.25f, 11.62f, 17.25f)
                quadTo(8.25f, 17.25f, 8.25f, 13.88f)
                quadTo(8.25f, 10.5f, 11.62f, 10.5f)
                quadTo(15f, 10.5f, 15f, 13.88f)
                close()
                moveTo(13.5f, 13.88f)
                quadTo(13.5f, 12f, 11.62f, 12f)
                quadTo(9.75f, 12f, 9.75f, 13.88f)
                quadTo(9.75f, 15.75f, 11.62f, 15.75f)
                quadTo(12.33f, 15.75f, 12.77f, 15.48f)
                quadTo(12.82f, 15.33f, 12.95f, 15.2f)
                quadTo(13.08f, 15.07f, 13.23f, 15.02f)
                quadTo(13.5f, 14.58f, 13.5f, 13.88f)
                close()
                moveTo(18.11f, 8f)
                quadTo(17.51f, 6.59f, 16.33f, 5.42f)
                quadTo(15.16f, 4.24f, 13.75f, 3.64f)
                quadTo(14.25f, 4.53f, 14.25f, 5.62f)
                lineTo(14.25f, 7.12f)
                quadTo(14.25f, 7.5f, 14.62f, 7.5f)
                lineTo(16.12f, 7.5f)
                quadTo(17.22f, 7.5f, 18.11f, 8f)
                close()
            }
        }.build()
}
