// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val DocumentCurrencyDollar: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "DocumentCurrencyDollar",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(10.5f, 1.5f)
                quadTo(14.54f, 1.5f, 17.39f, 4.36f)
                quadTo(20.25f, 7.21f, 20.25f, 11.25f)
                lineTo(20.25f, 20.62f)
                quadTo(20.25f, 22.5f, 18.38f, 22.5f)
                lineTo(5.62f, 22.5f)
                quadTo(3.75f, 22.5f, 3.75f, 20.62f)
                lineTo(3.75f, 3.38f)
                quadTo(3.75f, 1.5f, 5.62f, 1.5f)
                close()
                moveTo(10.12f, 3f)
                lineTo(8.25f, 3f)
                lineTo(5.62f, 3f)
                quadTo(5.25f, 3f, 5.25f, 3.38f)
                lineTo(5.25f, 20.62f)
                quadTo(5.25f, 21f, 5.62f, 21f)
                lineTo(18.38f, 21f)
                quadTo(18.75f, 21f, 18.75f, 20.62f)
                lineTo(18.75f, 11.62f)
                quadTo(18.75f, 9f, 16.12f, 9f)
                lineTo(14.62f, 9f)
                quadTo(12.75f, 9f, 12.75f, 7.12f)
                lineTo(12.75f, 5.62f)
                quadTo(12.75f, 4.54f, 11.98f, 3.77f)
                quadTo(11.21f, 3f, 10.12f, 3f)
                close()
                moveTo(12.75f, 11.25f)
                lineTo(12.75f, 11.28f)
                quadTo(13.6f, 11.34f, 14.44f, 11.56f)
                quadTo(14.74f, 11.63f, 14.9f, 11.9f)
                quadTo(15.05f, 12.17f, 14.98f, 12.47f)
                quadTo(14.9f, 12.77f, 14.63f, 12.93f)
                quadTo(14.36f, 13.09f, 14.06f, 13.01f)
                quadTo(13.41f, 12.84f, 12.75f, 12.78f)
                lineTo(12.75f, 14.46f)
                lineTo(13.72f, 14.8f)
                quadTo(15f, 15.23f, 15f, 16.5f)
                quadTo(15f, 16.74f, 14.98f, 16.97f)
                quadTo(14.85f, 18.46f, 13.31f, 18.66f)
                quadTo(13.03f, 18.7f, 12.75f, 18.72f)
                lineTo(12.75f, 18.75f)
                quadTo(12.75f, 19.06f, 12.53f, 19.28f)
                quadTo(12.31f, 19.5f, 12f, 19.5f)
                quadTo(11.69f, 19.5f, 11.47f, 19.28f)
                quadTo(11.25f, 19.06f, 11.25f, 18.75f)
                lineTo(11.25f, 18.72f)
                quadTo(10.4f, 18.66f, 9.56f, 18.44f)
                quadTo(9.26f, 18.36f, 9.11f, 18.1f)
                quadTo(8.95f, 17.83f, 9.02f, 17.53f)
                quadTo(9.1f, 17.23f, 9.37f, 17.07f)
                quadTo(9.63f, 16.91f, 9.94f, 16.99f)
                quadTo(10.59f, 17.16f, 11.25f, 17.22f)
                lineTo(11.25f, 15.54f)
                lineTo(10.28f, 15.2f)
                quadTo(9f, 14.77f, 9f, 13.5f)
                quadTo(9f, 13.27f, 9.02f, 13.03f)
                quadTo(9.15f, 11.54f, 10.69f, 11.34f)
                quadTo(10.97f, 11.3f, 11.25f, 11.28f)
                lineTo(11.25f, 11.25f)
                quadTo(11.25f, 10.94f, 11.47f, 10.72f)
                quadTo(11.69f, 10.5f, 12f, 10.5f)
                quadTo(12.31f, 10.5f, 12.53f, 10.72f)
                quadTo(12.75f, 10.94f, 12.75f, 11.25f)
                close()
                moveTo(18.11f, 8f)
                quadTo(17.51f, 6.59f, 16.33f, 5.42f)
                quadTo(15.16f, 4.24f, 13.75f, 3.64f)
                quadTo(14.25f, 4.53f, 14.25f, 5.62f)
                lineTo(14.25f, 7.12f)
                quadTo(14.25f, 7.5f, 14.62f, 7.5f)
                lineTo(16.12f, 7.5f)
                quadTo(17.22f, 7.5f, 18.11f, 8f)
                close()
                moveTo(11.25f, 12.78f)
                quadTo(11.07f, 12.8f, 10.89f, 12.82f)
                quadTo(10.54f, 12.87f, 10.52f, 13.16f)
                quadTo(10.5f, 13.33f, 10.5f, 13.5f)
                quadTo(10.5f, 13.69f, 10.77f, 13.78f)
                lineTo(11.25f, 13.95f)
                lineTo(11.25f, 12.78f)
                close()
                moveTo(12.75f, 16.05f)
                lineTo(12.75f, 17.22f)
                quadTo(12.93f, 17.2f, 13.11f, 17.18f)
                quadTo(13.46f, 17.13f, 13.48f, 16.83f)
                quadTo(13.5f, 16.67f, 13.5f, 16.5f)
                quadTo(13.5f, 16.31f, 13.23f, 16.21f)
                lineTo(12.75f, 16.05f)
                close()
            }
        }.build()
}
