// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val DocumentCurrencyEuro: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "DocumentCurrencyEuro",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(10.5f, 1.5f)
                quadTo(14.54f, 1.5f, 17.39f, 4.36f)
                quadTo(20.25f, 7.21f, 20.25f, 11.25f)
                lineTo(20.25f, 20.62f)
                quadTo(20.25f, 22.5f, 18.38f, 22.5f)
                lineTo(5.62f, 22.5f)
                quadTo(3.75f, 22.5f, 3.75f, 20.62f)
                lineTo(3.75f, 3.38f)
                quadTo(3.75f, 1.5f, 5.62f, 1.5f)
                close()
                moveTo(10.12f, 3f)
                lineTo(8.25f, 3f)
                lineTo(5.62f, 3f)
                quadTo(5.25f, 3f, 5.25f, 3.38f)
                lineTo(5.25f, 20.62f)
                quadTo(5.25f, 21f, 5.62f, 21f)
                lineTo(18.38f, 21f)
                quadTo(18.75f, 21f, 18.75f, 20.62f)
                lineTo(18.75f, 11.62f)
                quadTo(18.75f, 9f, 16.12f, 9f)
                lineTo(14.62f, 9f)
                quadTo(12.75f, 9f, 12.75f, 7.12f)
                lineTo(12.75f, 5.62f)
                quadTo(12.75f, 4.54f, 11.98f, 3.77f)
                quadTo(11.21f, 3f, 10.12f, 3f)
                close()
                moveTo(8.25f, 13.12f)
                lineTo(9.24f, 13.12f)
                quadTo(9.54f, 12.5f, 10.04f, 11.88f)
                quadTo(11.15f, 10.5f, 12.75f, 10.5f)
                quadTo(14.35f, 10.5f, 15.46f, 11.88f)
                quadTo(15.65f, 12.12f, 15.62f, 12.43f)
                quadTo(15.58f, 12.74f, 15.34f, 12.93f)
                quadTo(15.1f, 13.13f, 14.79f, 13.09f)
                quadTo(14.48f, 13.06f, 14.29f, 12.82f)
                quadTo(13.63f, 12f, 12.75f, 12f)
                quadTo(11.87f, 12f, 11.21f, 12.82f)
                quadTo(11.09f, 12.97f, 10.98f, 13.12f)
                lineTo(12.75f, 13.12f)
                quadTo(13.06f, 13.12f, 13.28f, 13.35f)
                quadTo(13.5f, 13.56f, 13.5f, 13.88f)
                quadTo(13.5f, 14.19f, 13.28f, 14.4f)
                quadTo(13.06f, 14.62f, 12.75f, 14.62f)
                lineTo(10.37f, 14.62f)
                quadTo(10.31f, 15f, 10.37f, 15.38f)
                lineTo(12.75f, 15.38f)
                quadTo(13.06f, 15.38f, 13.28f, 15.6f)
                quadTo(13.5f, 15.81f, 13.5f, 16.12f)
                quadTo(13.5f, 16.44f, 13.28f, 16.66f)
                quadTo(13.06f, 16.88f, 12.75f, 16.88f)
                lineTo(10.98f, 16.88f)
                quadTo(11.09f, 17.03f, 11.21f, 17.18f)
                quadTo(11.87f, 18f, 12.75f, 18f)
                quadTo(13.63f, 18f, 14.29f, 17.18f)
                quadTo(14.48f, 16.94f, 14.79f, 16.91f)
                quadTo(15.1f, 16.87f, 15.34f, 17.07f)
                quadTo(15.58f, 17.26f, 15.62f, 17.57f)
                quadTo(15.65f, 17.88f, 15.46f, 18.12f)
                quadTo(14.35f, 19.5f, 12.75f, 19.5f)
                quadTo(11.15f, 19.5f, 10.04f, 18.12f)
                quadTo(9.54f, 17.5f, 9.25f, 16.88f)
                lineTo(8.25f, 16.88f)
                quadTo(7.94f, 16.88f, 7.72f, 16.66f)
                quadTo(7.5f, 16.44f, 7.5f, 16.12f)
                quadTo(7.5f, 15.81f, 7.72f, 15.6f)
                quadTo(7.94f, 15.38f, 8.25f, 15.38f)
                lineTo(8.81f, 15.38f)
                quadTo(8.78f, 15f, 8.81f, 14.62f)
                lineTo(8.25f, 14.62f)
                quadTo(7.94f, 14.62f, 7.72f, 14.4f)
                quadTo(7.5f, 14.19f, 7.5f, 13.88f)
                quadTo(7.5f, 13.56f, 7.72f, 13.35f)
                quadTo(7.94f, 13.12f, 8.25f, 13.12f)
                close()
                moveTo(18.11f, 8f)
                quadTo(17.51f, 6.59f, 16.33f, 5.42f)
                quadTo(15.16f, 4.24f, 13.75f, 3.64f)
                quadTo(14.25f, 4.53f, 14.25f, 5.62f)
                lineTo(14.25f, 7.12f)
                quadTo(14.25f, 7.5f, 14.62f, 7.5f)
                lineTo(16.12f, 7.5f)
                quadTo(17.22f, 7.5f, 18.11f, 8f)
                close()
            }
        }.build()
}
