// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val DocumentPlus: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "DocumentPlus",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(10.5f, 1.5f)
                quadTo(14.54f, 1.5f, 17.39f, 4.36f)
                quadTo(20.25f, 7.21f, 20.25f, 11.25f)
                lineTo(20.25f, 20.62f)
                quadTo(20.25f, 22.5f, 18.38f, 22.5f)
                lineTo(5.62f, 22.5f)
                quadTo(3.75f, 22.5f, 3.75f, 20.62f)
                lineTo(3.75f, 3.38f)
                quadTo(3.75f, 1.5f, 5.62f, 1.5f)
                close()
                moveTo(10.12f, 3f)
                lineTo(8.25f, 3f)
                lineTo(5.62f, 3f)
                quadTo(5.25f, 3f, 5.25f, 3.38f)
                lineTo(5.25f, 20.62f)
                quadTo(5.25f, 21f, 5.62f, 21f)
                lineTo(18.38f, 21f)
                quadTo(18.75f, 21f, 18.75f, 20.62f)
                lineTo(18.75f, 11.62f)
                quadTo(18.75f, 9f, 16.12f, 9f)
                lineTo(14.62f, 9f)
                quadTo(12.75f, 9f, 12.75f, 7.12f)
                lineTo(12.75f, 5.62f)
                quadTo(12.75f, 4.54f, 11.98f, 3.77f)
                quadTo(11.21f, 3f, 10.12f, 3f)
                close()
                moveTo(12.75f, 11.25f)
                lineTo(12.75f, 13.5f)
                lineTo(15f, 13.5f)
                quadTo(15.31f, 13.5f, 15.53f, 13.72f)
                quadTo(15.75f, 13.94f, 15.75f, 14.25f)
                quadTo(15.75f, 14.56f, 15.53f, 14.78f)
                quadTo(15.31f, 15f, 15f, 15f)
                lineTo(12.75f, 15f)
                lineTo(12.75f, 17.25f)
                quadTo(12.75f, 17.56f, 12.53f, 17.78f)
                quadTo(12.31f, 18f, 12f, 18f)
                quadTo(11.69f, 18f, 11.47f, 17.78f)
                quadTo(11.25f, 17.56f, 11.25f, 17.25f)
                lineTo(11.25f, 15f)
                lineTo(9f, 15f)
                quadTo(8.69f, 15f, 8.47f, 14.78f)
                quadTo(8.25f, 14.56f, 8.25f, 14.25f)
                quadTo(8.25f, 13.94f, 8.47f, 13.72f)
                quadTo(8.69f, 13.5f, 9f, 13.5f)
                lineTo(11.25f, 13.5f)
                lineTo(11.25f, 11.25f)
                quadTo(11.25f, 10.94f, 11.47f, 10.72f)
                quadTo(11.69f, 10.5f, 12f, 10.5f)
                quadTo(12.31f, 10.5f, 12.53f, 10.72f)
                quadTo(12.75f, 10.94f, 12.75f, 11.25f)
                close()
                moveTo(18.11f, 8f)
                quadTo(17.51f, 6.59f, 16.33f, 5.42f)
                quadTo(15.16f, 4.24f, 13.75f, 3.64f)
                quadTo(14.25f, 4.53f, 14.25f, 5.62f)
                lineTo(14.25f, 7.12f)
                quadTo(14.25f, 7.5f, 14.62f, 7.5f)
                lineTo(16.12f, 7.5f)
                quadTo(17.22f, 7.5f, 18.11f, 8f)
                close()
            }
        }.build()
}
