// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val DocumentCurrencyRupee: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "DocumentCurrencyRupee",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(10.5f, 1.5f)
                quadTo(14.54f, 1.5f, 17.39f, 4.36f)
                quadTo(20.25f, 7.21f, 20.25f, 11.25f)
                lineTo(20.25f, 20.62f)
                quadTo(20.25f, 22.5f, 18.38f, 22.5f)
                lineTo(5.62f, 22.5f)
                quadTo(3.75f, 22.5f, 3.75f, 20.62f)
                lineTo(3.75f, 3.38f)
                quadTo(3.75f, 1.5f, 5.62f, 1.5f)
                close()
                moveTo(10.12f, 3f)
                lineTo(8.25f, 3f)
                lineTo(5.62f, 3f)
                quadTo(5.25f, 3f, 5.25f, 3.38f)
                lineTo(5.25f, 20.62f)
                quadTo(5.25f, 21f, 5.62f, 21f)
                lineTo(18.38f, 21f)
                quadTo(18.75f, 21f, 18.75f, 20.62f)
                lineTo(18.75f, 11.62f)
                quadTo(18.75f, 9f, 16.12f, 9f)
                lineTo(14.62f, 9f)
                quadTo(12.75f, 9f, 12.75f, 7.12f)
                lineTo(12.75f, 5.62f)
                quadTo(12.75f, 4.54f, 11.98f, 3.77f)
                quadTo(11.21f, 3f, 10.12f, 3f)
                close()
                moveTo(10.5f, 10.5f)
                lineTo(14.25f, 10.5f)
                quadTo(14.56f, 10.5f, 14.78f, 10.72f)
                quadTo(15f, 10.94f, 15f, 11.25f)
                quadTo(15f, 11.56f, 14.78f, 11.78f)
                quadTo(14.56f, 12f, 14.25f, 12f)
                lineTo(13.12f, 12f)
                quadTo(13.37f, 12.48f, 13.45f, 13.12f)
                lineTo(14.25f, 13.12f)
                quadTo(14.56f, 13.12f, 14.78f, 13.35f)
                quadTo(15f, 13.56f, 15f, 13.88f)
                quadTo(15f, 14.19f, 14.78f, 14.4f)
                quadTo(14.56f, 14.62f, 14.25f, 14.62f)
                lineTo(13.45f, 14.62f)
                quadTo(13.19f, 16.62f, 11.41f, 17.1f)
                lineTo(12.53f, 18.22f)
                quadTo(12.75f, 18.44f, 12.75f, 18.75f)
                quadTo(12.75f, 19.06f, 12.53f, 19.28f)
                quadTo(12.31f, 19.5f, 12f, 19.5f)
                quadTo(11.69f, 19.5f, 11.47f, 19.28f)
                lineTo(9.22f, 17.03f)
                quadTo(9f, 16.81f, 9f, 16.5f)
                quadTo(9f, 16.19f, 9.22f, 15.97f)
                quadTo(9.44f, 15.75f, 9.75f, 15.75f)
                lineTo(10.12f, 15.75f)
                quadTo(11.58f, 15.75f, 11.9f, 14.62f)
                lineTo(9.75f, 14.62f)
                quadTo(9.44f, 14.62f, 9.22f, 14.4f)
                quadTo(9f, 14.19f, 9f, 13.88f)
                quadTo(9f, 13.56f, 9.22f, 13.35f)
                quadTo(9.44f, 13.12f, 9.75f, 13.12f)
                lineTo(11.9f, 13.12f)
                quadTo(11.58f, 12f, 10.12f, 12f)
                lineTo(9.75f, 12f)
                quadTo(9.44f, 12f, 9.22f, 11.78f)
                quadTo(9f, 11.56f, 9f, 11.25f)
                quadTo(9f, 10.94f, 9.22f, 10.72f)
                quadTo(9.44f, 10.5f, 9.75f, 10.5f)
                lineTo(10.12f, 10.5f)
                quadTo(10.27f, 10.5f, 10.4f, 10.51f)
                quadTo(10.45f, 10.5f, 10.5f, 10.5f)
                close()
                moveTo(18.11f, 8f)
                quadTo(17.51f, 6.59f, 16.33f, 5.42f)
                quadTo(15.16f, 4.24f, 13.75f, 3.64f)
                quadTo(14.25f, 4.53f, 14.25f, 5.62f)
                lineTo(14.25f, 7.12f)
                quadTo(14.25f, 7.5f, 14.62f, 7.5f)
                lineTo(16.12f, 7.5f)
                quadTo(17.22f, 7.5f, 18.11f, 8f)
                close()
            }
        }.build()
}
