// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val EnvelopeOpen: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "EnvelopeOpen",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(22.5f, 19.5f)
                quadTo(22.5f, 22.5f, 19.5f, 22.5f)
                lineTo(4.5f, 22.5f)
                quadTo(1.5f, 22.5f, 1.5f, 19.5f)
                lineTo(1.5f, 9.91f)
                lineTo(1.5f, 8.84f)
                quadTo(1.5f, 7.05f, 3.08f, 6.2f)
                lineTo(10.58f, 2.16f)
                quadTo(12f, 1.4f, 13.42f, 2.16f)
                lineTo(20.92f, 6.2f)
                quadTo(22.5f, 7.05f, 22.5f, 8.84f)
                close()
                moveTo(3f, 9.91f)
                quadTo(3f, 10.8f, 3.79f, 11.23f)
                lineTo(9.91f, 14.52f)
                lineTo(10.58f, 14.16f)
                quadTo(12f, 13.4f, 13.42f, 14.16f)
                lineTo(14.09f, 14.52f)
                lineTo(20.21f, 11.23f)
                quadTo(21f, 10.8f, 21f, 9.91f)
                lineTo(21f, 8.84f)
                quadTo(21f, 7.95f, 20.21f, 7.52f)
                lineTo(12.71f, 3.48f)
                quadTo(12f, 3.1f, 11.29f, 3.48f)
                lineTo(3.79f, 7.52f)
                quadTo(3f, 7.95f, 3f, 8.84f)
                lineTo(3f, 9.91f)
                close()
                moveTo(18.39f, 18.55f)
                lineTo(13.77f, 16.06f)
                quadTo(13.72f, 16.03f, 13.68f, 16.01f)
                lineTo(12.71f, 15.49f)
                quadTo(12f, 15.1f, 11.29f, 15.48f)
                lineTo(10.31f, 16.01f)
                quadTo(10.28f, 16.03f, 10.23f, 16.05f)
                lineTo(5.61f, 18.55f)
                quadTo(5.33f, 18.69f, 5.04f, 18.6f)
                quadTo(4.74f, 18.51f, 4.59f, 18.24f)
                quadTo(4.44f, 17.97f, 4.53f, 17.67f)
                quadTo(4.62f, 17.37f, 4.89f, 17.23f)
                lineTo(8.33f, 15.38f)
                lineTo(3.08f, 12.55f)
                quadTo(3.04f, 12.53f, 3f, 12.51f)
                lineTo(3f, 19.5f)
                quadTo(3f, 21f, 4.5f, 21f)
                lineTo(19.5f, 21f)
                quadTo(21f, 21f, 21f, 19.5f)
                lineTo(21f, 12.51f)
                quadTo(20.96f, 12.53f, 20.92f, 12.55f)
                lineTo(15.67f, 15.38f)
                lineTo(19.11f, 17.23f)
                quadTo(19.38f, 17.37f, 19.47f, 17.67f)
                quadTo(19.56f, 17.97f, 19.41f, 18.24f)
                quadTo(19.26f, 18.51f, 18.96f, 18.6f)
                quadTo(18.67f, 18.69f, 18.39f, 18.55f)
                close()
            }
        }.build()
}
