// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val ExclamationTriangle: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "ExclamationTriangle",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(2.05f, 15.75f)
                lineTo(9.4f, 3f)
                quadTo(10.27f, 1.5f, 12f, 1.5f)
                quadTo(13.73f, 1.5f, 14.6f, 3f)
                lineTo(21.95f, 15.75f)
                quadTo(22.82f, 17.25f, 21.95f, 18.75f)
                quadTo(21.09f, 20.25f, 19.36f, 20.25f)
                lineTo(4.64f, 20.25f)
                quadTo(2.91f, 20.25f, 2.05f, 18.75f)
                quadTo(1.18f, 17.25f, 2.05f, 15.75f)
                close()
                moveTo(3.35f, 16.5f)
                quadTo(2.91f, 17.25f, 3.35f, 18f)
                quadTo(3.78f, 18.75f, 4.64f, 18.75f)
                lineTo(19.36f, 18.75f)
                quadTo(20.22f, 18.75f, 20.65f, 18f)
                quadTo(21.09f, 17.25f, 20.65f, 16.5f)
                lineTo(13.3f, 3.75f)
                quadTo(12.87f, 3f, 12f, 3f)
                quadTo(11.13f, 3f, 10.7f, 3.75f)
                lineTo(3.35f, 16.5f)
                close()
                moveTo(12.75f, 9f)
                lineTo(12.75f, 12.75f)
                quadTo(12.75f, 13.06f, 12.53f, 13.28f)
                quadTo(12.31f, 13.5f, 12f, 13.5f)
                quadTo(11.69f, 13.5f, 11.47f, 13.28f)
                quadTo(11.25f, 13.06f, 11.25f, 12.75f)
                lineTo(11.25f, 9f)
                quadTo(11.25f, 8.69f, 11.47f, 8.47f)
                quadTo(11.69f, 8.25f, 12f, 8.25f)
                quadTo(12.31f, 8.25f, 12.53f, 8.47f)
                quadTo(12.75f, 8.69f, 12.75f, 9f)
                close()
                moveTo(12f, 15f)
                lineTo(12.01f, 15f)
                quadTo(12.32f, 15f, 12.54f, 15.22f)
                quadTo(12.76f, 15.44f, 12.76f, 15.75f)
                lineTo(12.76f, 15.76f)
                quadTo(12.76f, 16.07f, 12.54f, 16.29f)
                quadTo(12.32f, 16.51f, 12.01f, 16.51f)
                lineTo(12f, 16.51f)
                quadTo(11.69f, 16.51f, 11.47f, 16.29f)
                quadTo(11.25f, 16.07f, 11.25f, 15.76f)
                lineTo(11.25f, 15.75f)
                quadTo(11.25f, 15.44f, 11.47f, 15.22f)
                quadTo(11.69f, 15f, 12f, 15f)
                close()
            }
        }.build()
}
