// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val FaceFrown: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "FaceFrown",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(21.75f, 12f)
                quadTo(21.75f, 16.04f, 18.89f, 18.89f)
                quadTo(16.04f, 21.75f, 12f, 21.75f)
                quadTo(7.96f, 21.75f, 5.11f, 18.89f)
                quadTo(2.25f, 16.04f, 2.25f, 12f)
                quadTo(2.25f, 7.96f, 5.11f, 5.11f)
                quadTo(7.96f, 2.25f, 12f, 2.25f)
                quadTo(16.04f, 2.25f, 18.89f, 5.11f)
                quadTo(21.75f, 7.96f, 21.75f, 12f)
                close()
                moveTo(20.25f, 12f)
                quadTo(20.25f, 8.58f, 17.83f, 6.17f)
                quadTo(15.42f, 3.75f, 12f, 3.75f)
                quadTo(8.58f, 3.75f, 6.17f, 6.17f)
                quadTo(3.75f, 8.58f, 3.75f, 12f)
                quadTo(3.75f, 15.42f, 6.17f, 17.83f)
                quadTo(8.58f, 20.25f, 12f, 20.25f)
                quadTo(15.42f, 20.25f, 17.83f, 17.83f)
                quadTo(20.25f, 15.42f, 20.25f, 12f)
                close()
                moveTo(14.65f, 16.85f)
                quadTo(13.56f, 15.75f, 12.01f, 15.75f)
                quadTo(10.45f, 15.74f, 9.35f, 16.85f)
                quadTo(9.13f, 17.07f, 8.82f, 17.07f)
                quadTo(8.51f, 17.07f, 8.29f, 16.85f)
                quadTo(8.07f, 16.63f, 8.07f, 16.32f)
                quadTo(8.07f, 16.01f, 8.29f, 15.79f)
                quadTo(9.83f, 14.24f, 12.02f, 14.25f)
                quadTo(14.18f, 14.26f, 15.71f, 15.79f)
                quadTo(15.93f, 16.01f, 15.93f, 16.32f)
                quadTo(15.93f, 16.63f, 15.71f, 16.85f)
                quadTo(15.49f, 17.07f, 15.18f, 17.07f)
                quadTo(14.87f, 17.07f, 14.65f, 16.85f)
                close()
                moveTo(10.5f, 9.75f)
                quadTo(10.5f, 11.25f, 9.38f, 11.25f)
                quadTo(8.25f, 11.25f, 8.25f, 9.75f)
                quadTo(8.25f, 8.25f, 9.38f, 8.25f)
                quadTo(10.5f, 8.25f, 10.5f, 9.75f)
                close()
                moveTo(15.75f, 9.75f)
                quadTo(15.75f, 11.25f, 14.62f, 11.25f)
                quadTo(13.5f, 11.25f, 13.5f, 9.75f)
                quadTo(13.5f, 8.25f, 14.62f, 8.25f)
                quadTo(15.75f, 8.25f, 15.75f, 9.75f)
                close()
            }
        }.build()
}
