// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val FingerPrint: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "FingerPrint",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(7.45f, 3.62f)
                quadTo(11.56f, 0.9f, 15.91f, 3.23f)
                quadTo(20.25f, 5.57f, 20.25f, 10.5f)
                quadTo(20.25f, 14.95f, 18.63f, 19.04f)
                quadTo(18.52f, 19.33f, 18.23f, 19.46f)
                quadTo(17.95f, 19.58f, 17.66f, 19.46f)
                quadTo(17.37f, 19.35f, 17.24f, 19.07f)
                quadTo(17.12f, 18.78f, 17.23f, 18.49f)
                quadTo(18.75f, 14.66f, 18.75f, 10.5f)
                quadTo(18.75f, 6.46f, 15.2f, 4.55f)
                quadTo(11.64f, 2.64f, 8.28f, 4.87f)
                quadTo(8.02f, 5.04f, 7.71f, 4.98f)
                quadTo(7.41f, 4.92f, 7.24f, 4.66f)
                quadTo(7.07f, 4.4f, 7.13f, 4.09f)
                quadTo(7.19f, 3.79f, 7.45f, 3.62f)
                close()
                moveTo(4.78f, 17.55f)
                quadTo(7.51f, 14.55f, 7.5f, 10.5f)
                quadTo(7.5f, 8.64f, 8.82f, 7.32f)
                quadTo(10.14f, 6f, 12f, 6f)
                quadTo(13.86f, 6f, 15.18f, 7.32f)
                quadTo(16.5f, 8.64f, 16.5f, 10.5f)
                quadTo(16.5f, 11.33f, 16.43f, 12.13f)
                quadTo(16.41f, 12.44f, 16.17f, 12.64f)
                quadTo(15.93f, 12.84f, 15.62f, 12.81f)
                quadTo(15.31f, 12.79f, 15.11f, 12.55f)
                quadTo(14.91f, 12.31f, 14.94f, 12f)
                quadTo(15f, 11.27f, 15f, 10.5f)
                quadTo(15f, 7.5f, 12f, 7.5f)
                quadTo(9f, 7.5f, 9f, 10.5f)
                quadTo(9.01f, 15.13f, 5.89f, 18.56f)
                quadTo(5.68f, 18.79f, 5.38f, 18.8f)
                quadTo(5.07f, 18.82f, 4.83f, 18.61f)
                quadTo(4.61f, 18.4f, 4.59f, 18.09f)
                quadTo(4.58f, 17.78f, 4.78f, 17.55f)
                close()
                moveTo(12.75f, 10.5f)
                quadTo(12.76f, 16.32f, 8.97f, 20.74f)
                quadTo(8.77f, 20.97f, 8.46f, 21f)
                quadTo(8.15f, 21.02f, 7.91f, 20.82f)
                quadTo(7.68f, 20.62f, 7.65f, 20.31f)
                quadTo(7.63f, 20f, 7.83f, 19.76f)
                quadTo(11.26f, 15.77f, 11.25f, 10.5f)
                quadTo(11.25f, 10.19f, 11.47f, 9.97f)
                quadTo(11.69f, 9.75f, 12f, 9.75f)
                quadTo(12.31f, 9.75f, 12.53f, 9.97f)
                quadTo(12.75f, 10.19f, 12.75f, 10.5f)
                close()
                moveTo(6.37f, 6.78f)
                quadTo(5.25f, 8.47f, 5.25f, 10.5f)
                quadTo(5.25f, 12.88f, 3.98f, 14.89f)
                quadTo(3.82f, 15.16f, 3.52f, 15.22f)
                quadTo(3.21f, 15.29f, 2.95f, 15.13f)
                quadTo(2.69f, 14.96f, 2.62f, 14.66f)
                quadTo(2.55f, 14.36f, 2.72f, 14.09f)
                quadTo(3.75f, 12.45f, 3.75f, 10.5f)
                quadTo(3.75f, 8.02f, 5.12f, 5.95f)
                quadTo(5.29f, 5.69f, 5.59f, 5.63f)
                quadTo(5.9f, 5.57f, 6.16f, 5.74f)
                quadTo(6.42f, 5.91f, 6.48f, 6.21f)
                quadTo(6.54f, 6.52f, 6.37f, 6.78f)
                close()
                moveTo(15.75f, 15.86f)
                quadTo(14.9f, 18.84f, 13.17f, 21.4f)
                quadTo(12.99f, 21.66f, 12.69f, 21.72f)
                quadTo(12.38f, 21.78f, 12.13f, 21.61f)
                quadTo(11.87f, 21.43f, 11.81f, 21.13f)
                quadTo(11.75f, 20.82f, 11.93f, 20.56f)
                quadTo(13.53f, 18.2f, 14.31f, 15.45f)
                quadTo(14.4f, 15.15f, 14.67f, 15f)
                quadTo(14.94f, 14.85f, 15.24f, 14.93f)
                quadTo(15.54f, 15.02f, 15.69f, 15.29f)
                quadTo(15.84f, 15.56f, 15.75f, 15.86f)
                close()
            }
        }.build()
}
