// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Fire: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "Fire",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(15.67f, 4.53f)
                quadTo(18.58f, 5.83f, 20.02f, 8.67f)
                quadTo(21.46f, 11.51f, 20.8f, 14.62f)
                quadTo(20.14f, 17.74f, 17.66f, 19.74f)
                quadTo(15.19f, 21.75f, 12f, 21.75f)
                quadTo(6.06f, 21.75f, 3.72f, 16.29f)
                quadTo(1.39f, 10.82f, 5.5f, 6.53f)
                quadTo(5.71f, 6.3f, 6.02f, 6.3f)
                quadTo(6.33f, 6.29f, 6.56f, 6.5f)
                quadTo(6.61f, 6.55f, 6.65f, 6.61f)
                quadTo(7.37f, 7.62f, 8.34f, 8.32f)
                quadTo(8.83f, 4.61f, 11.89f, 2.15f)
                quadTo(12.13f, 1.96f, 12.44f, 1.99f)
                quadTo(12.75f, 2.02f, 12.95f, 2.27f)
                quadTo(12.95f, 2.27f, 12.96f, 2.29f)
                quadTo(14.04f, 3.74f, 15.67f, 4.53f)
                close()
                moveTo(15.08f, 5.91f)
                quadTo(15.06f, 5.9f, 15.03f, 5.89f)
                quadTo(13.43f, 5.11f, 12.27f, 3.81f)
                quadTo(9.8f, 6.12f, 9.75f, 9.61f)
                quadTo(9.75f, 9.79f, 9.67f, 9.94f)
                quadTo(9.53f, 10.22f, 9.23f, 10.31f)
                quadTo(8.94f, 10.41f, 8.66f, 10.27f)
                quadTo(7.12f, 9.48f, 6.01f, 8.21f)
                quadTo(3.33f, 11.55f, 5.1f, 15.7f)
                quadTo(7.05f, 20.25f, 12f, 20.25f)
                quadTo(18.07f, 20.25f, 19.33f, 14.31f)
                quadTo(20.59f, 8.39f, 15.08f, 5.91f)
                close()
                moveTo(12f, 18.75f)
                lineTo(12f, 18.75f)
                quadTo(9.7f, 18.75f, 8.35f, 16.89f)
                quadTo(7.01f, 15.03f, 7.72f, 12.84f)
                quadTo(7.76f, 12.73f, 7.83f, 12.63f)
                quadTo(8.02f, 12.38f, 8.33f, 12.34f)
                quadTo(8.63f, 12.29f, 8.88f, 12.47f)
                quadTo(9.41f, 12.87f, 10.01f, 13.11f)
                quadTo(10.53f, 11.29f, 11.99f, 9.97f)
                quadTo(12.25f, 9.74f, 12.59f, 9.79f)
                quadTo(16.77f, 10.34f, 16.5f, 14.55f)
                quadTo(16.22f, 18.76f, 12f, 18.75f)
                close()
                moveTo(12f, 17.25f)
                quadTo(14.81f, 17.25f, 15f, 14.45f)
                quadTo(15.17f, 11.82f, 12.74f, 11.33f)
                quadTo(11.57f, 12.52f, 11.31f, 14.19f)
                quadTo(11.26f, 14.5f, 11.01f, 14.68f)
                quadTo(10.76f, 14.87f, 10.46f, 14.82f)
                quadTo(10.42f, 14.81f, 10.39f, 14.81f)
                quadTo(9.65f, 14.63f, 8.98f, 14.29f)
                quadTo(8.98f, 15.2f, 9.57f, 16.01f)
                quadTo(10.47f, 17.25f, 12f, 17.25f)
                close()
            }
        }.build()
}
