// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Flag: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "Flag",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(3.75f, 3f)
                lineTo(3.75f, 3.54f)
                lineTo(5.59f, 3.08f)
                quadTo(9.09f, 2.21f, 12.31f, 3.82f)
                lineTo(12.42f, 3.87f)
                quadTo(15.09f, 5.21f, 18f, 4.52f)
                lineTo(21.11f, 3.79f)
                quadTo(21.23f, 3.76f, 21.36f, 3.78f)
                quadTo(21.67f, 3.81f, 21.86f, 4.05f)
                quadTo(22.06f, 4.29f, 22.03f, 4.6f)
                quadTo(21.47f, 9.77f, 22.03f, 14.94f)
                quadTo(22.06f, 15.22f, 21.9f, 15.45f)
                quadTo(21.73f, 15.69f, 21.46f, 15.75f)
                lineTo(18.34f, 16.48f)
                quadTo(14.91f, 17.29f, 11.75f, 15.71f)
                lineTo(11.64f, 15.66f)
                quadTo(8.91f, 14.29f, 5.95f, 15.04f)
                lineTo(3.75f, 15.59f)
                lineTo(3.75f, 21f)
                quadTo(3.75f, 21.31f, 3.53f, 21.53f)
                quadTo(3.31f, 21.75f, 3f, 21.75f)
                quadTo(2.69f, 21.75f, 2.47f, 21.53f)
                quadTo(2.25f, 21.31f, 2.25f, 21f)
                lineTo(2.25f, 15.04f)
                quadTo(2.25f, 14.99f, 2.25f, 14.94f)
                lineTo(2.25f, 4.54f)
                quadTo(2.25f, 4.49f, 2.25f, 4.44f)
                lineTo(2.25f, 3f)
                quadTo(2.25f, 2.69f, 2.47f, 2.47f)
                quadTo(2.69f, 2.25f, 3f, 2.25f)
                quadTo(3.31f, 2.25f, 3.53f, 2.47f)
                quadTo(3.75f, 2.69f, 3.75f, 3f)
                close()
                moveTo(3.75f, 5.08f)
                lineTo(3.75f, 14.04f)
                lineTo(5.59f, 13.58f)
                quadTo(9.09f, 12.71f, 12.31f, 14.32f)
                lineTo(12.42f, 14.37f)
                quadTo(15.09f, 15.71f, 18f, 15.02f)
                lineTo(20.47f, 14.44f)
                quadTo(20.04f, 9.97f, 20.43f, 5.49f)
                lineTo(18.34f, 5.98f)
                quadTo(14.91f, 6.79f, 11.75f, 5.21f)
                lineTo(11.64f, 5.16f)
                quadTo(8.91f, 3.79f, 5.95f, 4.54f)
                lineTo(3.75f, 5.08f)
                close()
            }
        }.build()
}
