// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Gif: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "Gif",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(4.5f, 20.25f)
                quadTo(1.5f, 20.25f, 1.5f, 17.25f)
                lineTo(1.5f, 6.75f)
                quadTo(1.5f, 3.75f, 4.5f, 3.75f)
                lineTo(19.5f, 3.75f)
                quadTo(22.5f, 3.75f, 22.5f, 6.75f)
                lineTo(22.5f, 17.25f)
                quadTo(22.5f, 20.25f, 19.5f, 20.25f)
                close()
                moveTo(4.5f, 18.75f)
                lineTo(19.5f, 18.75f)
                quadTo(21f, 18.75f, 21f, 17.25f)
                lineTo(21f, 6.75f)
                quadTo(21f, 5.25f, 19.5f, 5.25f)
                lineTo(4.5f, 5.25f)
                quadTo(3f, 5.25f, 3f, 6.75f)
                lineTo(3f, 17.25f)
                quadTo(3f, 18.75f, 4.5f, 18.75f)
                close()
                moveTo(9.14f, 9.78f)
                quadTo(8.59f, 9f, 7.89f, 9f)
                quadTo(7.18f, 9f, 6.63f, 9.78f)
                quadTo(5.07f, 12f, 6.63f, 14.22f)
                quadTo(7.18f, 15f, 7.89f, 15f)
                quadTo(8.5f, 15f, 9f, 14.4f)
                lineTo(9f, 12.75f)
                lineTo(8.25f, 12.75f)
                quadTo(7.94f, 12.75f, 7.72f, 12.53f)
                quadTo(7.5f, 12.31f, 7.5f, 12f)
                quadTo(7.5f, 11.69f, 7.72f, 11.47f)
                quadTo(7.94f, 11.25f, 8.25f, 11.25f)
                lineTo(9.75f, 11.25f)
                quadTo(10.06f, 11.25f, 10.28f, 11.47f)
                quadTo(10.5f, 11.69f, 10.5f, 12f)
                lineTo(10.5f, 14.65f)
                quadTo(10.5f, 14.89f, 10.36f, 15.08f)
                quadTo(9.37f, 16.5f, 7.89f, 16.5f)
                quadTo(6.41f, 16.5f, 5.41f, 15.08f)
                quadTo(3.24f, 12f, 5.41f, 8.92f)
                quadTo(6.41f, 7.5f, 7.89f, 7.5f)
                quadTo(9.37f, 7.5f, 10.36f, 8.92f)
                quadTo(10.54f, 9.17f, 10.49f, 9.48f)
                quadTo(10.44f, 9.78f, 10.18f, 9.96f)
                quadTo(9.93f, 10.14f, 9.62f, 10.09f)
                quadTo(9.31f, 10.03f, 9.14f, 9.78f)
                close()
                moveTo(18.75f, 9f)
                lineTo(16.5f, 9f)
                lineTo(16.5f, 11.25f)
                lineTo(18f, 11.25f)
                quadTo(18.31f, 11.25f, 18.53f, 11.47f)
                quadTo(18.75f, 11.69f, 18.75f, 12f)
                quadTo(18.75f, 12.31f, 18.53f, 12.53f)
                quadTo(18.31f, 12.75f, 18f, 12.75f)
                lineTo(16.5f, 12.75f)
                lineTo(16.5f, 15.75f)
                quadTo(16.5f, 16.06f, 16.28f, 16.28f)
                quadTo(16.06f, 16.5f, 15.75f, 16.5f)
                quadTo(15.44f, 16.5f, 15.22f, 16.28f)
                quadTo(15f, 16.06f, 15f, 15.75f)
                lineTo(15f, 8.25f)
                quadTo(15f, 7.94f, 15.22f, 7.72f)
                quadTo(15.44f, 7.5f, 15.75f, 7.5f)
                lineTo(18.75f, 7.5f)
                quadTo(19.06f, 7.5f, 19.28f, 7.72f)
                quadTo(19.5f, 7.94f, 19.5f, 8.25f)
                quadTo(19.5f, 8.56f, 19.28f, 8.78f)
                quadTo(19.06f, 9f, 18.75f, 9f)
                close()
                moveTo(13.5f, 8.25f)
                lineTo(13.5f, 15.75f)
                quadTo(13.5f, 16.06f, 13.28f, 16.28f)
                quadTo(13.06f, 16.5f, 12.75f, 16.5f)
                quadTo(12.44f, 16.5f, 12.22f, 16.28f)
                quadTo(12f, 16.06f, 12f, 15.75f)
                lineTo(12f, 8.25f)
                quadTo(12f, 7.94f, 12.22f, 7.72f)
                quadTo(12.44f, 7.5f, 12.75f, 7.5f)
                quadTo(13.06f, 7.5f, 13.28f, 7.72f)
                quadTo(13.5f, 7.94f, 13.5f, 8.25f)
                close()
            }
        }.build()
}
