// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val GiftTop: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "GiftTop",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(3.75f, 21f)
                quadTo(1.5f, 21f, 1.5f, 18.75f)
                lineTo(1.5f, 12f)
                lineTo(1.5f, 12f)
                lineTo(1.5f, 5.25f)
                quadTo(1.5f, 4.32f, 2.16f, 3.66f)
                quadTo(2.82f, 3f, 3.75f, 3f)
                lineTo(20.25f, 3f)
                quadTo(22.5f, 3f, 22.5f, 5.25f)
                lineTo(22.5f, 18.75f)
                quadTo(22.5f, 21f, 20.25f, 21f)
                close()
                moveTo(17.62f, 18f)
                quadTo(15.29f, 18f, 13.65f, 16.35f)
                quadTo(13.11f, 15.82f, 12.75f, 15.21f)
                lineTo(12.75f, 19.5f)
                lineTo(20.25f, 19.5f)
                quadTo(21f, 19.5f, 21f, 18.75f)
                lineTo(21f, 12.75f)
                lineTo(13.52f, 12.75f)
                quadTo(13.63f, 14.22f, 14.71f, 15.29f)
                quadTo(15.92f, 16.5f, 17.62f, 16.5f)
                quadTo(17.94f, 16.5f, 18.16f, 16.72f)
                quadTo(18.38f, 16.94f, 18.38f, 17.25f)
                quadTo(18.38f, 17.56f, 18.16f, 17.78f)
                quadTo(17.94f, 18f, 17.62f, 18f)
                close()
                moveTo(6.38f, 16.5f)
                quadTo(8.08f, 16.5f, 9.29f, 15.29f)
                quadTo(10.37f, 14.22f, 10.48f, 12.75f)
                lineTo(3f, 12.75f)
                lineTo(3f, 18.75f)
                quadTo(3f, 19.5f, 3.75f, 19.5f)
                lineTo(11.25f, 19.5f)
                lineTo(11.25f, 15.21f)
                quadTo(10.89f, 15.82f, 10.35f, 16.35f)
                quadTo(8.71f, 18f, 6.38f, 18f)
                quadTo(6.06f, 18f, 5.84f, 17.78f)
                quadTo(5.62f, 17.56f, 5.62f, 17.25f)
                quadTo(5.62f, 16.94f, 5.84f, 16.72f)
                quadTo(6.06f, 16.5f, 6.38f, 16.5f)
                close()
                moveTo(11.25f, 4.5f)
                lineTo(3.75f, 4.5f)
                quadTo(3.44f, 4.5f, 3.22f, 4.72f)
                quadTo(3f, 4.94f, 3f, 5.25f)
                lineTo(3f, 11.25f)
                lineTo(6.97f, 11.25f)
                quadTo(6.18f, 10.4f, 6.18f, 9.22f)
                quadTo(6.18f, 7.98f, 7.06f, 7.1f)
                quadTo(7.94f, 6.22f, 9.18f, 6.22f)
                quadTo(10.39f, 6.22f, 11.25f, 7.05f)
                lineTo(11.25f, 4.5f)
                close()
                moveTo(16.99f, 11.25f)
                lineTo(21f, 11.25f)
                lineTo(21f, 5.25f)
                quadTo(21f, 4.5f, 20.25f, 4.5f)
                lineTo(12.75f, 4.5f)
                lineTo(12.75f, 7.01f)
                quadTo(14.83f, 5.02f, 16.9f, 7.1f)
                quadTo(17.78f, 7.98f, 17.78f, 9.22f)
                quadTo(17.78f, 10.4f, 16.99f, 11.25f)
                close()
                moveTo(15.84f, 10.28f)
                quadTo(15.85f, 10.27f, 15.86f, 10.26f)
                quadTo(16.89f, 9.21f, 15.84f, 8.16f)
                quadTo(14.78f, 7.1f, 13.72f, 8.16f)
                quadTo(12.71f, 9.16f, 12.82f, 11.18f)
                quadTo(14.84f, 11.29f, 15.84f, 10.28f)
                close()
                moveTo(10.24f, 8.16f)
                quadTo(10.23f, 8.15f, 10.21f, 8.13f)
                quadTo(9.78f, 7.72f, 9.18f, 7.72f)
                quadTo(8.56f, 7.72f, 8.12f, 8.16f)
                quadTo(7.68f, 8.6f, 7.68f, 9.22f)
                quadTo(7.68f, 9.84f, 8.12f, 10.28f)
                quadTo(9.13f, 11.29f, 11.14f, 11.18f)
                quadTo(11.25f, 9.17f, 10.24f, 8.16f)
                close()
            }
        }.build()
}
