// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val H1: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "H1",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(2.99f, 4.49f)
                lineTo(2.99f, 11.24f)
                lineTo(11.99f, 11.24f)
                lineTo(11.99f, 4.49f)
                quadTo(11.99f, 4.18f, 12.21f, 3.96f)
                quadTo(12.43f, 3.74f, 12.74f, 3.74f)
                quadTo(13.05f, 3.74f, 13.27f, 3.96f)
                quadTo(13.49f, 4.18f, 13.49f, 4.49f)
                lineTo(13.49f, 19.5f)
                quadTo(13.49f, 19.81f, 13.27f, 20.02f)
                quadTo(13.05f, 20.25f, 12.74f, 20.25f)
                quadTo(12.43f, 20.25f, 12.21f, 20.02f)
                quadTo(11.99f, 19.81f, 11.99f, 19.5f)
                lineTo(11.99f, 12.74f)
                lineTo(2.99f, 12.74f)
                lineTo(2.99f, 19.5f)
                quadTo(2.99f, 19.81f, 2.77f, 20.02f)
                quadTo(2.55f, 20.25f, 2.24f, 20.25f)
                quadTo(1.93f, 20.25f, 1.71f, 20.02f)
                quadTo(1.49f, 19.81f, 1.49f, 19.5f)
                lineTo(1.49f, 4.49f)
                quadTo(1.49f, 4.18f, 1.71f, 3.96f)
                quadTo(1.93f, 3.74f, 2.24f, 3.74f)
                quadTo(2.55f, 3.74f, 2.77f, 3.96f)
                quadTo(2.99f, 4.18f, 2.99f, 4.49f)
                close()
                moveTo(16.83f, 10.24f)
                lineTo(19.08f, 8.74f)
                quadTo(19.34f, 8.57f, 19.64f, 8.63f)
                quadTo(19.95f, 8.69f, 20.12f, 8.95f)
                quadTo(20.24f, 9.14f, 20.24f, 9.37f)
                lineTo(20.24f, 18.74f)
                lineTo(21.74f, 18.74f)
                quadTo(22.05f, 18.74f, 22.27f, 18.96f)
                quadTo(22.49f, 19.18f, 22.49f, 19.49f)
                quadTo(22.49f, 19.8f, 22.27f, 20.02f)
                quadTo(22.05f, 20.24f, 21.74f, 20.24f)
                lineTo(17.24f, 20.24f)
                quadTo(16.93f, 20.24f, 16.71f, 20.02f)
                quadTo(16.49f, 19.8f, 16.49f, 19.49f)
                quadTo(16.49f, 19.18f, 16.71f, 18.96f)
                quadTo(16.93f, 18.74f, 17.24f, 18.74f)
                lineTo(18.74f, 18.74f)
                lineTo(18.74f, 10.77f)
                lineTo(17.66f, 11.49f)
                quadTo(17.4f, 11.66f, 17.1f, 11.6f)
                quadTo(16.79f, 11.54f, 16.62f, 11.28f)
                quadTo(16.45f, 11.03f, 16.51f, 10.72f)
                quadTo(16.57f, 10.42f, 16.83f, 10.24f)
                close()
            }
        }.build()
}
