// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val H2: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "H2",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(2.99f, 4.49f)
                lineTo(2.99f, 11.24f)
                lineTo(11.99f, 11.24f)
                lineTo(11.99f, 4.49f)
                quadTo(11.99f, 4.18f, 12.21f, 3.96f)
                quadTo(12.43f, 3.74f, 12.74f, 3.74f)
                quadTo(13.05f, 3.74f, 13.27f, 3.96f)
                quadTo(13.49f, 4.18f, 13.49f, 4.49f)
                lineTo(13.49f, 19.49f)
                quadTo(13.49f, 19.8f, 13.27f, 20.02f)
                quadTo(13.05f, 20.24f, 12.74f, 20.24f)
                quadTo(12.43f, 20.24f, 12.21f, 20.02f)
                quadTo(11.99f, 19.8f, 11.99f, 19.49f)
                lineTo(11.99f, 12.74f)
                lineTo(2.99f, 12.74f)
                lineTo(2.99f, 19.49f)
                quadTo(2.99f, 19.8f, 2.77f, 20.02f)
                quadTo(2.55f, 20.24f, 2.24f, 20.24f)
                quadTo(1.93f, 20.24f, 1.71f, 20.02f)
                quadTo(1.49f, 19.8f, 1.49f, 19.49f)
                lineTo(1.49f, 4.49f)
                quadTo(1.49f, 4.18f, 1.71f, 3.96f)
                quadTo(1.93f, 3.74f, 2.24f, 3.74f)
                quadTo(2.55f, 3.74f, 2.77f, 3.96f)
                quadTo(2.99f, 4.18f, 2.99f, 4.49f)
                close()
                moveTo(21.75f, 20.25f)
                lineTo(16.5f, 20.25f)
                quadTo(16.19f, 20.25f, 15.97f, 20.03f)
                quadTo(15.75f, 19.81f, 15.75f, 19.5f)
                lineTo(15.75f, 17.89f)
                quadTo(15.75f, 16.04f, 17.41f, 15.21f)
                lineTo(20.3f, 13.76f)
                quadTo(21f, 13.41f, 21f, 12.75f)
                quadTo(21f, 12.07f, 20.89f, 11.41f)
                quadTo(20.76f, 10.62f, 19.9f, 10.55f)
                quadTo(18.25f, 10.41f, 16.61f, 10.66f)
                quadTo(16.3f, 10.71f, 16.05f, 10.52f)
                quadTo(15.8f, 10.34f, 15.76f, 10.03f)
                quadTo(15.71f, 9.72f, 15.9f, 9.47f)
                quadTo(16.08f, 9.22f, 16.39f, 9.18f)
                quadTo(18.2f, 8.91f, 20.02f, 9.05f)
                quadTo(22.05f, 9.21f, 22.37f, 11.17f)
                quadTo(22.5f, 11.95f, 22.5f, 12.75f)
                quadTo(22.5f, 14.34f, 20.97f, 15.11f)
                lineTo(18.08f, 16.55f)
                quadTo(17.25f, 16.96f, 17.25f, 17.89f)
                lineTo(17.25f, 18.75f)
                lineTo(21.75f, 18.75f)
                quadTo(22.06f, 18.75f, 22.28f, 18.97f)
                quadTo(22.5f, 19.19f, 22.5f, 19.5f)
                quadTo(22.5f, 19.81f, 22.28f, 20.03f)
                quadTo(22.06f, 20.25f, 21.75f, 20.25f)
                close()
            }
        }.build()
}
