// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val HandThumbDown: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "HandThumbDown",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(7.5f, 16f)
                lineTo(4.37f, 16f)
                quadTo(1.83f, 16f, 1.57f, 13.62f)
                quadTo(1.5f, 12.93f, 1.5f, 12.25f)
                quadTo(1.5f, 7.75f, 4.32f, 4.26f)
                quadTo(5.13f, 3.25f, 6.5f, 3.25f)
                lineTo(10.52f, 3.25f)
                quadTo(11.37f, 3.25f, 12.18f, 3.52f)
                lineTo(15.29f, 4.56f)
                quadTo(15.87f, 4.75f, 16.48f, 4.75f)
                lineTo(17.15f, 4.75f)
                quadTo(17.21f, 4.64f, 17.28f, 4.54f)
                quadTo(17.68f, 4f, 18.35f, 4f)
                lineTo(19.26f, 4f)
                quadTo(21.37f, 4f, 21.95f, 5.9f)
                quadTo(22.5f, 7.71f, 22.5f, 9.62f)
                quadTo(22.5f, 12.05f, 21.62f, 14.3f)
                quadTo(20.94f, 16f, 19f, 16f)
                lineTo(17.95f, 16f)
                quadTo(17.14f, 16f, 16.76f, 15.26f)
                quadTo(16.62f, 14.98f, 16.6f, 14.7f)
                quadTo(16.24f, 14.9f, 15.93f, 15.29f)
                quadTo(14.65f, 16.92f, 12.83f, 17.89f)
                quadTo(11.84f, 18.42f, 11.52f, 19.22f)
                quadTo(11.25f, 19.9f, 11.25f, 20.62f)
                lineTo(11.25f, 21.25f)
                quadTo(11.25f, 22.75f, 9.75f, 22.75f)
                quadTo(8.25f, 22.75f, 7.5f, 22f)
                quadTo(6.75f, 21.25f, 6.75f, 19.75f)
                quadTo(6.75f, 17.89f, 7.55f, 16.21f)
                quadTo(7.58f, 16.13f, 7.53f, 16.04f)
                quadTo(7.51f, 16f, 7.5f, 16f)
                close()
                moveTo(17.28f, 6.25f)
                lineTo(16.48f, 6.25f)
                quadTo(15.63f, 6.25f, 14.82f, 5.98f)
                lineTo(11.71f, 4.94f)
                quadTo(11.13f, 4.75f, 10.52f, 4.75f)
                lineTo(6.5f, 4.75f)
                quadTo(5.84f, 4.75f, 5.48f, 5.2f)
                quadTo(3f, 8.28f, 3f, 12.25f)
                quadTo(3f, 12.86f, 3.06f, 13.46f)
                quadTo(3.17f, 14.5f, 4.37f, 14.5f)
                lineTo(9.7f, 14.5f)
                quadTo(10.01f, 14.5f, 10.23f, 14.72f)
                quadTo(10.45f, 14.94f, 10.45f, 15.25f)
                quadTo(10.45f, 15.56f, 10.23f, 15.78f)
                quadTo(10.01f, 16f, 9.7f, 16f)
                lineTo(9.07f, 16f)
                quadTo(9.1f, 16.43f, 8.9f, 16.86f)
                quadTo(8.25f, 18.23f, 8.25f, 19.75f)
                quadTo(8.25f, 21.25f, 9.75f, 21.25f)
                lineTo(9.75f, 20.62f)
                quadTo(9.75f, 19.61f, 10.12f, 18.67f)
                quadTo(10.65f, 17.35f, 12.12f, 16.57f)
                quadTo(13.67f, 15.74f, 14.74f, 14.37f)
                quadTo(15.79f, 13.04f, 17.28f, 13f)
                quadTo(18f, 11.41f, 18f, 9.62f)
                quadTo(18f, 7.85f, 17.28f, 6.25f)
                close()
                moveTo(18.59f, 5.5f)
                quadTo(19.5f, 7.44f, 19.5f, 9.62f)
                quadTo(19.5f, 11.97f, 18.45f, 14.04f)
                quadTo(18.42f, 14.09f, 18.39f, 14.14f)
                quadTo(18.3f, 14.32f, 18.2f, 14.5f)
                lineTo(19f, 14.5f)
                quadTo(19.92f, 14.5f, 20.22f, 13.75f)
                quadTo(21f, 11.77f, 21f, 9.62f)
                quadTo(21f, 7.94f, 20.51f, 6.34f)
                quadTo(20.26f, 5.5f, 19.26f, 5.5f)
                lineTo(18.59f, 5.5f)
                close()
            }
        }.build()
}
