// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val HomeModern: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "HomeModern",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(2.25f, 20.25f)
                lineTo(3f, 20.25f)
                lineTo(3f, 9.53f)
                lineTo(2.51f, 9.71f)
                quadTo(2.21f, 9.81f, 1.93f, 9.68f)
                quadTo(1.65f, 9.55f, 1.54f, 9.26f)
                quadTo(1.44f, 8.96f, 1.57f, 8.68f)
                quadTo(1.7f, 8.4f, 1.99f, 8.29f)
                lineTo(3f, 7.93f)
                lineTo(3f, 3f)
                quadTo(3f, 2.69f, 3.22f, 2.47f)
                quadTo(3.44f, 2.25f, 3.75f, 2.25f)
                lineTo(6.75f, 2.25f)
                quadTo(7.06f, 2.25f, 7.28f, 2.47f)
                quadTo(7.5f, 2.69f, 7.5f, 3f)
                lineTo(7.5f, 6.29f)
                lineTo(16.94f, 2.86f)
                quadTo(16.99f, 2.84f, 17.05f, 2.82f)
                lineTo(18.49f, 2.29f)
                quadTo(18.79f, 2.19f, 19.07f, 2.32f)
                quadTo(19.35f, 2.45f, 19.45f, 2.74f)
                quadTo(19.56f, 3.04f, 19.43f, 3.32f)
                quadTo(19.3f, 3.6f, 19.01f, 3.71f)
                lineTo(18f, 4.07f)
                lineTo(18f, 9.21f)
                lineTo(20.44f, 10.02f)
                quadTo(20.49f, 10.04f, 20.54f, 10.06f)
                lineTo(21.99f, 10.54f)
                quadTo(22.28f, 10.64f, 22.42f, 10.91f)
                quadTo(22.56f, 11.19f, 22.46f, 11.49f)
                quadTo(22.36f, 11.78f, 22.09f, 11.92f)
                quadTo(21.81f, 12.06f, 21.51f, 11.96f)
                lineTo(21f, 11.79f)
                lineTo(21f, 20.25f)
                lineTo(21.75f, 20.25f)
                quadTo(22.06f, 20.25f, 22.28f, 20.47f)
                quadTo(22.5f, 20.69f, 22.5f, 21f)
                quadTo(22.5f, 21.31f, 22.28f, 21.53f)
                quadTo(22.06f, 21.75f, 21.75f, 21.75f)
                lineTo(2.25f, 21.75f)
                quadTo(1.94f, 21.75f, 1.72f, 21.53f)
                quadTo(1.5f, 21.31f, 1.5f, 21f)
                quadTo(1.5f, 20.69f, 1.72f, 20.47f)
                quadTo(1.94f, 20.25f, 2.25f, 20.25f)
                close()
                moveTo(16.5f, 4.62f)
                lineTo(7.06f, 8.05f)
                quadTo(7.01f, 8.07f, 6.96f, 8.09f)
                lineTo(4.5f, 8.98f)
                lineTo(4.5f, 20.25f)
                lineTo(7.5f, 20.25f)
                lineTo(7.5f, 16.12f)
                quadTo(7.5f, 14.25f, 9.38f, 14.25f)
                lineTo(11.62f, 14.25f)
                quadTo(13.5f, 14.25f, 13.5f, 16.12f)
                lineTo(13.5f, 20.25f)
                lineTo(16.5f, 20.25f)
                lineTo(16.5f, 9.81f)
                quadTo(16.5f, 9.75f, 16.5f, 9.7f)
                lineTo(16.5f, 4.62f)
                close()
                moveTo(18f, 10.79f)
                lineTo(18f, 20.25f)
                lineTo(19.5f, 20.25f)
                lineTo(19.5f, 11.29f)
                lineTo(18f, 10.79f)
                close()
                moveTo(9f, 20.25f)
                lineTo(12f, 20.25f)
                lineTo(12f, 16.12f)
                quadTo(12f, 15.75f, 11.62f, 15.75f)
                lineTo(9.38f, 15.75f)
                quadTo(9f, 15.75f, 9f, 16.12f)
                lineTo(9f, 20.25f)
                close()
                moveTo(4.5f, 7.38f)
                lineTo(6f, 6.84f)
                lineTo(6f, 3.75f)
                lineTo(4.5f, 3.75f)
                lineTo(4.5f, 7.38f)
                close()
            }
        }.build()
}
