// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Identification: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "Identification",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(4.5f, 20.25f)
                quadTo(1.5f, 20.25f, 1.5f, 17.25f)
                lineTo(1.5f, 6.75f)
                quadTo(1.5f, 3.75f, 4.5f, 3.75f)
                lineTo(19.5f, 3.75f)
                quadTo(22.5f, 3.75f, 22.5f, 6.75f)
                lineTo(22.5f, 17.25f)
                quadTo(22.5f, 20.25f, 19.5f, 20.25f)
                close()
                moveTo(4.5f, 18.75f)
                lineTo(19.5f, 18.75f)
                quadTo(21f, 18.75f, 21f, 17.25f)
                lineTo(21f, 6.75f)
                quadTo(21f, 5.25f, 19.5f, 5.25f)
                lineTo(4.5f, 5.25f)
                quadTo(3f, 5.25f, 3f, 6.75f)
                lineTo(3f, 17.25f)
                quadTo(3f, 18.75f, 4.5f, 18.75f)
                close()
                moveTo(12.15f, 16.37f)
                quadTo(10.49f, 17.25f, 8.62f, 17.25f)
                quadTo(6.75f, 17.25f, 5.1f, 16.37f)
                quadTo(4.86f, 16.24f, 4.75f, 15.98f)
                quadTo(4.66f, 15.72f, 4.75f, 15.45f)
                quadTo(5.75f, 12.75f, 8.62f, 12.75f)
                quadTo(11.51f, 12.75f, 12.5f, 15.45f)
                quadTo(12.6f, 15.72f, 12.49f, 15.98f)
                quadTo(12.39f, 16.24f, 12.15f, 16.37f)
                close()
                moveTo(11.25f, 9.38f)
                quadTo(11.25f, 12f, 8.62f, 12f)
                quadTo(6f, 12f, 6f, 9.38f)
                quadTo(6f, 6.75f, 8.62f, 6.75f)
                quadTo(11.25f, 6.75f, 11.25f, 9.38f)
                close()
                moveTo(15f, 11.25f)
                lineTo(18.75f, 11.25f)
                quadTo(19.06f, 11.25f, 19.28f, 11.47f)
                quadTo(19.5f, 11.69f, 19.5f, 12f)
                quadTo(19.5f, 12.31f, 19.28f, 12.53f)
                quadTo(19.06f, 12.75f, 18.75f, 12.75f)
                lineTo(15f, 12.75f)
                quadTo(14.69f, 12.75f, 14.47f, 12.53f)
                quadTo(14.25f, 12.31f, 14.25f, 12f)
                quadTo(14.25f, 11.69f, 14.47f, 11.47f)
                quadTo(14.69f, 11.25f, 15f, 11.25f)
                close()
                moveTo(15f, 14.25f)
                lineTo(18.75f, 14.25f)
                quadTo(19.06f, 14.25f, 19.28f, 14.47f)
                quadTo(19.5f, 14.69f, 19.5f, 15f)
                quadTo(19.5f, 15.31f, 19.28f, 15.53f)
                quadTo(19.06f, 15.75f, 18.75f, 15.75f)
                lineTo(15f, 15.75f)
                quadTo(14.69f, 15.75f, 14.47f, 15.53f)
                quadTo(14.25f, 15.31f, 14.25f, 15f)
                quadTo(14.25f, 14.69f, 14.47f, 14.47f)
                quadTo(14.69f, 14.25f, 15f, 14.25f)
                close()
                moveTo(15f, 8.25f)
                lineTo(18.75f, 8.25f)
                quadTo(19.06f, 8.25f, 19.28f, 8.47f)
                quadTo(19.5f, 8.69f, 19.5f, 9f)
                quadTo(19.5f, 9.31f, 19.28f, 9.53f)
                quadTo(19.06f, 9.75f, 18.75f, 9.75f)
                lineTo(15f, 9.75f)
                quadTo(14.69f, 9.75f, 14.47f, 9.53f)
                quadTo(14.25f, 9.31f, 14.25f, 9f)
                quadTo(14.25f, 8.69f, 14.47f, 8.47f)
                quadTo(14.69f, 8.25f, 15f, 8.25f)
                close()
                moveTo(10.79f, 15.35f)
                quadTo(10.09f, 14.25f, 8.62f, 14.25f)
                quadTo(7.16f, 14.25f, 6.46f, 15.35f)
                quadTo(7.49f, 15.75f, 8.62f, 15.75f)
                quadTo(9.76f, 15.75f, 10.79f, 15.35f)
                close()
                moveTo(9.75f, 9.38f)
                quadTo(9.75f, 8.25f, 8.62f, 8.25f)
                quadTo(7.5f, 8.25f, 7.5f, 9.38f)
                quadTo(7.5f, 10.5f, 8.62f, 10.5f)
                quadTo(9.75f, 10.5f, 9.75f, 9.38f)
                close()
            }
        }.build()
}
