// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Inbox: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "Inbox",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(1.5f, 13.84f)
                quadTo(1.5f, 13.73f, 1.51f, 13.62f)
                quadTo(1.5f, 13.56f, 1.5f, 13.5f)
                quadTo(1.5f, 13.32f, 1.58f, 13.16f)
                quadTo(1.6f, 13.06f, 1.63f, 12.96f)
                lineTo(4.04f, 5.12f)
                quadTo(4.7f, 3f, 6.91f, 3f)
                lineTo(17.09f, 3f)
                quadTo(19.3f, 3f, 19.96f, 5.12f)
                lineTo(22.37f, 12.96f)
                quadTo(22.4f, 13.06f, 22.42f, 13.16f)
                quadTo(22.5f, 13.32f, 22.5f, 13.5f)
                quadTo(22.5f, 13.56f, 22.49f, 13.62f)
                quadTo(22.5f, 13.73f, 22.5f, 13.84f)
                lineTo(22.5f, 18f)
                quadTo(22.5f, 21f, 19.5f, 21f)
                lineTo(4.5f, 21f)
                quadTo(1.5f, 21f, 1.5f, 18f)
                lineTo(1.5f, 13.84f)
                close()
                moveTo(20.73f, 12.75f)
                lineTo(18.52f, 5.56f)
                quadTo(18.2f, 4.5f, 17.09f, 4.5f)
                lineTo(6.91f, 4.5f)
                quadTo(5.8f, 4.5f, 5.48f, 5.56f)
                lineTo(3.27f, 12.75f)
                lineTo(6.11f, 12.75f)
                quadTo(7.96f, 12.75f, 8.79f, 14.41f)
                lineTo(9.05f, 14.92f)
                quadTo(9.46f, 15.75f, 10.39f, 15.75f)
                lineTo(13.61f, 15.75f)
                quadTo(14.54f, 15.75f, 14.95f, 14.92f)
                lineTo(15.21f, 14.41f)
                quadTo(16.04f, 12.75f, 17.89f, 12.75f)
                lineTo(20.73f, 12.75f)
                close()
                moveTo(3f, 14.25f)
                lineTo(3f, 18f)
                quadTo(3f, 19.5f, 4.5f, 19.5f)
                lineTo(19.5f, 19.5f)
                quadTo(21f, 19.5f, 21f, 18f)
                lineTo(21f, 14.25f)
                lineTo(17.89f, 14.25f)
                quadTo(16.96f, 14.25f, 16.55f, 15.08f)
                lineTo(16.29f, 15.59f)
                quadTo(15.46f, 17.25f, 13.61f, 17.25f)
                lineTo(10.39f, 17.25f)
                quadTo(8.54f, 17.25f, 7.71f, 15.59f)
                lineTo(7.45f, 15.08f)
                quadTo(7.04f, 14.25f, 6.11f, 14.25f)
                lineTo(3f, 14.25f)
                close()
            }
        }.build()
}
