// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val InboxStack: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "InboxStack",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(4.5f, 21f)
                quadTo(1.5f, 21f, 1.5f, 18f)
                lineTo(1.5f, 15.38f)
                quadTo(1.5f, 14.41f, 2f, 13.94f)
                quadTo(1.5f, 13.22f, 1.5f, 12f)
                lineTo(1.5f, 9.83f)
                quadTo(1.5f, 9.29f, 1.69f, 8.78f)
                quadTo(1.71f, 8.72f, 1.74f, 8.66f)
                quadTo(1.92f, 8.23f, 2.22f, 7.88f)
                lineTo(5.51f, 4.05f)
                quadTo(6.41f, 3f, 7.79f, 3f)
                lineTo(16.21f, 3f)
                quadTo(17.59f, 3f, 18.49f, 4.05f)
                lineTo(21.78f, 7.88f)
                quadTo(22.08f, 8.23f, 22.26f, 8.66f)
                quadTo(22.29f, 8.72f, 22.31f, 8.78f)
                quadTo(22.5f, 9.29f, 22.5f, 9.83f)
                lineTo(22.5f, 12f)
                quadTo(22.5f, 13.22f, 22f, 13.94f)
                quadTo(22.5f, 14.41f, 22.5f, 15.38f)
                lineTo(22.5f, 18f)
                quadTo(22.5f, 21f, 19.5f, 21f)
                close()
                moveTo(20.12f, 8.25f)
                lineTo(17.36f, 5.02f)
                quadTo(16.91f, 4.5f, 16.21f, 4.5f)
                lineTo(7.79f, 4.5f)
                quadTo(7.09f, 4.5f, 6.65f, 5.02f)
                lineTo(3.88f, 8.25f)
                lineTo(7.05f, 8.25f)
                quadTo(8.65f, 8.25f, 9.54f, 9.59f)
                lineTo(9.71f, 9.83f)
                quadTo(10.15f, 10.5f, 10.95f, 10.5f)
                lineTo(13.05f, 10.5f)
                quadTo(13.85f, 10.5f, 14.29f, 9.83f)
                lineTo(14.46f, 9.59f)
                quadTo(15.35f, 8.25f, 16.95f, 8.25f)
                lineTo(20.12f, 8.25f)
                close()
                moveTo(4.5f, 19.5f)
                lineTo(19.5f, 19.5f)
                quadTo(21f, 19.5f, 21f, 18f)
                lineTo(21f, 15.38f)
                quadTo(21f, 15f, 20.62f, 15f)
                lineTo(16.54f, 15f)
                lineTo(15.55f, 16.59f)
                quadTo(14.67f, 18f, 13f, 18f)
                lineTo(11f, 18f)
                quadTo(9.33f, 18f, 8.45f, 16.59f)
                lineTo(7.46f, 15f)
                lineTo(3.38f, 15f)
                quadTo(3f, 15f, 3f, 15.38f)
                lineTo(3f, 18f)
                quadTo(3f, 19.5f, 4.5f, 19.5f)
                close()
                moveTo(3f, 9.75f)
                quadTo(3f, 9.79f, 3f, 9.83f)
                lineTo(3f, 12f)
                quadTo(3f, 13.5f, 4.5f, 13.5f)
                lineTo(7.82f, 13.5f)
                quadTo(7.87f, 13.5f, 7.92f, 13.5f)
                lineTo(16.09f, 13.5f)
                quadTo(16.13f, 13.5f, 16.18f, 13.5f)
                lineTo(19.5f, 13.5f)
                quadTo(21f, 13.5f, 21f, 12f)
                lineTo(21f, 9.83f)
                quadTo(21f, 9.79f, 21f, 9.75f)
                lineTo(16.95f, 9.75f)
                quadTo(16.15f, 9.75f, 15.71f, 10.42f)
                lineTo(15.54f, 10.66f)
                quadTo(14.65f, 12f, 13.05f, 12f)
                lineTo(10.95f, 12f)
                quadTo(9.35f, 12f, 8.46f, 10.66f)
                lineTo(8.29f, 10.42f)
                quadTo(7.85f, 9.75f, 7.05f, 9.75f)
                lineTo(3f, 9.75f)
                close()
                moveTo(14.77f, 15f)
                lineTo(9.23f, 15f)
                lineTo(9.72f, 15.79f)
                quadTo(10.17f, 16.5f, 11f, 16.5f)
                lineTo(13f, 16.5f)
                quadTo(13.83f, 16.5f, 14.28f, 15.79f)
                lineTo(14.77f, 15f)
                close()
            }
        }.build()
}
