// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val InformationCircle: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "InformationCircle",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(21.75f, 12f)
                quadTo(21.75f, 16.04f, 18.89f, 18.89f)
                quadTo(16.04f, 21.75f, 12f, 21.75f)
                quadTo(7.96f, 21.75f, 5.11f, 18.89f)
                quadTo(2.25f, 16.04f, 2.25f, 12f)
                quadTo(2.25f, 7.96f, 5.11f, 5.11f)
                quadTo(7.96f, 2.25f, 12f, 2.25f)
                quadTo(16.04f, 2.25f, 18.89f, 5.11f)
                quadTo(21.75f, 7.96f, 21.75f, 12f)
                close()
                moveTo(20.25f, 12f)
                quadTo(20.25f, 8.58f, 17.83f, 6.17f)
                quadTo(15.42f, 3.75f, 12f, 3.75f)
                quadTo(8.58f, 3.75f, 6.17f, 6.17f)
                quadTo(3.75f, 8.58f, 3.75f, 12f)
                quadTo(3.75f, 15.42f, 6.17f, 17.83f)
                quadTo(8.58f, 20.25f, 12f, 20.25f)
                quadTo(15.42f, 20.25f, 17.83f, 17.83f)
                quadTo(20.25f, 15.42f, 20.25f, 12f)
                close()
                moveTo(10.92f, 10.58f)
                lineTo(10.96f, 10.56f)
                quadTo(11.81f, 10.13f, 12.56f, 10.73f)
                quadTo(13.31f, 11.33f, 13.08f, 12.26f)
                lineTo(12.37f, 15.1f)
                lineTo(12.37f, 15.1f)
                lineTo(12.41f, 15.08f)
                quadTo(12.69f, 14.94f, 12.98f, 15.04f)
                quadTo(13.28f, 15.13f, 13.42f, 15.41f)
                quadTo(13.56f, 15.69f, 13.46f, 15.98f)
                quadTo(13.37f, 16.28f, 13.09f, 16.42f)
                lineTo(13.04f, 16.44f)
                quadTo(12.19f, 16.87f, 11.44f, 16.27f)
                quadTo(10.69f, 15.67f, 10.92f, 14.74f)
                lineTo(11.63f, 11.9f)
                lineTo(11.62f, 11.9f)
                lineTo(11.58f, 11.92f)
                quadTo(11.3f, 12.06f, 11.01f, 11.96f)
                quadTo(10.71f, 11.86f, 10.58f, 11.58f)
                quadTo(10.44f, 11.3f, 10.54f, 11.01f)
                quadTo(10.64f, 10.71f, 10.92f, 10.58f)
                close()
                moveTo(12f, 7.5f)
                lineTo(12.01f, 7.5f)
                quadTo(12.32f, 7.5f, 12.54f, 7.72f)
                quadTo(12.76f, 7.94f, 12.76f, 8.25f)
                lineTo(12.76f, 8.26f)
                quadTo(12.76f, 8.57f, 12.54f, 8.79f)
                quadTo(12.32f, 9.01f, 12.01f, 9.01f)
                lineTo(12f, 9.01f)
                quadTo(11.69f, 9.01f, 11.47f, 8.79f)
                quadTo(11.25f, 8.57f, 11.25f, 8.26f)
                lineTo(11.25f, 8.25f)
                quadTo(11.25f, 7.94f, 11.47f, 7.72f)
                quadTo(11.69f, 7.5f, 12f, 7.5f)
                close()
            }
        }.build()
}
