// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Language: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "Language",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(9.82f, 20.68f)
                lineTo(15.07f, 9.43f)
                quadTo(15.2f, 9.15f, 15.49f, 9.04f)
                quadTo(15.79f, 8.94f, 16.07f, 9.07f)
                quadTo(16.31f, 9.19f, 16.43f, 9.43f)
                lineTo(21.68f, 20.68f)
                quadTo(21.81f, 20.96f, 21.7f, 21.26f)
                quadTo(21.6f, 21.55f, 21.32f, 21.68f)
                quadTo(21.04f, 21.81f, 20.74f, 21.7f)
                quadTo(20.45f, 21.6f, 20.32f, 21.32f)
                lineTo(19.12f, 18.75f)
                lineTo(12.38f, 18.75f)
                lineTo(11.18f, 21.32f)
                quadTo(11.05f, 21.6f, 10.76f, 21.7f)
                quadTo(10.46f, 21.81f, 10.18f, 21.68f)
                quadTo(9.9f, 21.55f, 9.79f, 21.26f)
                quadTo(9.69f, 20.96f, 9.82f, 20.68f)
                close()
                moveTo(2.91f, 4.88f)
                quadTo(5.57f, 4.54f, 8.25f, 4.5f)
                lineTo(8.25f, 3f)
                quadTo(8.25f, 2.69f, 8.47f, 2.47f)
                quadTo(8.69f, 2.25f, 9f, 2.25f)
                quadTo(9.31f, 2.25f, 9.53f, 2.47f)
                quadTo(9.75f, 2.69f, 9.75f, 3f)
                lineTo(9.75f, 4.51f)
                quadTo(11.05f, 4.53f, 12.34f, 4.61f)
                quadTo(12.38f, 4.61f, 12.41f, 4.62f)
                quadTo(13.76f, 4.71f, 15.09f, 4.88f)
                quadTo(15.4f, 4.92f, 15.59f, 5.16f)
                quadTo(15.78f, 5.41f, 15.74f, 5.71f)
                quadTo(15.71f, 6.02f, 15.46f, 6.21f)
                quadTo(15.21f, 6.4f, 14.91f, 6.37f)
                quadTo(13.91f, 6.24f, 12.92f, 6.16f)
                quadTo(12.01f, 9.78f, 10.01f, 12.56f)
                quadTo(10.46f, 13.09f, 10.95f, 13.59f)
                quadTo(11.16f, 13.81f, 11.16f, 14.12f)
                quadTo(11.16f, 14.43f, 10.94f, 14.65f)
                quadTo(10.71f, 14.87f, 10.4f, 14.87f)
                quadTo(10.09f, 14.86f, 9.88f, 14.64f)
                quadTo(9.45f, 14.21f, 9.06f, 13.76f)
                quadTo(6.77f, 16.4f, 3.34f, 18.17f)
                quadTo(3.07f, 18.31f, 2.77f, 18.22f)
                quadTo(2.48f, 18.12f, 2.33f, 17.85f)
                quadTo(2.19f, 17.57f, 2.29f, 17.27f)
                quadTo(2.38f, 16.98f, 2.66f, 16.84f)
                quadTo(5.95f, 15.13f, 8.1f, 12.56f)
                quadTo(6.76f, 10.73f, 5.89f, 8.6f)
                quadTo(5.77f, 8.31f, 5.89f, 8.02f)
                quadTo(6.01f, 7.74f, 6.3f, 7.62f)
                quadTo(6.59f, 7.5f, 6.87f, 7.62f)
                quadTo(7.16f, 7.74f, 7.28f, 8.03f)
                quadTo(8f, 9.78f, 9.05f, 11.3f)
                quadTo(10.62f, 8.98f, 11.39f, 6.06f)
                quadTo(10.21f, 6f, 9f, 6f)
                quadTo(6.04f, 6f, 3.09f, 6.37f)
                quadTo(2.78f, 6.4f, 2.54f, 6.21f)
                quadTo(2.29f, 6.02f, 2.26f, 5.71f)
                quadTo(2.22f, 5.41f, 2.41f, 5.16f)
                quadTo(2.6f, 4.92f, 2.91f, 4.88f)
                close()
                moveTo(18.42f, 17.25f)
                lineTo(15.75f, 11.52f)
                lineTo(13.08f, 17.25f)
                lineTo(18.42f, 17.25f)
                close()
            }
        }.build()
}
