// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Link: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "Link",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(18.14f, 11.16f)
                lineTo(19.9f, 9.4f)
                quadTo(21f, 8.3f, 21f, 6.75f)
                quadTo(21f, 5.2f, 19.9f, 4.1f)
                quadTo(18.8f, 3f, 17.25f, 3f)
                quadTo(15.7f, 3f, 14.6f, 4.1f)
                lineTo(10.1f, 8.6f)
                quadTo(8.72f, 9.97f, 9.05f, 11.88f)
                quadTo(9.38f, 13.8f, 11.13f, 14.63f)
                quadTo(11.41f, 14.77f, 11.52f, 15.06f)
                quadTo(11.62f, 15.36f, 11.49f, 15.63f)
                quadTo(11.35f, 15.91f, 11.06f, 16.02f)
                quadTo(10.77f, 16.12f, 10.49f, 15.99f)
                quadTo(8.03f, 14.82f, 7.57f, 12.14f)
                quadTo(7.12f, 9.46f, 9.04f, 7.54f)
                lineTo(13.54f, 3.04f)
                quadTo(15.07f, 1.5f, 17.25f, 1.5f)
                quadTo(19.43f, 1.5f, 20.96f, 3.04f)
                quadTo(22.5f, 4.58f, 22.5f, 6.75f)
                quadTo(22.5f, 8.93f, 20.96f, 10.46f)
                lineTo(19.2f, 12.22f)
                quadTo(18.99f, 12.44f, 18.68f, 12.44f)
                quadTo(18.36f, 12.44f, 18.14f, 12.22f)
                quadTo(17.93f, 12f, 17.93f, 11.69f)
                quadTo(17.93f, 11.38f, 18.14f, 11.16f)
                close()
                moveTo(13.51f, 8.01f)
                quadTo(15.97f, 9.18f, 16.43f, 11.86f)
                quadTo(16.89f, 14.54f, 14.96f, 16.46f)
                lineTo(10.46f, 20.96f)
                quadTo(8.93f, 22.5f, 6.75f, 22.5f)
                quadTo(4.58f, 22.5f, 3.04f, 20.96f)
                quadTo(1.5f, 19.43f, 1.5f, 17.25f)
                quadTo(1.5f, 15.07f, 3.04f, 13.54f)
                lineTo(4.79f, 11.78f)
                quadTo(5.01f, 11.56f, 5.33f, 11.56f)
                quadTo(5.64f, 11.56f, 5.86f, 11.78f)
                quadTo(6.08f, 12f, 6.08f, 12.31f)
                quadTo(6.08f, 12.62f, 5.86f, 12.84f)
                lineTo(4.1f, 14.6f)
                quadTo(3f, 15.7f, 3f, 17.25f)
                quadTo(3f, 18.8f, 4.1f, 19.9f)
                quadTo(5.2f, 21f, 6.75f, 21f)
                quadTo(8.3f, 21f, 9.4f, 19.9f)
                lineTo(13.9f, 15.4f)
                quadTo(15.28f, 14.03f, 14.95f, 12.12f)
                quadTo(14.62f, 10.2f, 12.87f, 9.37f)
                quadTo(12.59f, 9.23f, 12.48f, 8.94f)
                quadTo(12.38f, 8.64f, 12.51f, 8.37f)
                quadTo(12.65f, 8.09f, 12.94f, 7.98f)
                quadTo(13.23f, 7.88f, 13.51f, 8.01f)
                close()
            }
        }.build()
}
