// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val LinkSlash: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "LinkSlash",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(13.51f, 8f)
                quadTo(15.61f, 9.01f, 16.27f, 11.25f)
                quadTo(16.85f, 13.19f, 16.01f, 14.95f)
                lineTo(21.52f, 20.46f)
                quadTo(21.74f, 20.68f, 21.74f, 20.99f)
                quadTo(21.74f, 21.3f, 21.52f, 21.52f)
                quadTo(21.3f, 21.74f, 20.99f, 21.74f)
                quadTo(20.68f, 21.74f, 20.46f, 21.52f)
                lineTo(14.58f, 15.64f)
                quadTo(14.55f, 15.61f, 14.51f, 15.57f)
                lineTo(8.4f, 9.46f)
                quadTo(8.39f, 9.45f, 8.38f, 9.44f)
                quadTo(8.36f, 9.43f, 8.35f, 9.41f)
                lineTo(2.46f, 3.52f)
                quadTo(2.24f, 3.3f, 2.24f, 2.99f)
                quadTo(2.24f, 2.68f, 2.46f, 2.46f)
                quadTo(2.68f, 2.24f, 2.99f, 2.24f)
                quadTo(3.3f, 2.24f, 3.52f, 2.46f)
                lineTo(8.82f, 7.76f)
                quadTo(8.92f, 7.64f, 9.03f, 7.53f)
                lineTo(13.53f, 3.03f)
                quadTo(15.07f, 1.49f, 17.24f, 1.49f)
                quadTo(19.42f, 1.49f, 20.95f, 3.03f)
                quadTo(22.49f, 4.57f, 22.49f, 6.74f)
                quadTo(22.49f, 8.92f, 20.95f, 10.45f)
                lineTo(19.2f, 12.21f)
                quadTo(18.98f, 12.43f, 18.67f, 12.43f)
                quadTo(18.36f, 12.43f, 18.14f, 12.21f)
                quadTo(17.92f, 11.99f, 17.92f, 11.68f)
                quadTo(17.92f, 11.37f, 18.14f, 11.15f)
                lineTo(19.89f, 9.39f)
                quadTo(20.99f, 8.29f, 20.99f, 6.74f)
                quadTo(20.99f, 5.19f, 19.89f, 4.09f)
                quadTo(18.8f, 2.99f, 17.24f, 2.99f)
                quadTo(15.69f, 2.99f, 14.59f, 4.09f)
                lineTo(10.09f, 8.59f)
                quadTo(9.98f, 8.7f, 9.88f, 8.82f)
                lineTo(14.85f, 13.79f)
                quadTo(15.16f, 12.78f, 14.84f, 11.67f)
                quadTo(14.36f, 10.08f, 12.86f, 9.36f)
                quadTo(12.58f, 9.22f, 12.47f, 8.93f)
                quadTo(12.37f, 8.64f, 12.5f, 8.36f)
                quadTo(12.64f, 8.08f, 12.93f, 7.97f)
                quadTo(13.22f, 7.87f, 13.51f, 8f)
                close()
                moveTo(5.85f, 12.83f)
                lineTo(4.09f, 14.59f)
                quadTo(1.44f, 17.24f, 4.09f, 19.89f)
                quadTo(5.19f, 20.99f, 6.74f, 20.99f)
                quadTo(8.29f, 20.99f, 9.39f, 19.89f)
                lineTo(12.52f, 16.77f)
                quadTo(12.74f, 16.55f, 13.05f, 16.55f)
                quadTo(13.36f, 16.55f, 13.58f, 16.77f)
                quadTo(13.8f, 16.98f, 13.8f, 17.3f)
                quadTo(13.8f, 17.61f, 13.58f, 17.83f)
                lineTo(10.45f, 20.95f)
                quadTo(8.92f, 22.49f, 6.74f, 22.49f)
                quadTo(4.57f, 22.49f, 3.03f, 20.95f)
                quadTo(1.49f, 19.42f, 1.49f, 17.24f)
                quadTo(1.49f, 15.07f, 3.03f, 13.53f)
                lineTo(4.79f, 11.77f)
                quadTo(5f, 11.55f, 5.32f, 11.55f)
                quadTo(5.63f, 11.55f, 5.85f, 11.77f)
                quadTo(6.07f, 11.99f, 6.07f, 12.3f)
                quadTo(6.07f, 12.61f, 5.85f, 12.83f)
                close()
                moveTo(10.48f, 15.98f)
                quadTo(9.66f, 15.59f, 9.03f, 14.95f)
                quadTo(8.19f, 14.11f, 7.79f, 12.99f)
                quadTo(7.69f, 12.7f, 7.82f, 12.42f)
                quadTo(7.96f, 12.14f, 8.25f, 12.03f)
                quadTo(8.54f, 11.93f, 8.82f, 12.06f)
                quadTo(9.1f, 12.2f, 9.21f, 12.49f)
                quadTo(9.49f, 13.29f, 10.09f, 13.89f)
                quadTo(10.54f, 14.35f, 11.13f, 14.63f)
                quadTo(11.41f, 14.76f, 11.51f, 15.05f)
                quadTo(11.61f, 15.35f, 11.48f, 15.63f)
                quadTo(11.34f, 15.91f, 11.05f, 16.01f)
                quadTo(10.76f, 16.11f, 10.48f, 15.98f)
                close()
            }
        }.build()
}
