// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val MagnifyingGlass: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "MagnifyingGlass",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(20.47f, 21.53f)
                lineTo(15.78f, 16.84f)
                quadTo(13.54f, 18.75f, 10.5f, 18.75f)
                quadTo(7.08f, 18.75f, 4.67f, 16.33f)
                quadTo(2.25f, 13.92f, 2.25f, 10.5f)
                quadTo(2.25f, 7.08f, 4.67f, 4.67f)
                quadTo(7.08f, 2.25f, 10.5f, 2.25f)
                quadTo(13.92f, 2.25f, 16.33f, 4.67f)
                quadTo(18.75f, 7.08f, 18.75f, 10.5f)
                quadTo(18.75f, 13.54f, 16.84f, 15.78f)
                lineTo(21.53f, 20.47f)
                quadTo(21.75f, 20.69f, 21.75f, 21f)
                quadTo(21.75f, 21.31f, 21.53f, 21.53f)
                quadTo(21.31f, 21.75f, 21f, 21.75f)
                quadTo(20.69f, 21.75f, 20.47f, 21.53f)
                close()
                moveTo(15.27f, 15.27f)
                quadTo(17.25f, 13.3f, 17.25f, 10.5f)
                quadTo(17.25f, 7.7f, 15.27f, 5.73f)
                quadTo(13.3f, 3.75f, 10.5f, 3.75f)
                quadTo(7.7f, 3.75f, 5.73f, 5.73f)
                quadTo(3.75f, 7.7f, 3.75f, 10.5f)
                quadTo(3.75f, 13.3f, 5.73f, 15.27f)
                quadTo(7.7f, 17.25f, 10.5f, 17.25f)
                quadTo(13.3f, 17.25f, 15.27f, 15.27f)
                close()
            }
        }.build()
}
