// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Map: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "Map",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(15.88f, 21.4f)
                quadTo(15.86f, 21.41f, 15.84f, 21.42f)
                quadTo(15f, 21.84f, 14.16f, 21.42f)
                lineTo(9.17f, 18.92f)
                quadTo(9f, 18.84f, 8.83f, 18.92f)
                lineTo(4.96f, 20.86f)
                quadTo(4.03f, 21.32f, 3.14f, 20.77f)
                quadTo(2.25f, 20.23f, 2.25f, 19.18f)
                lineTo(2.25f, 6.7f)
                quadTo(2.25f, 5.54f, 3.29f, 5.02f)
                lineTo(8.16f, 2.58f)
                quadTo(9f, 2.16f, 9.84f, 2.58f)
                lineTo(14.83f, 5.08f)
                quadTo(15f, 5.16f, 15.17f, 5.08f)
                lineTo(19.04f, 3.14f)
                quadTo(19.97f, 2.68f, 20.86f, 3.23f)
                quadTo(21.75f, 3.77f, 21.75f, 4.82f)
                lineTo(21.75f, 17.3f)
                quadTo(21.75f, 18.46f, 20.71f, 18.98f)
                lineTo(15.88f, 21.4f)
                close()
                moveTo(15.17f, 20.08f)
                lineTo(20.04f, 17.64f)
                quadTo(20.25f, 17.54f, 20.25f, 17.3f)
                lineTo(20.25f, 4.82f)
                quadTo(20.25f, 4.61f, 20.07f, 4.5f)
                quadTo(19.89f, 4.39f, 19.71f, 4.49f)
                lineTo(15.84f, 6.42f)
                quadTo(15f, 6.84f, 14.16f, 6.42f)
                lineTo(9.17f, 3.92f)
                quadTo(9f, 3.84f, 8.83f, 3.92f)
                lineTo(3.96f, 6.36f)
                quadTo(3.75f, 6.46f, 3.75f, 6.7f)
                lineTo(3.75f, 19.18f)
                quadTo(3.75f, 19.39f, 3.93f, 19.5f)
                quadTo(4.11f, 19.61f, 4.29f, 19.52f)
                lineTo(8.16f, 17.58f)
                quadTo(9f, 17.16f, 9.84f, 17.58f)
                lineTo(14.83f, 20.08f)
                quadTo(14.99f, 20.16f, 15.15f, 20.09f)
                quadTo(15.16f, 20.08f, 15.17f, 20.08f)
                close()
                moveTo(15.75f, 9f)
                lineTo(15.75f, 17.25f)
                quadTo(15.75f, 17.56f, 15.53f, 17.78f)
                quadTo(15.31f, 18f, 15f, 18f)
                quadTo(14.69f, 18f, 14.47f, 17.78f)
                quadTo(14.25f, 17.56f, 14.25f, 17.25f)
                lineTo(14.25f, 9f)
                quadTo(14.25f, 8.69f, 14.47f, 8.47f)
                quadTo(14.69f, 8.25f, 15f, 8.25f)
                quadTo(15.31f, 8.25f, 15.53f, 8.47f)
                quadTo(15.75f, 8.69f, 15.75f, 9f)
                close()
                moveTo(9.75f, 6.75f)
                lineTo(9.75f, 15f)
                quadTo(9.75f, 15.31f, 9.53f, 15.53f)
                quadTo(9.31f, 15.75f, 9f, 15.75f)
                quadTo(8.69f, 15.75f, 8.47f, 15.53f)
                quadTo(8.25f, 15.31f, 8.25f, 15f)
                lineTo(8.25f, 6.75f)
                quadTo(8.25f, 6.44f, 8.47f, 6.22f)
                quadTo(8.69f, 6f, 9f, 6f)
                quadTo(9.31f, 6f, 9.53f, 6.22f)
                quadTo(9.75f, 6.44f, 9.75f, 6.75f)
                close()
            }
        }.build()
}
