// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Megaphone: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "Megaphone",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(20.91f, 13.33f)
                quadTo(20.69f, 15.99f, 19.91f, 18.55f)
                quadTo(19.9f, 18.59f, 19.88f, 18.63f)
                quadTo(19.71f, 19.18f, 19.5f, 19.76f)
                quadTo(19.39f, 20.05f, 19.11f, 20.18f)
                quadTo(18.83f, 20.31f, 18.54f, 20.2f)
                quadTo(18.25f, 20.1f, 18.11f, 19.82f)
                quadTo(17.98f, 19.54f, 18.09f, 19.24f)
                quadTo(18.18f, 19f, 18.26f, 18.76f)
                quadTo(14.98f, 17.19f, 11.38f, 16.71f)
                quadTo(11.65f, 17.52f, 12.01f, 18.32f)
                quadTo(12.73f, 19.92f, 11.24f, 20.78f)
                lineTo(10.58f, 21.16f)
                quadTo(9.88f, 21.57f, 9.12f, 21.34f)
                quadTo(8.34f, 21.11f, 8f, 20.37f)
                quadTo(7.12f, 18.46f, 6.62f, 16.43f)
                quadTo(5f, 16.18f, 3.79f, 14.96f)
                quadTo(2.25f, 13.43f, 2.25f, 11.25f)
                quadTo(2.25f, 9.07f, 3.79f, 7.54f)
                quadTo(5.33f, 6f, 7.5f, 6f)
                lineTo(8.25f, 6f)
                quadTo(9.25f, 6f, 10.22f, 5.92f)
                quadTo(10.27f, 5.91f, 10.33f, 5.91f)
                quadTo(14.5f, 5.54f, 18.26f, 3.74f)
                quadTo(18.18f, 3.5f, 18.09f, 3.26f)
                quadTo(17.98f, 2.97f, 18.11f, 2.68f)
                quadTo(18.25f, 2.4f, 18.54f, 2.3f)
                quadTo(18.83f, 2.19f, 19.11f, 2.32f)
                quadTo(19.39f, 2.45f, 19.5f, 2.74f)
                quadTo(19.7f, 3.3f, 19.88f, 3.87f)
                quadTo(19.9f, 3.91f, 19.91f, 3.95f)
                quadTo(20.69f, 6.51f, 20.91f, 9.17f)
                quadTo(21.75f, 10.02f, 21.75f, 11.25f)
                quadTo(21.75f, 12.48f, 20.91f, 13.33f)
                close()
                moveTo(18.7f, 5.19f)
                quadTo(15.01f, 6.92f, 10.94f, 7.36f)
                quadTo(10.5f, 9.27f, 10.5f, 11.25f)
                quadTo(10.5f, 13.23f, 10.94f, 15.14f)
                quadTo(15.01f, 15.58f, 18.7f, 17.31f)
                quadTo(19.28f, 15.16f, 19.44f, 12.94f)
                quadTo(19.44f, 12.93f, 19.44f, 12.92f)
                quadTo(19.56f, 11.25f, 19.44f, 9.58f)
                quadTo(19.44f, 9.57f, 19.44f, 9.56f)
                quadTo(19.28f, 7.34f, 18.7f, 5.19f)
                close()
                moveTo(9.38f, 7.47f)
                quadTo(8.82f, 7.5f, 8.25f, 7.5f)
                lineTo(7.5f, 7.5f)
                quadTo(3.75f, 7.5f, 3.75f, 11.25f)
                quadTo(3.75f, 15f, 7.5f, 15f)
                lineTo(8.25f, 15f)
                quadTo(8.82f, 15f, 9.38f, 15.03f)
                quadTo(9f, 13.16f, 9f, 11.25f)
                quadTo(9f, 9.33f, 9.38f, 7.47f)
                close()
                moveTo(9.76f, 16.55f)
                quadTo(9.01f, 16.5f, 8.25f, 16.5f)
                lineTo(8.19f, 16.5f)
                quadTo(8.63f, 18.17f, 9.36f, 19.74f)
                quadTo(9.42f, 19.86f, 9.55f, 19.9f)
                quadTo(9.69f, 19.94f, 9.83f, 19.86f)
                lineTo(10.49f, 19.48f)
                quadTo(10.81f, 19.3f, 10.64f, 18.93f)
                quadTo(10.12f, 17.77f, 9.76f, 16.55f)
                close()
            }
        }.build()
}
