// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val PaintBrush: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "PaintBrush",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(7.44f, 13.49f)
                quadTo(8.01f, 12.03f, 8.86f, 10.69f)
                quadTo(8.87f, 10.67f, 8.89f, 10.64f)
                quadTo(10.79f, 7.66f, 13.73f, 5.7f)
                lineTo(19.54f, 1.82f)
                quadTo(20.84f, 0.95f, 21.95f, 2.06f)
                quadTo(23.05f, 3.16f, 22.18f, 4.46f)
                lineTo(18.3f, 10.27f)
                quadTo(16.35f, 13.21f, 13.37f, 15.1f)
                quadTo(13.33f, 15.13f, 13.29f, 15.15f)
                quadTo(11.93f, 16.01f, 10.44f, 16.59f)
                quadTo(10.5f, 16.91f, 10.5f, 17.25f)
                quadTo(10.5f, 21.28f, 6.61f, 22.32f)
                quadTo(2.71f, 23.36f, 0.7f, 19.87f)
                quadTo(0.59f, 19.67f, 0.6f, 19.45f)
                quadTo(0.62f, 19.14f, 0.86f, 18.93f)
                quadTo(1.09f, 18.73f, 1.4f, 18.75f)
                quadTo(2.05f, 18.79f, 2.52f, 18.34f)
                quadTo(3f, 17.9f, 3f, 17.25f)
                quadTo(3f, 14.16f, 6.03f, 13.57f)
                quadTo(6.79f, 13.42f, 7.44f, 13.49f)
                close()
                moveTo(10.59f, 10.8f)
                quadTo(12.24f, 11.76f, 13.2f, 13.41f)
                quadTo(15.49f, 11.79f, 17.06f, 9.44f)
                lineTo(20.93f, 3.62f)
                quadTo(21.12f, 3.35f, 20.89f, 3.12f)
                quadTo(20.65f, 2.88f, 20.38f, 3.07f)
                lineTo(14.56f, 6.94f)
                quadTo(12.21f, 8.51f, 10.59f, 10.8f)
                close()
                moveTo(8.83f, 16.39f)
                quadTo(8.49f, 15.57f, 7.9f, 15.23f)
                quadTo(7.77f, 15.23f, 7.63f, 15.19f)
                quadTo(7.47f, 15.13f, 7.36f, 15.02f)
                quadTo(6.89f, 14.93f, 6.32f, 15.04f)
                quadTo(4.5f, 15.4f, 4.5f, 17.25f)
                quadTo(4.5f, 18.55f, 3.55f, 19.44f)
                quadTo(3.14f, 19.82f, 2.66f, 20.03f)
                quadTo(4.02f, 21.46f, 6.22f, 20.87f)
                quadTo(9f, 20.13f, 9f, 17.25f)
                quadTo(9f, 16.82f, 8.84f, 16.42f)
                quadTo(8.84f, 16.41f, 8.83f, 16.39f)
                close()
                moveTo(11.93f, 14.22f)
                quadTo(11.15f, 12.85f, 9.78f, 12.07f)
                quadTo(9.25f, 13f, 8.85f, 14f)
                quadTo(9.47f, 14.42f, 9.91f, 15.19f)
                quadTo(10.96f, 14.78f, 11.93f, 14.22f)
                close()
            }
        }.build()
}
