// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val PaperClip: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "PaperClip",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(18.91f, 13.27f)
                lineTo(11.21f, 20.96f)
                quadTo(9.68f, 22.5f, 7.5f, 22.5f)
                quadTo(5.33f, 22.5f, 3.79f, 20.96f)
                quadTo(2.25f, 19.43f, 2.25f, 17.25f)
                quadTo(2.25f, 15.07f, 3.79f, 13.54f)
                lineTo(14.73f, 2.6f)
                quadTo(17.38f, -0.05f, 20.03f, 2.6f)
                quadTo(22.68f, 5.25f, 20.03f, 7.9f)
                lineTo(9.08f, 18.85f)
                quadTo(9.06f, 18.87f, 9.04f, 18.89f)
                quadTo(7.46f, 20.38f, 5.92f, 18.82f)
                quadTo(4.36f, 17.25f, 5.91f, 15.66f)
                lineTo(13.72f, 7.85f)
                quadTo(13.94f, 7.63f, 14.25f, 7.63f)
                quadTo(14.56f, 7.63f, 14.78f, 7.85f)
                quadTo(15f, 8.07f, 15f, 8.38f)
                quadTo(15f, 8.69f, 14.78f, 8.91f)
                lineTo(6.97f, 16.72f)
                quadTo(6.46f, 17.24f, 6.98f, 17.76f)
                quadTo(7.5f, 18.29f, 8.03f, 17.78f)
                lineTo(8.03f, 17.78f)
                quadTo(8.04f, 17.77f, 8.06f, 17.75f)
                lineTo(18.97f, 6.84f)
                quadTo(19.63f, 6.18f, 19.63f, 5.25f)
                quadTo(19.63f, 4.32f, 18.97f, 3.66f)
                quadTo(17.38f, 2.07f, 15.79f, 3.66f)
                lineTo(4.85f, 14.6f)
                quadTo(3.75f, 15.7f, 3.75f, 17.25f)
                quadTo(3.75f, 18.8f, 4.85f, 19.9f)
                quadTo(5.95f, 21f, 7.5f, 21f)
                quadTo(9.05f, 21f, 10.15f, 19.9f)
                lineTo(17.84f, 12.21f)
                quadTo(18.06f, 11.99f, 18.38f, 11.99f)
                quadTo(18.69f, 11.99f, 18.91f, 12.21f)
                quadTo(19.12f, 12.43f, 19.12f, 12.74f)
                quadTo(19.12f, 13.05f, 18.91f, 13.27f)
                close()
            }
        }.build()
}
