// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val PencilSquare: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "PencilSquare",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(16.33f, 3.96f)
                lineTo(16.33f, 3.96f)
                lineTo(18.02f, 2.27f)
                quadTo(19.88f, 0.41f, 21.73f, 2.27f)
                quadTo(23.59f, 4.12f, 21.73f, 5.98f)
                lineTo(11.11f, 16.6f)
                quadTo(10.17f, 17.54f, 8.9f, 17.92f)
                lineTo(6.21f, 18.72f)
                quadTo(5.92f, 18.81f, 5.64f, 18.66f)
                quadTo(5.37f, 18.51f, 5.28f, 18.21f)
                quadTo(5.22f, 18f, 5.28f, 17.79f)
                lineTo(6.08f, 15.1f)
                quadTo(6.46f, 13.83f, 7.4f, 12.89f)
                lineTo(16.33f, 3.96f)
                close()
                moveTo(18.75f, 14f)
                lineTo(18.75f, 18.75f)
                quadTo(18.75f, 21.75f, 15.75f, 21.75f)
                lineTo(5.25f, 21.75f)
                quadTo(2.25f, 21.75f, 2.25f, 18.75f)
                lineTo(2.25f, 8.25f)
                quadTo(2.25f, 5.25f, 5.25f, 5.25f)
                lineTo(10f, 5.25f)
                quadTo(10.31f, 5.25f, 10.53f, 5.47f)
                quadTo(10.75f, 5.69f, 10.75f, 6f)
                quadTo(10.75f, 6.31f, 10.53f, 6.53f)
                quadTo(10.31f, 6.75f, 10f, 6.75f)
                lineTo(5.25f, 6.75f)
                quadTo(3.75f, 6.75f, 3.75f, 8.25f)
                lineTo(3.75f, 18.75f)
                quadTo(3.75f, 20.25f, 5.25f, 20.25f)
                lineTo(15.75f, 20.25f)
                quadTo(17.25f, 20.25f, 17.25f, 18.75f)
                lineTo(17.25f, 14f)
                quadTo(17.25f, 13.69f, 17.47f, 13.47f)
                quadTo(17.69f, 13.25f, 18f, 13.25f)
                quadTo(18.31f, 13.25f, 18.53f, 13.47f)
                quadTo(18.75f, 13.69f, 18.75f, 14f)
                close()
                moveTo(16.86f, 5.55f)
                lineTo(8.46f, 13.95f)
                quadTo(7.79f, 14.62f, 7.52f, 15.53f)
                lineTo(7.12f, 16.89f)
                lineTo(8.47f, 16.48f)
                quadTo(9.38f, 16.21f, 10.05f, 15.54f)
                lineTo(18.45f, 7.14f)
                lineTo(16.86f, 5.55f)
                close()
                moveTo(19.51f, 6.08f)
                lineTo(20.67f, 4.92f)
                quadTo(21.47f, 4.12f, 20.67f, 3.33f)
                quadTo(19.88f, 2.53f, 19.08f, 3.33f)
                lineTo(17.92f, 4.49f)
                lineTo(19.51f, 6.08f)
                close()
            }
        }.build()
}
