// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val PercentBadge: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "PercentBadge",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(21.74f, 11.99f)
                lineTo(21.74f, 11.99f)
                quadTo(21.74f, 14.09f, 20.2f, 15.39f)
                quadTo(20.37f, 17.4f, 18.88f, 18.89f)
                quadTo(17.4f, 20.38f, 15.39f, 20.2f)
                quadTo(14.09f, 21.75f, 11.99f, 21.75f)
                quadTo(9.89f, 21.75f, 8.59f, 20.2f)
                quadTo(6.58f, 20.38f, 5.09f, 18.89f)
                quadTo(3.61f, 17.4f, 3.78f, 15.39f)
                quadTo(2.24f, 14.1f, 2.24f, 11.99f)
                quadTo(2.24f, 9.89f, 3.78f, 8.6f)
                quadTo(3.61f, 6.58f, 5.1f, 5.1f)
                quadTo(6.58f, 3.61f, 8.59f, 3.79f)
                quadTo(9.89f, 2.24f, 11.99f, 2.24f)
                quadTo(14.09f, 2.24f, 15.39f, 3.79f)
                quadTo(17.4f, 3.61f, 18.89f, 5.1f)
                quadTo(20.37f, 6.58f, 20.2f, 8.6f)
                quadTo(21.74f, 9.89f, 21.74f, 11.99f)
                close()
                moveTo(20.24f, 11.99f)
                quadTo(20.24f, 10.44f, 18.97f, 9.54f)
                quadTo(18.58f, 9.27f, 18.66f, 8.8f)
                quadTo(18.93f, 7.26f, 17.82f, 6.16f)
                quadTo(16.72f, 5.06f, 15.19f, 5.33f)
                quadTo(14.72f, 5.41f, 14.45f, 5.02f)
                quadTo(13.55f, 3.74f, 11.99f, 3.74f)
                quadTo(10.43f, 3.74f, 9.54f, 5.02f)
                quadTo(9.26f, 5.41f, 8.79f, 5.33f)
                quadTo(7.26f, 5.06f, 6.16f, 6.16f)
                quadTo(5.05f, 7.26f, 5.32f, 8.8f)
                quadTo(5.4f, 9.27f, 5.01f, 9.54f)
                quadTo(3.74f, 10.44f, 3.74f, 11.99f)
                quadTo(3.74f, 13.55f, 5.01f, 14.45f)
                quadTo(5.4f, 14.72f, 5.32f, 15.19f)
                quadTo(5.05f, 16.73f, 6.16f, 17.83f)
                quadTo(7.26f, 18.93f, 8.79f, 18.66f)
                quadTo(9.26f, 18.58f, 9.54f, 18.97f)
                quadTo(10.43f, 20.25f, 11.99f, 20.25f)
                quadTo(13.55f, 20.25f, 14.44f, 18.97f)
                quadTo(14.72f, 18.58f, 15.19f, 18.66f)
                quadTo(16.72f, 18.93f, 17.82f, 17.83f)
                quadTo(18.93f, 16.73f, 18.66f, 15.19f)
                quadTo(18.58f, 14.72f, 18.96f, 14.45f)
                quadTo(20.24f, 13.55f, 20.24f, 11.99f)
                close()
                moveTo(8.46f, 14.46f)
                lineTo(14.46f, 8.46f)
                quadTo(14.68f, 8.24f, 14.99f, 8.24f)
                quadTo(15.3f, 8.24f, 15.52f, 8.46f)
                quadTo(15.74f, 8.68f, 15.74f, 8.99f)
                quadTo(15.74f, 9.3f, 15.52f, 9.52f)
                lineTo(9.52f, 15.52f)
                quadTo(9.3f, 15.74f, 8.99f, 15.74f)
                quadTo(8.68f, 15.74f, 8.46f, 15.52f)
                quadTo(8.24f, 15.3f, 8.24f, 14.99f)
                quadTo(8.24f, 14.68f, 8.46f, 14.46f)
                close()
                moveTo(10.87f, 9.74f)
                quadTo(10.87f, 10.87f, 9.74f, 10.87f)
                quadTo(8.62f, 10.87f, 8.62f, 9.74f)
                quadTo(8.62f, 8.62f, 9.74f, 8.62f)
                quadTo(10.87f, 8.62f, 10.87f, 9.74f)
                close()
                moveTo(15.37f, 14.24f)
                quadTo(15.37f, 15.37f, 14.24f, 15.37f)
                quadTo(13.12f, 15.37f, 13.12f, 14.24f)
                quadTo(13.12f, 13.12f, 14.24f, 13.12f)
                quadTo(15.37f, 13.12f, 15.37f, 14.24f)
                close()
            }
        }.build()
}
