// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val PlayPause: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "PlayPause",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(2.25f, 8.69f)
                quadTo(2.25f, 7.61f, 3.18f, 7.07f)
                quadTo(4.12f, 6.53f, 5.05f, 7.06f)
                lineTo(12.16f, 11.12f)
                quadTo(13.11f, 11.66f, 13.11f, 12.75f)
                quadTo(13.11f, 13.84f, 12.16f, 14.38f)
                lineTo(5.05f, 18.44f)
                quadTo(4.12f, 18.98f, 3.18f, 18.43f)
                quadTo(2.25f, 17.89f, 2.25f, 16.81f)
                lineTo(2.25f, 16.81f)
                lineTo(2.25f, 8.69f)
                close()
                moveTo(3.75f, 16.81f)
                quadTo(3.75f, 17.03f, 3.94f, 17.14f)
                quadTo(4.12f, 17.25f, 4.31f, 17.14f)
                lineTo(11.42f, 13.08f)
                quadTo(11.61f, 12.97f, 11.61f, 12.75f)
                quadTo(11.61f, 12.53f, 11.42f, 12.43f)
                lineTo(4.31f, 8.36f)
                quadTo(4.12f, 8.26f, 3.94f, 8.37f)
                quadTo(3.75f, 8.47f, 3.75f, 8.69f)
                lineTo(3.75f, 16.81f)
                close()
                moveTo(21.75f, 7.5f)
                lineTo(21.75f, 18f)
                quadTo(21.75f, 18.31f, 21.53f, 18.53f)
                quadTo(21.31f, 18.75f, 21f, 18.75f)
                quadTo(20.69f, 18.75f, 20.47f, 18.53f)
                quadTo(20.25f, 18.31f, 20.25f, 18f)
                lineTo(20.25f, 7.5f)
                quadTo(20.25f, 7.19f, 20.47f, 6.97f)
                quadTo(20.69f, 6.75f, 21f, 6.75f)
                quadTo(21.31f, 6.75f, 21.53f, 6.97f)
                quadTo(21.75f, 7.19f, 21.75f, 7.5f)
                close()
                moveTo(15.75f, 7.5f)
                lineTo(15.75f, 18f)
                quadTo(15.75f, 18.31f, 15.53f, 18.53f)
                quadTo(15.31f, 18.75f, 15f, 18.75f)
                quadTo(14.69f, 18.75f, 14.47f, 18.53f)
                quadTo(14.25f, 18.31f, 14.25f, 18f)
                lineTo(14.25f, 7.5f)
                quadTo(14.25f, 7.19f, 14.47f, 6.97f)
                quadTo(14.69f, 6.75f, 15f, 6.75f)
                quadTo(15.31f, 6.75f, 15.53f, 6.97f)
                quadTo(15.75f, 7.19f, 15.75f, 7.5f)
                close()
            }
        }.build()
}
