// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val PresentationChartLine: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "PresentationChartLine",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(3.75f, 2.25f)
                lineTo(21.75f, 2.25f)
                quadTo(22.06f, 2.25f, 22.28f, 2.47f)
                quadTo(22.5f, 2.69f, 22.5f, 3f)
                quadTo(22.5f, 3.31f, 22.28f, 3.53f)
                quadTo(22.06f, 3.75f, 21.75f, 3.75f)
                lineTo(21f, 3.75f)
                lineTo(21f, 14.25f)
                quadTo(21f, 17.25f, 18f, 17.25f)
                lineTo(16.79f, 17.25f)
                lineTo(17.44f, 19.21f)
                quadTo(17.46f, 19.26f, 17.48f, 19.31f)
                lineTo(17.96f, 20.76f)
                quadTo(18.06f, 21.06f, 17.92f, 21.34f)
                quadTo(17.78f, 21.61f, 17.49f, 21.71f)
                quadTo(17.19f, 21.81f, 16.91f, 21.67f)
                quadTo(16.64f, 21.53f, 16.54f, 21.24f)
                lineTo(16.21f, 20.25f)
                lineTo(7.79f, 20.25f)
                lineTo(7.46f, 21.24f)
                quadTo(7.36f, 21.53f, 7.08f, 21.67f)
                quadTo(6.81f, 21.81f, 6.51f, 21.71f)
                quadTo(6.22f, 21.61f, 6.08f, 21.34f)
                quadTo(5.94f, 21.06f, 6.04f, 20.76f)
                lineTo(6.52f, 19.31f)
                quadTo(6.54f, 19.26f, 6.56f, 19.21f)
                lineTo(7.21f, 17.25f)
                lineTo(6f, 17.25f)
                quadTo(3f, 17.25f, 3f, 14.25f)
                lineTo(3f, 3.75f)
                lineTo(2.25f, 3.75f)
                quadTo(1.94f, 3.75f, 1.72f, 3.53f)
                quadTo(1.5f, 3.31f, 1.5f, 3f)
                quadTo(1.5f, 2.69f, 1.72f, 2.47f)
                quadTo(1.94f, 2.25f, 2.25f, 2.25f)
                lineTo(3.75f, 2.25f)
                close()
                moveTo(4.5f, 3.75f)
                lineTo(4.5f, 14.25f)
                quadTo(4.5f, 15.75f, 6f, 15.75f)
                lineTo(8.19f, 15.75f)
                quadTo(8.25f, 15.75f, 8.3f, 15.75f)
                lineTo(15.7f, 15.75f)
                quadTo(15.75f, 15.75f, 15.81f, 15.75f)
                lineTo(18f, 15.75f)
                quadTo(19.5f, 15.75f, 19.5f, 14.25f)
                lineTo(19.5f, 3.75f)
                lineTo(4.5f, 3.75f)
                close()
                moveTo(6.97f, 11.47f)
                lineTo(9.97f, 8.47f)
                quadTo(10.19f, 8.25f, 10.5f, 8.25f)
                quadTo(10.81f, 8.25f, 11.03f, 8.47f)
                lineTo(12.57f, 10.01f)
                quadTo(14.05f, 8.16f, 16.12f, 6.96f)
                quadTo(16.39f, 6.8f, 16.69f, 6.88f)
                quadTo(16.99f, 6.96f, 17.15f, 7.23f)
                quadTo(17.3f, 7.5f, 17.23f, 7.8f)
                quadTo(17.14f, 8.1f, 16.88f, 8.25f)
                quadTo(14.7f, 9.51f, 13.26f, 11.58f)
                quadTo(13.22f, 11.63f, 13.18f, 11.68f)
                quadTo(12.96f, 11.9f, 12.65f, 11.9f)
                quadTo(12.34f, 11.9f, 12.12f, 11.68f)
                lineTo(10.5f, 10.06f)
                lineTo(8.03f, 12.53f)
                quadTo(7.81f, 12.75f, 7.5f, 12.75f)
                quadTo(7.19f, 12.75f, 6.97f, 12.53f)
                quadTo(6.75f, 12.31f, 6.75f, 12f)
                quadTo(6.75f, 11.69f, 6.97f, 11.47f)
                close()
                moveTo(8.79f, 17.25f)
                lineTo(8.29f, 18.75f)
                lineTo(15.71f, 18.75f)
                lineTo(15.21f, 17.25f)
                lineTo(8.79f, 17.25f)
                close()
            }
        }.build()
}
