// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val RectangleGroup: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "RectangleGroup",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(13.5f, 8.62f)
                quadTo(13.5f, 6.75f, 15.38f, 6.75f)
                lineTo(20.62f, 6.75f)
                quadTo(22.5f, 6.75f, 22.5f, 8.62f)
                lineTo(22.5f, 16.88f)
                quadTo(22.5f, 18.75f, 20.62f, 18.75f)
                lineTo(15.38f, 18.75f)
                quadTo(13.5f, 18.75f, 13.5f, 16.88f)
                close()
                moveTo(1.5f, 7.12f)
                quadTo(1.5f, 5.25f, 3.38f, 5.25f)
                lineTo(9.38f, 5.25f)
                quadTo(11.25f, 5.25f, 11.25f, 7.12f)
                lineTo(11.25f, 10.88f)
                quadTo(11.25f, 12.75f, 9.38f, 12.75f)
                lineTo(3.38f, 12.75f)
                quadTo(1.5f, 12.75f, 1.5f, 10.88f)
                close()
                moveTo(15f, 8.62f)
                lineTo(15f, 16.88f)
                quadTo(15f, 17.25f, 15.38f, 17.25f)
                lineTo(20.62f, 17.25f)
                quadTo(21f, 17.25f, 21f, 16.88f)
                lineTo(21f, 8.62f)
                quadTo(21f, 8.25f, 20.62f, 8.25f)
                lineTo(15.38f, 8.25f)
                quadTo(15f, 8.25f, 15f, 8.62f)
                close()
                moveTo(3f, 16.12f)
                quadTo(3f, 14.25f, 4.88f, 14.25f)
                lineTo(10.12f, 14.25f)
                quadTo(12f, 14.25f, 12f, 16.12f)
                lineTo(12f, 18.38f)
                quadTo(12f, 20.25f, 10.12f, 20.25f)
                lineTo(4.88f, 20.25f)
                quadTo(3f, 20.25f, 3f, 18.38f)
                close()
                moveTo(3f, 7.12f)
                lineTo(3f, 10.88f)
                quadTo(3f, 11.25f, 3.38f, 11.25f)
                lineTo(9.38f, 11.25f)
                quadTo(9.75f, 11.25f, 9.75f, 10.88f)
                lineTo(9.75f, 7.12f)
                quadTo(9.75f, 6.75f, 9.38f, 6.75f)
                lineTo(3.38f, 6.75f)
                quadTo(3f, 6.75f, 3f, 7.12f)
                close()
                moveTo(4.5f, 16.12f)
                lineTo(4.5f, 18.38f)
                quadTo(4.5f, 18.75f, 4.88f, 18.75f)
                lineTo(10.12f, 18.75f)
                quadTo(10.5f, 18.75f, 10.5f, 18.38f)
                lineTo(10.5f, 16.12f)
                quadTo(10.5f, 15.75f, 10.12f, 15.75f)
                lineTo(4.88f, 15.75f)
                quadTo(4.5f, 15.75f, 4.5f, 16.12f)
                close()
            }
        }.build()
}
