// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val RocketLaunch: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "RocketLaunch",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(9f, 17.62f)
                quadTo(8.99f, 17.61f, 8.97f, 17.6f)
                quadTo(7.54f, 16.46f, 6.4f, 15.03f)
                quadTo(6.39f, 15.01f, 6.38f, 15f)
                lineTo(2.25f, 15f)
                quadTo(1.94f, 15f, 1.72f, 14.78f)
                quadTo(1.5f, 14.56f, 1.5f, 14.25f)
                quadTo(1.5f, 10.98f, 4.06f, 8.96f)
                quadTo(6.43f, 7.08f, 9.31f, 7.58f)
                quadTo(13.98f, 1.49f, 21.75f, 1.5f)
                quadTo(22.06f, 1.5f, 22.28f, 1.72f)
                quadTo(22.5f, 1.94f, 22.5f, 2.25f)
                quadTo(22.51f, 10.02f, 16.42f, 14.69f)
                quadTo(16.91f, 17.57f, 15.04f, 19.94f)
                quadTo(13.02f, 22.5f, 9.75f, 22.5f)
                quadTo(9.44f, 22.5f, 9.22f, 22.28f)
                quadTo(9f, 22.06f, 9f, 21.75f)
                lineTo(9f, 17.62f)
                close()
                moveTo(15.1f, 13.8f)
                quadTo(15.14f, 13.76f, 15.19f, 13.73f)
                quadTo(20.69f, 9.7f, 20.98f, 3.02f)
                quadTo(14.3f, 3.31f, 10.27f, 8.81f)
                quadTo(10.24f, 8.86f, 10.2f, 8.9f)
                quadTo(8.41f, 11.37f, 7.79f, 14.36f)
                quadTo(8.63f, 15.37f, 9.64f, 16.21f)
                quadTo(12.63f, 15.59f, 15.1f, 13.8f)
                close()
                moveTo(17.25f, 9f)
                quadTo(17.25f, 11.25f, 15f, 11.25f)
                quadTo(12.75f, 11.25f, 12.75f, 9f)
                quadTo(12.75f, 6.75f, 15f, 6.75f)
                quadTo(17.25f, 6.75f, 17.25f, 9f)
                close()
                moveTo(5.26f, 17.24f)
                quadTo(3.68f, 18.42f, 3.74f, 20.26f)
                quadTo(5.58f, 20.32f, 6.76f, 18.74f)
                quadTo(6.94f, 18.49f, 7.25f, 18.45f)
                quadTo(7.56f, 18.4f, 7.81f, 18.59f)
                quadTo(8.06f, 18.77f, 8.1f, 19.08f)
                quadTo(8.15f, 19.39f, 7.96f, 19.64f)
                quadTo(6.07f, 22.18f, 2.94f, 21.69f)
                quadTo(2.4f, 21.6f, 2.31f, 21.06f)
                quadTo(1.82f, 17.93f, 4.36f, 16.04f)
                quadTo(4.61f, 15.85f, 4.92f, 15.9f)
                quadTo(5.23f, 15.94f, 5.41f, 16.19f)
                quadTo(5.6f, 16.44f, 5.55f, 16.75f)
                quadTo(5.51f, 17.06f, 5.26f, 17.24f)
                close()
                moveTo(8.34f, 8.98f)
                quadTo(6.52f, 8.92f, 4.99f, 10.13f)
                quadTo(3.3f, 11.47f, 3.05f, 13.5f)
                lineTo(6.45f, 13.5f)
                quadTo(7.04f, 11.08f, 8.34f, 8.98f)
                close()
                moveTo(15.02f, 15.66f)
                quadTo(12.91f, 16.96f, 10.5f, 17.55f)
                lineTo(10.5f, 20.95f)
                quadTo(12.53f, 20.7f, 13.87f, 19.01f)
                quadTo(15.08f, 17.48f, 15.02f, 15.66f)
                close()
                moveTo(15.75f, 9f)
                quadTo(15.75f, 8.25f, 15f, 8.25f)
                quadTo(14.25f, 8.25f, 14.25f, 9f)
                quadTo(14.25f, 9.75f, 15f, 9.75f)
                quadTo(15.75f, 9.75f, 15.75f, 9f)
                close()
            }
        }.build()
}
