// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Scissors: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "Scissors",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(9.76f, 8.49f)
                lineTo(9.76f, 8.49f)
                lineTo(9.76f, 8.49f)
                lineTo(9.76f, 8.49f)
                lineTo(9.76f, 8.49f)
                lineTo(9.76f, 8.49f)
                lineTo(11.32f, 9.39f)
                quadTo(12.16f, 8.59f, 13.31f, 8.24f)
                lineTo(18.64f, 6.61f)
                quadTo(20.07f, 6.17f, 21.53f, 6.56f)
                lineTo(22.33f, 6.78f)
                quadTo(22.63f, 6.86f, 22.79f, 7.12f)
                quadTo(22.94f, 7.39f, 22.86f, 7.69f)
                quadTo(22.78f, 7.99f, 22.51f, 8.15f)
                lineTo(15.84f, 12f)
                lineTo(22.51f, 15.85f)
                quadTo(22.78f, 16.01f, 22.86f, 16.31f)
                quadTo(22.94f, 16.61f, 22.79f, 16.88f)
                quadTo(22.63f, 17.14f, 22.33f, 17.22f)
                lineTo(21.53f, 17.44f)
                quadTo(20.07f, 17.83f, 18.64f, 17.39f)
                lineTo(13.31f, 15.76f)
                quadTo(12.16f, 15.41f, 11.32f, 14.61f)
                lineTo(9.76f, 15.51f)
                lineTo(9.76f, 15.51f)
                lineTo(9.76f, 15.51f)
                lineTo(9.76f, 15.51f)
                lineTo(9.76f, 15.51f)
                lineTo(8.82f, 16.05f)
                quadTo(9.4f, 17.59f, 8.51f, 19.14f)
                quadTo(7.43f, 21.02f, 5.25f, 21.02f)
                quadTo(3.08f, 21.01f, 2f, 19.12f)
                quadTo(0.16f, 15.88f, 3.38f, 14.02f)
                quadTo(6.27f, 12.35f, 8.08f, 14.75f)
                lineTo(9.01f, 14.21f)
                lineTo(9.01f, 14.21f)
                lineTo(9.01f, 14.21f)
                lineTo(9.01f, 14.21f)
                quadTo(9.7f, 13.81f, 9.72f, 13.01f)
                quadTo(9.72f, 12.5f, 9.84f, 12f)
                quadTo(9.72f, 11.5f, 9.72f, 10.99f)
                quadTo(9.7f, 10.19f, 9.01f, 9.79f)
                lineTo(9.01f, 9.79f)
                lineTo(9.01f, 9.79f)
                lineTo(9.01f, 9.79f)
                lineTo(8.07f, 9.25f)
                quadTo(7.03f, 10.51f, 5.25f, 10.52f)
                quadTo(3.07f, 10.52f, 1.99f, 8.63f)
                quadTo(0.9f, 6.75f, 2f, 4.87f)
                quadTo(3.89f, 1.66f, 7.12f, 3.52f)
                quadTo(10f, 5.19f, 8.83f, 7.95f)
                close()
                moveTo(7.2f, 16.13f)
                quadTo(6.07f, 14.2f, 4.13f, 15.32f)
                quadTo(2.2f, 16.44f, 3.3f, 18.38f)
                quadTo(3.95f, 19.51f, 5.25f, 19.52f)
                quadTo(6.56f, 19.52f, 7.21f, 18.39f)
                quadTo(7.86f, 17.26f, 7.2f, 16.13f)
                quadTo(7.2f, 16.13f, 7.2f, 16.13f)
                close()
                moveTo(7.2f, 7.88f)
                quadTo(8.3f, 5.94f, 6.37f, 4.82f)
                quadTo(4.43f, 3.7f, 3.3f, 5.63f)
                quadTo(2.64f, 6.76f, 3.29f, 7.89f)
                quadTo(3.94f, 9.02f, 5.25f, 9.02f)
                quadTo(6.55f, 9.01f, 7.2f, 7.88f)
                quadTo(7.2f, 7.88f, 7.2f, 7.88f)
                close()
                moveTo(11.32f, 12.23f)
                quadTo(11.23f, 12.58f, 11.22f, 12.94f)
                lineTo(13.92f, 11.38f)
                quadTo(13.96f, 11.35f, 14.01f, 11.33f)
                lineTo(19.97f, 7.88f)
                quadTo(19.52f, 7.91f, 19.07f, 8.05f)
                lineTo(13.75f, 9.67f)
                quadTo(12.74f, 9.98f, 12.06f, 10.79f)
                quadTo(12.04f, 10.82f, 12.01f, 10.85f)
                quadTo(11.54f, 11.43f, 11.35f, 12.14f)
                quadTo(11.34f, 12.19f, 11.32f, 12.23f)
                close()
                moveTo(14.34f, 12.87f)
                lineTo(12.7f, 13.81f)
                quadTo(13.17f, 14.15f, 13.75f, 14.33f)
                lineTo(19.07f, 15.96f)
                quadTo(19.52f, 16.09f, 19.97f, 16.12f)
                lineTo(14.34f, 12.87f)
                close()
            }
        }.build()
}
