// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Server: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "Server",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(22.5f, 17.25f)
                quadTo(22.5f, 21f, 18.75f, 21f)
                lineTo(5.25f, 21f)
                quadTo(1.5f, 21f, 1.5f, 17.25f)
                lineTo(1.5f, 17.02f)
                quadTo(1.5f, 16.41f, 1.64f, 15.82f)
                lineTo(3.91f, 6.18f)
                quadTo(4.66f, 3f, 7.92f, 3f)
                lineTo(16.08f, 3f)
                quadTo(19.34f, 3f, 20.09f, 6.18f)
                lineTo(22.36f, 15.82f)
                quadTo(22.5f, 16.41f, 22.5f, 17.02f)
                close()
                moveTo(20.32f, 13.71f)
                lineTo(18.63f, 6.52f)
                quadTo(18.16f, 4.5f, 16.08f, 4.5f)
                lineTo(7.92f, 4.5f)
                quadTo(5.84f, 4.5f, 5.37f, 6.52f)
                lineTo(3.68f, 13.71f)
                quadTo(4.36f, 13.5f, 5.25f, 13.5f)
                lineTo(18.75f, 13.5f)
                quadTo(19.64f, 13.5f, 20.32f, 13.71f)
                close()
                moveTo(21f, 17.25f)
                quadTo(21f, 15f, 18.75f, 15f)
                lineTo(5.25f, 15f)
                quadTo(3f, 15f, 3f, 17.25f)
                quadTo(3f, 19.5f, 5.25f, 19.5f)
                lineTo(18.75f, 19.5f)
                quadTo(21f, 19.5f, 21f, 17.25f)
                close()
                moveTo(15.75f, 16.5f)
                lineTo(15.76f, 16.5f)
                quadTo(16.07f, 16.5f, 16.29f, 16.72f)
                quadTo(16.51f, 16.94f, 16.51f, 17.25f)
                lineTo(16.51f, 17.26f)
                quadTo(16.51f, 17.57f, 16.29f, 17.79f)
                quadTo(16.07f, 18.01f, 15.76f, 18.01f)
                lineTo(15.75f, 18.01f)
                quadTo(15.44f, 18.01f, 15.22f, 17.79f)
                quadTo(15f, 17.57f, 15f, 17.26f)
                lineTo(15f, 17.25f)
                quadTo(15f, 16.94f, 15.22f, 16.72f)
                quadTo(15.44f, 16.5f, 15.75f, 16.5f)
                close()
                moveTo(18.75f, 16.5f)
                lineTo(18.76f, 16.5f)
                quadTo(19.07f, 16.5f, 19.29f, 16.72f)
                quadTo(19.51f, 16.94f, 19.51f, 17.25f)
                lineTo(19.51f, 17.26f)
                quadTo(19.51f, 17.57f, 19.29f, 17.79f)
                quadTo(19.07f, 18.01f, 18.76f, 18.01f)
                lineTo(18.75f, 18.01f)
                quadTo(18.44f, 18.01f, 18.22f, 17.79f)
                quadTo(18f, 17.57f, 18f, 17.26f)
                lineTo(18f, 17.25f)
                quadTo(18f, 16.94f, 18.22f, 16.72f)
                quadTo(18.44f, 16.5f, 18.75f, 16.5f)
                close()
            }
        }.build()
}
