// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Share: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "Share",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(16.55f, 6.58f)
                lineTo(8.15f, 11.24f)
                quadTo(8.25f, 11.61f, 8.25f, 12f)
                quadTo(8.25f, 12.39f, 8.15f, 12.76f)
                lineTo(16.54f, 17.41f)
                quadTo(17.94f, 15.62f, 20.21f, 16.88f)
                quadTo(22.83f, 18.33f, 21.37f, 20.96f)
                quadTo(19.92f, 23.58f, 17.29f, 22.12f)
                quadTo(16.21f, 21.52f, 15.87f, 20.32f)
                quadTo(15.63f, 19.51f, 15.84f, 18.74f)
                lineTo(7.45f, 14.08f)
                quadTo(6.36f, 15.39f, 4.5f, 14.9f)
                quadTo(2.25f, 14.32f, 2.25f, 12f)
                quadTo(2.25f, 9.68f, 4.5f, 9.1f)
                quadTo(6.36f, 8.61f, 7.45f, 9.92f)
                lineTo(15.82f, 5.27f)
                quadTo(15.09f, 3.15f, 17.31f, 1.92f)
                quadTo(19.89f, 0.49f, 21.36f, 3.03f)
                quadTo(22.25f, 4.55f, 21.35f, 6.06f)
                quadTo(20.46f, 7.58f, 18.7f, 7.54f)
                quadTo(17.35f, 7.51f, 16.55f, 6.58f)
                close()
                moveTo(17.44f, 18.77f)
                quadTo(17.14f, 19.32f, 17.31f, 19.91f)
                quadTo(17.48f, 20.51f, 18.02f, 20.81f)
                quadTo(19.33f, 21.54f, 20.06f, 20.23f)
                quadTo(20.79f, 18.92f, 19.48f, 18.19f)
                quadTo(18.17f, 17.46f, 17.44f, 18.77f)
                close()
                moveTo(17.45f, 5.25f)
                quadTo(17.86f, 6.02f, 18.74f, 6.04f)
                quadTo(19.61f, 6.06f, 20.06f, 5.3f)
                quadTo(20.51f, 4.54f, 20.07f, 3.79f)
                quadTo(19.33f, 2.51f, 18.04f, 3.23f)
                quadTo(16.76f, 3.94f, 17.44f, 5.24f)
                quadTo(17.45f, 5.24f, 17.45f, 5.25f)
                close()
                moveTo(6.56f, 11.27f)
                lineTo(6.56f, 11.27f)
                lineTo(6.56f, 11.27f)
                quadTo(6f, 10.26f, 4.87f, 10.55f)
                quadTo(3.75f, 10.84f, 3.75f, 12f)
                quadTo(3.75f, 13.16f, 4.87f, 13.45f)
                quadTo(6f, 13.74f, 6.56f, 12.73f)
                lineTo(6.56f, 12.73f)
                lineTo(6.56f, 12.73f)
                quadTo(6.75f, 12.39f, 6.75f, 12f)
                quadTo(6.75f, 11.61f, 6.56f, 11.27f)
                close()
                moveTo(6.63f, 13.56f)
                quadTo(6.72f, 13.67f, 6.85f, 13.75f)
                lineTo(6.85f, 13.75f)
                lineTo(6.85f, 13.75f)
                close()
            }
        }.build()
}
