// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val ShieldCheck: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "ShieldCheck",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(11.48f, 2.17f)
                quadTo(11.7f, 1.96f, 12f, 1.96f)
                quadTo(12.3f, 1.96f, 12.52f, 2.17f)
                quadTo(15.77f, 5.25f, 20.25f, 5.25f)
                lineTo(20.4f, 5.25f)
                quadTo(20.95f, 5.25f, 21.11f, 5.76f)
                quadTo(21.75f, 7.7f, 21.75f, 9.75f)
                quadTo(21.75f, 14.16f, 19.03f, 17.62f)
                quadTo(16.36f, 21.02f, 12.19f, 22.1f)
                quadTo(12f, 22.15f, 11.81f, 22.1f)
                quadTo(7.64f, 21.02f, 4.97f, 17.62f)
                quadTo(2.25f, 14.16f, 2.25f, 9.75f)
                quadTo(2.25f, 7.71f, 2.88f, 5.77f)
                quadTo(3.06f, 5.24f, 3.61f, 5.25f)
                quadTo(8.17f, 5.31f, 11.48f, 2.17f)
                close()
                moveTo(12f, 3.73f)
                quadTo(8.62f, 6.63f, 4.16f, 6.75f)
                quadTo(3.75f, 8.21f, 3.75f, 9.75f)
                quadTo(3.75f, 13.64f, 6.15f, 16.69f)
                quadTo(8.45f, 19.62f, 12f, 20.6f)
                quadTo(15.55f, 19.62f, 17.85f, 16.7f)
                quadTo(20.25f, 13.64f, 20.25f, 9.75f)
                quadTo(20.25f, 8.21f, 19.84f, 6.74f)
                quadTo(15.37f, 6.62f, 12f, 3.73f)
                close()
                moveTo(9.53f, 12.22f)
                lineTo(11.15f, 13.84f)
                lineTo(14.39f, 9.31f)
                quadTo(14.57f, 9.06f, 14.88f, 9.01f)
                quadTo(15.18f, 8.96f, 15.44f, 9.14f)
                quadTo(15.69f, 9.32f, 15.74f, 9.63f)
                quadTo(15.79f, 9.93f, 15.61f, 10.19f)
                lineTo(11.86f, 15.44f)
                quadTo(11.82f, 15.49f, 11.78f, 15.53f)
                quadTo(11.56f, 15.75f, 11.25f, 15.75f)
                quadTo(10.94f, 15.75f, 10.72f, 15.53f)
                lineTo(8.47f, 13.28f)
                quadTo(8.25f, 13.06f, 8.25f, 12.75f)
                quadTo(8.25f, 12.44f, 8.47f, 12.22f)
                quadTo(8.69f, 12f, 9f, 12f)
                quadTo(9.31f, 12f, 9.53f, 12.22f)
                close()
            }
        }.build()
}
