// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val ShoppingBag: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "ShoppingBag",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(20.35f, 8.43f)
                lineTo(20.35f, 8.43f)
                lineTo(21.61f, 20.43f)
                quadTo(21.7f, 21.26f, 21.14f, 21.88f)
                quadTo(20.59f, 22.5f, 19.75f, 22.5f)
                lineTo(4.25f, 22.5f)
                quadTo(3.42f, 22.5f, 2.86f, 21.88f)
                quadTo(2.3f, 21.26f, 2.38f, 20.43f)
                lineTo(3.65f, 8.43f)
                quadTo(3.83f, 6.75f, 5.51f, 6.75f)
                lineTo(7.5f, 6.75f)
                lineTo(7.5f, 6f)
                quadTo(7.5f, 4.14f, 8.82f, 2.82f)
                quadTo(10.14f, 1.5f, 12f, 1.5f)
                quadTo(13.86f, 1.5f, 15.18f, 2.82f)
                quadTo(16.5f, 4.14f, 16.5f, 6f)
                lineTo(16.5f, 6.75f)
                lineTo(18.49f, 6.75f)
                quadTo(20.18f, 6.75f, 20.35f, 8.43f)
                close()
                moveTo(18.86f, 8.59f)
                quadTo(18.82f, 8.25f, 18.49f, 8.25f)
                lineTo(16.5f, 8.25f)
                lineTo(16.5f, 9.58f)
                quadTo(16.88f, 9.85f, 16.88f, 10.5f)
                quadTo(16.88f, 11.62f, 15.75f, 11.62f)
                quadTo(14.62f, 11.62f, 14.62f, 10.5f)
                quadTo(14.62f, 9.85f, 15f, 9.58f)
                lineTo(15f, 8.25f)
                lineTo(9f, 8.25f)
                lineTo(9f, 9.58f)
                quadTo(9.38f, 9.85f, 9.38f, 10.5f)
                quadTo(9.38f, 11.62f, 8.25f, 11.62f)
                quadTo(7.12f, 11.62f, 7.12f, 10.5f)
                quadTo(7.12f, 9.85f, 7.5f, 9.58f)
                lineTo(7.5f, 8.25f)
                lineTo(5.51f, 8.25f)
                quadTo(5.17f, 8.25f, 5.14f, 8.59f)
                lineTo(3.88f, 20.59f)
                quadTo(3.86f, 20.75f, 3.97f, 20.88f)
                quadTo(4.08f, 21f, 4.25f, 21f)
                lineTo(19.75f, 21f)
                quadTo(19.92f, 21f, 20.03f, 20.88f)
                quadTo(20.14f, 20.75f, 20.12f, 20.59f)
                lineTo(18.86f, 8.59f)
                close()
                moveTo(15f, 6.75f)
                lineTo(15f, 6f)
                quadTo(15f, 3f, 12f, 3f)
                quadTo(9f, 3f, 9f, 6f)
                lineTo(9f, 6.75f)
                lineTo(15f, 6.75f)
                close()
            }
        }.build()
}
