// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Signal: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "Signal",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(19.42f, 4.58f)
                quadTo(22.5f, 7.65f, 22.5f, 12f)
                quadTo(22.5f, 16.35f, 19.42f, 19.42f)
                quadTo(19.2f, 19.64f, 18.89f, 19.64f)
                quadTo(18.58f, 19.64f, 18.36f, 19.42f)
                quadTo(18.14f, 19.2f, 18.14f, 18.89f)
                quadTo(18.14f, 18.58f, 18.36f, 18.36f)
                quadTo(21f, 15.73f, 21f, 12f)
                quadTo(21f, 8.27f, 18.36f, 5.64f)
                quadTo(18.14f, 5.42f, 18.14f, 5.11f)
                quadTo(18.14f, 4.79f, 18.36f, 4.58f)
                quadTo(18.58f, 4.36f, 18.89f, 4.36f)
                quadTo(19.2f, 4.36f, 19.42f, 4.58f)
                close()
                moveTo(4.58f, 19.42f)
                quadTo(1.5f, 16.35f, 1.5f, 12f)
                quadTo(1.5f, 7.65f, 4.58f, 4.58f)
                quadTo(4.79f, 4.36f, 5.11f, 4.36f)
                quadTo(5.42f, 4.36f, 5.64f, 4.58f)
                quadTo(5.86f, 4.79f, 5.86f, 5.11f)
                quadTo(5.86f, 5.42f, 5.64f, 5.64f)
                quadTo(3f, 8.27f, 3f, 12f)
                quadTo(3f, 15.73f, 5.64f, 18.36f)
                quadTo(5.86f, 18.58f, 5.86f, 18.89f)
                quadTo(5.86f, 19.2f, 5.64f, 19.42f)
                quadTo(5.42f, 19.64f, 5.11f, 19.64f)
                quadTo(4.79f, 19.64f, 4.58f, 19.42f)
                close()
                moveTo(17.3f, 6.7f)
                quadTo(19.5f, 8.89f, 19.5f, 12f)
                quadTo(19.5f, 15.11f, 17.3f, 17.3f)
                quadTo(17.08f, 17.52f, 16.77f, 17.52f)
                quadTo(16.46f, 17.52f, 16.24f, 17.3f)
                quadTo(16.02f, 17.08f, 16.02f, 16.77f)
                quadTo(16.02f, 16.46f, 16.24f, 16.24f)
                quadTo(18f, 14.48f, 18f, 12f)
                quadTo(18f, 9.52f, 16.24f, 7.76f)
                quadTo(16.02f, 7.54f, 16.02f, 7.23f)
                quadTo(16.02f, 6.92f, 16.24f, 6.7f)
                quadTo(16.46f, 6.48f, 16.77f, 6.48f)
                quadTo(17.08f, 6.48f, 17.3f, 6.7f)
                close()
                moveTo(6.7f, 17.3f)
                quadTo(4.5f, 15.11f, 4.5f, 12f)
                quadTo(4.5f, 8.89f, 6.7f, 6.7f)
                quadTo(6.92f, 6.48f, 7.23f, 6.48f)
                quadTo(7.54f, 6.48f, 7.76f, 6.7f)
                quadTo(7.98f, 6.92f, 7.98f, 7.23f)
                quadTo(7.98f, 7.54f, 7.76f, 7.76f)
                quadTo(6f, 9.52f, 6f, 12f)
                quadTo(6f, 14.48f, 7.76f, 16.24f)
                quadTo(7.98f, 16.46f, 7.98f, 16.77f)
                quadTo(7.98f, 17.08f, 7.76f, 17.3f)
                quadTo(7.54f, 17.52f, 7.23f, 17.52f)
                quadTo(6.92f, 17.52f, 6.7f, 17.3f)
                close()
                moveTo(8.82f, 15.18f)
                quadTo(7.5f, 13.86f, 7.5f, 12f)
                quadTo(7.5f, 10.14f, 8.82f, 8.82f)
                quadTo(9.04f, 8.6f, 9.35f, 8.6f)
                quadTo(9.66f, 8.6f, 9.88f, 8.82f)
                quadTo(10.1f, 9.04f, 10.1f, 9.35f)
                quadTo(10.1f, 9.66f, 9.88f, 9.88f)
                quadTo(9f, 10.76f, 9f, 12f)
                quadTo(9f, 13.24f, 9.88f, 14.12f)
                quadTo(10.1f, 14.34f, 10.1f, 14.65f)
                quadTo(10.1f, 14.96f, 9.88f, 15.18f)
                quadTo(9.66f, 15.4f, 9.35f, 15.4f)
                quadTo(9.04f, 15.4f, 8.82f, 15.18f)
                close()
                moveTo(15.18f, 8.82f)
                quadTo(16.5f, 10.14f, 16.5f, 12f)
                quadTo(16.5f, 13.86f, 15.18f, 15.18f)
                quadTo(14.96f, 15.4f, 14.65f, 15.4f)
                quadTo(14.34f, 15.4f, 14.12f, 15.18f)
                quadTo(13.9f, 14.96f, 13.9f, 14.65f)
                quadTo(13.9f, 14.34f, 14.12f, 14.12f)
                quadTo(15f, 13.24f, 15f, 12f)
                quadTo(15f, 10.76f, 14.12f, 9.88f)
                quadTo(13.9f, 9.66f, 13.9f, 9.35f)
                quadTo(13.9f, 9.04f, 14.12f, 8.82f)
                quadTo(14.34f, 8.6f, 14.65f, 8.6f)
                quadTo(14.96f, 8.6f, 15.18f, 8.82f)
                close()
                moveTo(13.12f, 12f)
                quadTo(13.12f, 13.12f, 12f, 13.12f)
                quadTo(10.88f, 13.12f, 10.88f, 12f)
                quadTo(10.88f, 10.88f, 12f, 10.88f)
                quadTo(13.12f, 10.88f, 13.12f, 12f)
                close()
            }
        }.build()
}
