// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val SignalSlash: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "SignalSlash",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(3.53f, 2.47f)
                lineTo(11.88f, 10.82f)
                quadTo(12.34f, 10.75f, 12.79f, 11.21f)
                quadTo(13.25f, 11.66f, 13.18f, 12.12f)
                lineTo(14.59f, 13.53f)
                quadTo(15f, 12.85f, 15f, 12f)
                quadTo(15f, 10.76f, 14.12f, 9.88f)
                quadTo(13.9f, 9.66f, 13.9f, 9.35f)
                quadTo(13.9f, 9.04f, 14.12f, 8.82f)
                quadTo(14.34f, 8.6f, 14.65f, 8.6f)
                quadTo(14.96f, 8.6f, 15.18f, 8.82f)
                quadTo(16.5f, 10.14f, 16.5f, 12f)
                quadTo(16.5f, 13.48f, 15.67f, 14.61f)
                lineTo(16.74f, 15.68f)
                quadTo(18f, 14.1f, 18f, 12f)
                quadTo(18f, 9.52f, 16.24f, 7.76f)
                quadTo(16.02f, 7.54f, 16.02f, 7.23f)
                quadTo(16.02f, 6.92f, 16.24f, 6.7f)
                quadTo(16.46f, 6.48f, 16.77f, 6.48f)
                quadTo(17.08f, 6.48f, 17.3f, 6.7f)
                quadTo(19.5f, 8.89f, 19.5f, 12f)
                quadTo(19.5f, 14.72f, 17.81f, 16.75f)
                lineTo(18.88f, 17.81f)
                quadTo(21f, 15.35f, 21f, 12f)
                quadTo(21f, 8.27f, 18.36f, 5.64f)
                quadTo(18.14f, 5.42f, 18.14f, 5.11f)
                quadTo(18.14f, 4.79f, 18.36f, 4.58f)
                quadTo(18.58f, 4.36f, 18.89f, 4.36f)
                quadTo(19.2f, 4.36f, 19.42f, 4.58f)
                quadTo(22.5f, 7.65f, 22.5f, 12f)
                quadTo(22.5f, 15.97f, 19.94f, 18.88f)
                lineTo(21.53f, 20.47f)
                quadTo(21.75f, 20.69f, 21.75f, 21f)
                quadTo(21.75f, 21.31f, 21.53f, 21.53f)
                quadTo(21.31f, 21.75f, 21f, 21.75f)
                quadTo(20.69f, 21.75f, 20.47f, 21.53f)
                lineTo(18.36f, 19.42f)
                lineTo(16.24f, 17.3f)
                lineTo(11.54f, 12.6f)
                quadTo(11.51f, 12.57f, 11.47f, 12.54f)
                quadTo(11.43f, 12.5f, 11.4f, 12.46f)
                lineTo(11.2f, 12.27f)
                lineTo(2.47f, 3.53f)
                quadTo(2.25f, 3.31f, 2.25f, 3f)
                quadTo(2.25f, 2.69f, 2.47f, 2.47f)
                quadTo(2.69f, 2.25f, 3f, 2.25f)
                quadTo(3.31f, 2.25f, 3.53f, 2.47f)
                close()
                moveTo(4.58f, 19.42f)
                quadTo(-0.83f, 14.02f, 2.65f, 7.22f)
                quadTo(2.79f, 6.94f, 3.08f, 6.85f)
                quadTo(3.38f, 6.75f, 3.66f, 6.89f)
                quadTo(3.93f, 7.03f, 4.03f, 7.33f)
                quadTo(4.12f, 7.62f, 3.98f, 7.9f)
                quadTo(1f, 13.73f, 5.64f, 18.36f)
                quadTo(5.86f, 18.58f, 5.86f, 18.89f)
                quadTo(5.86f, 19.2f, 5.64f, 19.42f)
                quadTo(5.42f, 19.64f, 5.11f, 19.64f)
                quadTo(4.79f, 19.64f, 4.58f, 19.42f)
                close()
                moveTo(6.7f, 17.3f)
                quadTo(3.41f, 14.01f, 4.89f, 9.61f)
                quadTo(4.99f, 9.31f, 5.27f, 9.17f)
                quadTo(5.55f, 9.03f, 5.84f, 9.13f)
                quadTo(6.14f, 9.23f, 6.27f, 9.51f)
                quadTo(6.41f, 9.79f, 6.31f, 10.08f)
                quadTo(5.12f, 13.61f, 7.76f, 16.24f)
                quadTo(7.98f, 16.46f, 7.98f, 16.77f)
                quadTo(7.98f, 17.08f, 7.76f, 17.3f)
                quadTo(7.54f, 17.52f, 7.23f, 17.52f)
                quadTo(6.92f, 17.52f, 6.7f, 17.3f)
                close()
                moveTo(8.82f, 15.18f)
                quadTo(7.75f, 14.12f, 7.54f, 12.63f)
                quadTo(7.5f, 12.33f, 7.69f, 12.08f)
                quadTo(7.88f, 11.83f, 8.18f, 11.79f)
                quadTo(8.49f, 11.74f, 8.74f, 11.93f)
                quadTo(8.99f, 12.12f, 9.03f, 12.43f)
                quadTo(9.17f, 13.41f, 9.88f, 14.12f)
                quadTo(10.1f, 14.34f, 10.1f, 14.65f)
                quadTo(10.1f, 14.96f, 9.88f, 15.18f)
                quadTo(9.66f, 15.4f, 9.35f, 15.4f)
                quadTo(9.04f, 15.4f, 8.82f, 15.18f)
                close()
            }
        }.build()
}
