// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val SpeakerXMark: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "SpeakerXMark",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(6.44f, 7.5f)
                lineTo(10.94f, 3f)
                quadTo(11.65f, 2.29f, 12.57f, 2.67f)
                quadTo(13.5f, 3.06f, 13.5f, 4.06f)
                lineTo(13.5f, 19.94f)
                quadTo(13.5f, 20.94f, 12.57f, 21.32f)
                quadTo(11.65f, 21.71f, 10.94f, 21f)
                lineTo(6.44f, 16.5f)
                lineTo(4.51f, 16.5f)
                quadTo(2.38f, 16.5f, 1.85f, 14.6f)
                quadTo(1.5f, 13.32f, 1.5f, 12f)
                quadTo(1.5f, 10.67f, 1.85f, 9.4f)
                quadTo(2.38f, 7.5f, 4.51f, 7.5f)
                lineTo(6.44f, 7.5f)
                close()
                moveTo(7.28f, 8.78f)
                quadTo(7.06f, 9f, 6.75f, 9f)
                lineTo(4.51f, 9f)
                quadTo(3.52f, 9f, 3.29f, 9.8f)
                quadTo(3f, 10.88f, 3f, 12f)
                quadTo(3f, 13.12f, 3.29f, 14.2f)
                quadTo(3.52f, 15f, 4.51f, 15f)
                lineTo(6.75f, 15f)
                quadTo(7.06f, 15f, 7.28f, 15.22f)
                lineTo(12f, 19.94f)
                lineTo(12f, 4.06f)
                close()
                moveTo(17.78f, 9.22f)
                lineTo(19.5f, 10.94f)
                lineTo(21.22f, 9.22f)
                quadTo(21.44f, 9f, 21.75f, 9f)
                quadTo(22.06f, 9f, 22.28f, 9.22f)
                quadTo(22.5f, 9.44f, 22.5f, 9.75f)
                quadTo(22.5f, 10.06f, 22.28f, 10.28f)
                lineTo(20.56f, 12f)
                lineTo(22.28f, 13.72f)
                quadTo(22.5f, 13.94f, 22.5f, 14.25f)
                quadTo(22.5f, 14.56f, 22.28f, 14.78f)
                quadTo(22.06f, 15f, 21.75f, 15f)
                quadTo(21.44f, 15f, 21.22f, 14.78f)
                lineTo(19.5f, 13.06f)
                lineTo(17.78f, 14.78f)
                quadTo(17.56f, 15f, 17.25f, 15f)
                quadTo(16.94f, 15f, 16.72f, 14.78f)
                quadTo(16.5f, 14.56f, 16.5f, 14.25f)
                quadTo(16.5f, 13.94f, 16.72f, 13.72f)
                lineTo(18.44f, 12f)
                lineTo(16.72f, 10.28f)
                quadTo(16.5f, 10.06f, 16.5f, 9.75f)
                quadTo(16.5f, 9.44f, 16.72f, 9.22f)
                quadTo(16.94f, 9f, 17.25f, 9f)
                quadTo(17.56f, 9f, 17.78f, 9.22f)
                close()
            }
        }.build()
}
