// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val SpeakerWave: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "SpeakerWave",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(6.44f, 7.5f)
                lineTo(10.94f, 3f)
                quadTo(11.65f, 2.29f, 12.57f, 2.67f)
                quadTo(13.5f, 3.06f, 13.5f, 4.06f)
                lineTo(13.5f, 19.94f)
                quadTo(13.5f, 20.94f, 12.57f, 21.32f)
                quadTo(11.65f, 21.71f, 10.94f, 21f)
                lineTo(6.44f, 16.5f)
                lineTo(4.51f, 16.5f)
                quadTo(2.38f, 16.5f, 1.85f, 14.6f)
                quadTo(1.5f, 13.32f, 1.5f, 12f)
                quadTo(1.5f, 10.67f, 1.85f, 9.4f)
                quadTo(2.38f, 7.5f, 4.51f, 7.5f)
                lineTo(6.44f, 7.5f)
                close()
                moveTo(7.28f, 8.78f)
                quadTo(7.06f, 9f, 6.75f, 9f)
                lineTo(4.51f, 9f)
                quadTo(3.52f, 9f, 3.29f, 9.8f)
                quadTo(3f, 10.88f, 3f, 12f)
                quadTo(3f, 13.12f, 3.29f, 14.2f)
                quadTo(3.52f, 15f, 4.51f, 15f)
                lineTo(6.75f, 15f)
                quadTo(7.06f, 15f, 7.28f, 15.22f)
                lineTo(12f, 19.94f)
                lineTo(12f, 4.06f)
                close()
                moveTo(19.64f, 5.11f)
                quadTo(22.5f, 7.96f, 22.5f, 12f)
                quadTo(22.5f, 16.04f, 19.64f, 18.89f)
                quadTo(19.43f, 19.11f, 19.11f, 19.11f)
                quadTo(18.8f, 19.11f, 18.58f, 18.89f)
                quadTo(18.36f, 18.68f, 18.36f, 18.36f)
                quadTo(18.36f, 18.05f, 18.58f, 17.83f)
                quadTo(21f, 15.42f, 21f, 12f)
                quadTo(21f, 8.58f, 18.58f, 6.17f)
                quadTo(18.36f, 5.95f, 18.36f, 5.64f)
                quadTo(18.36f, 5.33f, 18.58f, 5.11f)
                quadTo(18.8f, 4.89f, 19.11f, 4.89f)
                quadTo(19.43f, 4.89f, 19.64f, 5.11f)
                close()
                moveTo(16.99f, 7.76f)
                quadTo(18.75f, 9.52f, 18.75f, 12f)
                quadTo(18.75f, 14.48f, 16.99f, 16.24f)
                quadTo(16.77f, 16.46f, 16.46f, 16.46f)
                quadTo(16.15f, 16.46f, 15.93f, 16.24f)
                quadTo(15.71f, 16.02f, 15.71f, 15.71f)
                quadTo(15.71f, 15.4f, 15.93f, 15.18f)
                quadTo(17.25f, 13.86f, 17.25f, 12f)
                quadTo(17.25f, 10.14f, 15.93f, 8.82f)
                quadTo(15.71f, 8.6f, 15.71f, 8.29f)
                quadTo(15.71f, 7.98f, 15.93f, 7.76f)
                quadTo(16.15f, 7.54f, 16.46f, 7.54f)
                quadTo(16.77f, 7.54f, 16.99f, 7.76f)
                close()
            }
        }.build()
}
