// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Strikethrough: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "Strikethrough",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(3.75f, 11.25f)
                lineTo(8.51f, 11.25f)
                quadTo(7.87f, 10.77f, 7.36f, 10.18f)
                quadTo(5.68f, 8.24f, 6.23f, 6.19f)
                quadTo(6.77f, 4.16f, 9.16f, 3.31f)
                quadTo(11.39f, 2.52f, 14.01f, 3.23f)
                quadTo(15.6f, 3.64f, 16.94f, 4.6f)
                quadTo(17.19f, 4.78f, 17.24f, 5.09f)
                quadTo(17.29f, 5.39f, 17.11f, 5.65f)
                quadTo(16.93f, 5.9f, 16.62f, 5.95f)
                quadTo(16.32f, 6f, 16.06f, 5.82f)
                quadTo(14.95f, 5.03f, 13.62f, 4.68f)
                quadTo(11.45f, 4.09f, 9.66f, 4.73f)
                quadTo(8.02f, 5.31f, 7.68f, 6.58f)
                quadTo(7.34f, 7.86f, 8.49f, 9.19f)
                quadTo(9.72f, 10.62f, 11.88f, 11.2f)
                quadTo(11.98f, 11.22f, 12.09f, 11.25f)
                lineTo(20.25f, 11.25f)
                quadTo(20.56f, 11.25f, 20.78f, 11.47f)
                quadTo(21f, 11.69f, 21f, 12f)
                quadTo(21f, 12.31f, 20.78f, 12.53f)
                quadTo(20.56f, 12.75f, 20.25f, 12.75f)
                lineTo(12.06f, 12.75f)
                quadTo(12.01f, 12.75f, 11.96f, 12.75f)
                lineTo(3.75f, 12.75f)
                quadTo(3.44f, 12.75f, 3.22f, 12.53f)
                quadTo(3f, 12.31f, 3f, 12f)
                quadTo(3f, 11.69f, 3.22f, 11.47f)
                quadTo(3.44f, 11.25f, 3.75f, 11.25f)
                close()
                moveTo(6.99f, 17.32f)
                quadTo(8.22f, 18.75f, 10.38f, 19.32f)
                quadTo(12.55f, 19.91f, 14.34f, 19.27f)
                quadTo(15.98f, 18.69f, 16.32f, 17.42f)
                quadTo(16.58f, 16.45f, 15.94f, 15.39f)
                quadTo(15.78f, 15.12f, 15.85f, 14.82f)
                quadTo(15.92f, 14.52f, 16.19f, 14.36f)
                quadTo(16.45f, 14.2f, 16.76f, 14.27f)
                quadTo(17.06f, 14.34f, 17.22f, 14.61f)
                quadTo(18.2f, 16.22f, 17.77f, 17.81f)
                quadTo(17.23f, 19.84f, 14.84f, 20.69f)
                quadTo(12.61f, 21.48f, 9.99f, 20.77f)
                quadTo(7.39f, 20.07f, 5.85f, 18.3f)
                quadTo(5.65f, 18.07f, 5.67f, 17.76f)
                quadTo(5.69f, 17.45f, 5.93f, 17.24f)
                quadTo(6.16f, 17.04f, 6.47f, 17.06f)
                quadTo(6.78f, 17.08f, 6.99f, 17.32f)
                close()
            }
        }.build()
}
