// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val TableCells: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "TableCells",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(3.38f, 20.25f)
                quadTo(1.5f, 20.25f, 1.5f, 18.38f)
                lineTo(1.5f, 5.62f)
                quadTo(1.5f, 3.75f, 3.38f, 3.75f)
                lineTo(20.62f, 3.75f)
                quadTo(22.5f, 3.75f, 22.5f, 5.62f)
                lineTo(22.5f, 18.38f)
                quadTo(22.5f, 20.25f, 20.62f, 20.25f)
                close()
                moveTo(21f, 5.62f)
                quadTo(21f, 5.25f, 20.62f, 5.25f)
                lineTo(3.38f, 5.25f)
                quadTo(3f, 5.25f, 3f, 5.62f)
                lineTo(3f, 7.12f)
                quadTo(3f, 7.5f, 3.38f, 7.5f)
                lineTo(20.62f, 7.5f)
                quadTo(21f, 7.5f, 21f, 7.12f)
                close()
                moveTo(3.38f, 9f)
                quadTo(3f, 9f, 3f, 9.38f)
                lineTo(3f, 10.88f)
                quadTo(3f, 11.25f, 3.38f, 11.25f)
                lineTo(10.88f, 11.25f)
                quadTo(11.25f, 11.25f, 11.25f, 10.88f)
                lineTo(11.25f, 9.38f)
                quadTo(11.25f, 9f, 10.88f, 9f)
                close()
                moveTo(20.62f, 9f)
                lineTo(13.12f, 9f)
                quadTo(12.75f, 9f, 12.75f, 9.38f)
                lineTo(12.75f, 10.88f)
                quadTo(12.75f, 11.25f, 13.12f, 11.25f)
                lineTo(20.62f, 11.25f)
                quadTo(21f, 11.25f, 21f, 10.88f)
                lineTo(21f, 9.38f)
                quadTo(21f, 9f, 20.62f, 9f)
                close()
                moveTo(3.38f, 12.75f)
                quadTo(3f, 12.75f, 3f, 13.12f)
                lineTo(3f, 14.62f)
                quadTo(3f, 15f, 3.38f, 15f)
                lineTo(10.88f, 15f)
                quadTo(11.25f, 15f, 11.25f, 14.62f)
                lineTo(11.25f, 13.12f)
                quadTo(11.25f, 12.75f, 10.88f, 12.75f)
                close()
                moveTo(13.12f, 12.75f)
                quadTo(12.75f, 12.75f, 12.75f, 13.12f)
                lineTo(12.75f, 14.62f)
                quadTo(12.75f, 15f, 13.12f, 15f)
                lineTo(20.62f, 15f)
                quadTo(21f, 15f, 21f, 14.62f)
                lineTo(21f, 13.12f)
                quadTo(21f, 12.75f, 20.62f, 12.75f)
                close()
                moveTo(3.38f, 18.75f)
                lineTo(10.88f, 18.75f)
                quadTo(11.25f, 18.75f, 11.25f, 18.38f)
                lineTo(11.25f, 16.88f)
                quadTo(11.25f, 16.5f, 10.88f, 16.5f)
                lineTo(3.38f, 16.5f)
                quadTo(3f, 16.5f, 3f, 16.88f)
                lineTo(3f, 18.38f)
                quadTo(3f, 18.75f, 3.38f, 18.75f)
                close()
                moveTo(21f, 18.38f)
                lineTo(21f, 16.88f)
                quadTo(21f, 16.5f, 20.62f, 16.5f)
                lineTo(13.12f, 16.5f)
                quadTo(12.75f, 16.5f, 12.75f, 16.88f)
                lineTo(12.75f, 18.38f)
                quadTo(12.75f, 18.75f, 13.12f, 18.75f)
                lineTo(20.62f, 18.75f)
                quadTo(21f, 18.75f, 21f, 18.38f)
                close()
            }
        }.build()
}
