// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Trash: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "Trash",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(19.34f, 5.05f)
                lineTo(19.34f, 5.05f)
                quadTo(19.88f, 5.13f, 20.38f, 5.22f)
                quadTo(20.68f, 5.27f, 20.86f, 5.52f)
                quadTo(21.04f, 5.78f, 20.99f, 6.08f)
                quadTo(20.94f, 6.39f, 20.68f, 6.57f)
                quadTo(20.43f, 6.75f, 20.12f, 6.7f)
                quadTo(20.02f, 6.68f, 19.91f, 6.66f)
                lineTo(18.91f, 19.73f)
                quadTo(18.69f, 22.5f, 15.92f, 22.5f)
                lineTo(8.08f, 22.5f)
                quadTo(5.31f, 22.5f, 5.09f, 19.73f)
                lineTo(4.09f, 6.66f)
                quadTo(3.98f, 6.68f, 3.88f, 6.69f)
                quadTo(3.57f, 6.75f, 3.32f, 6.57f)
                quadTo(3.06f, 6.39f, 3.01f, 6.08f)
                quadTo(2.96f, 5.78f, 3.14f, 5.52f)
                quadTo(3.32f, 5.27f, 3.62f, 5.22f)
                quadTo(4.13f, 5.13f, 4.63f, 5.05f)
                quadTo(4.65f, 5.05f, 4.67f, 5.05f)
                quadTo(6.08f, 4.83f, 7.5f, 4.7f)
                lineTo(7.5f, 4.48f)
                quadTo(7.5f, 1.61f, 10.32f, 1.53f)
                quadTo(12f, 1.47f, 13.68f, 1.53f)
                quadTo(16.5f, 1.61f, 16.5f, 4.48f)
                lineTo(16.5f, 4.7f)
                quadTo(17.93f, 4.83f, 19.34f, 5.05f)
                close()
                moveTo(15.71f, 6.14f)
                quadTo(15.69f, 6.14f, 15.66f, 6.14f)
                quadTo(12f, 5.86f, 8.34f, 6.14f)
                quadTo(8.31f, 6.14f, 8.29f, 6.14f)
                quadTo(6.93f, 6.25f, 5.57f, 6.43f)
                lineTo(6.59f, 19.61f)
                quadTo(6.7f, 21f, 8.08f, 21f)
                lineTo(15.92f, 21f)
                quadTo(17.3f, 21f, 17.41f, 19.61f)
                lineTo(18.43f, 6.43f)
                quadTo(17.07f, 6.25f, 15.71f, 6.14f)
                close()
                moveTo(15.49f, 9.03f)
                lineTo(15.14f, 18.03f)
                quadTo(15.13f, 18.34f, 14.9f, 18.55f)
                quadTo(14.68f, 18.76f, 14.37f, 18.75f)
                quadTo(14.05f, 18.74f, 13.84f, 18.51f)
                quadTo(13.63f, 18.28f, 13.64f, 17.97f)
                lineTo(13.99f, 8.97f)
                quadTo(14f, 8.66f, 14.23f, 8.45f)
                quadTo(14.46f, 8.24f, 14.77f, 8.25f)
                quadTo(15.08f, 8.26f, 15.29f, 8.49f)
                quadTo(15.5f, 8.72f, 15.49f, 9.03f)
                close()
                moveTo(8.86f, 18.03f)
                lineTo(8.51f, 9.03f)
                quadTo(8.5f, 8.72f, 8.71f, 8.49f)
                quadTo(8.92f, 8.26f, 9.23f, 8.25f)
                quadTo(9.54f, 8.24f, 9.77f, 8.45f)
                quadTo(10f, 8.66f, 10.01f, 8.97f)
                lineTo(10.36f, 17.97f)
                quadTo(10.37f, 18.28f, 10.16f, 18.51f)
                quadTo(9.95f, 18.74f, 9.63f, 18.75f)
                quadTo(9.32f, 18.76f, 9.1f, 18.55f)
                quadTo(8.87f, 18.34f, 8.86f, 18.03f)
                close()
                moveTo(9f, 4.59f)
                quadTo(12f, 4.41f, 15f, 4.59f)
                lineTo(15f, 4.48f)
                quadTo(15f, 3.07f, 13.64f, 3.03f)
                quadTo(12f, 2.97f, 10.36f, 3.03f)
                quadTo(9f, 3.07f, 9f, 4.48f)
                lineTo(9f, 4.59f)
                close()
            }
        }.build()
}
