// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Truck: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "Truck",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(1.5f, 14.25f)
                lineTo(1.5f, 6.62f)
                quadTo(1.49f, 4.94f, 3.16f, 4.76f)
                quadTo(8.25f, 4.24f, 13.34f, 4.76f)
                quadTo(15f, 4.93f, 15f, 6.62f)
                lineTo(15f, 6.82f)
                lineTo(16.92f, 6.82f)
                quadTo(16.94f, 6.82f, 16.96f, 6.82f)
                quadTo(18.32f, 6.89f, 19.12f, 8f)
                quadTo(22.14f, 12.32f, 22.46f, 17.58f)
                quadTo(22.51f, 18.38f, 21.95f, 18.95f)
                quadTo(21.41f, 19.5f, 20.62f, 19.5f)
                lineTo(20.17f, 19.5f)
                quadTo(19.84f, 21f, 18f, 21f)
                quadTo(16.16f, 21f, 15.83f, 19.5f)
                lineTo(8.92f, 19.5f)
                quadTo(8.59f, 21f, 6.75f, 21f)
                quadTo(4.91f, 21f, 4.58f, 19.5f)
                lineTo(3.38f, 19.5f)
                quadTo(1.5f, 19.5f, 1.5f, 17.62f)
                lineTo(1.5f, 14.25f)
                close()
                moveTo(13.5f, 6.62f)
                quadTo(13.5f, 6.29f, 13.19f, 6.25f)
                quadTo(8.25f, 5.74f, 3.31f, 6.25f)
                quadTo(3f, 6.29f, 3f, 6.61f)
                lineTo(3f, 13.5f)
                lineTo(13.5f, 13.5f)
                lineTo(13.5f, 6.62f)
                close()
                moveTo(15f, 18f)
                lineTo(15.83f, 18f)
                quadTo(16.16f, 16.5f, 18f, 16.5f)
                quadTo(19.84f, 16.5f, 20.17f, 18f)
                lineTo(20.62f, 18f)
                quadTo(20.78f, 18f, 20.88f, 17.89f)
                quadTo(20.98f, 17.8f, 20.97f, 17.67f)
                quadTo(20.67f, 12.83f, 17.89f, 8.86f)
                quadTo(17.53f, 8.36f, 16.9f, 8.32f)
                lineTo(15f, 8.32f)
                lineTo(15f, 18f)
                close()
                moveTo(3f, 15f)
                lineTo(3f, 17.62f)
                quadTo(3f, 18f, 3.38f, 18f)
                lineTo(4.58f, 18f)
                quadTo(4.91f, 16.5f, 6.75f, 16.5f)
                quadTo(8.59f, 16.5f, 8.92f, 18f)
                lineTo(13.5f, 18f)
                lineTo(13.5f, 15f)
                lineTo(3f, 15f)
                close()
                moveTo(7.5f, 18.75f)
                quadTo(7.5f, 18f, 6.75f, 18f)
                quadTo(6f, 18f, 6f, 18.75f)
                quadTo(6f, 19.5f, 6.75f, 19.5f)
                quadTo(7.5f, 19.5f, 7.5f, 18.75f)
                close()
                moveTo(18.75f, 18.75f)
                quadTo(18.75f, 18f, 18f, 18f)
                quadTo(17.25f, 18f, 17.25f, 18.75f)
                quadTo(17.25f, 19.5f, 18f, 19.5f)
                quadTo(18.75f, 19.5f, 18.75f, 18.75f)
                close()
            }
        }.build()
}
