// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val UserGroup: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "UserGroup",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(18.71f, 19.5f)
                lineTo(18.71f, 19.5f)
                quadTo(18.66f, 19.88f, 18.34f, 20.07f)
                quadTo(15.39f, 21.75f, 12f, 21.75f)
                quadTo(8.6f, 21.75f, 5.66f, 20.07f)
                quadTo(5.33f, 19.88f, 5.29f, 19.5f)
                quadTo(3.62f, 19.51f, 2.01f, 18.95f)
                quadTo(1.55f, 18.79f, 1.51f, 18.3f)
                quadTo(1.32f, 15.95f, 3.37f, 14.76f)
                quadTo(5.08f, 13.77f, 6.72f, 14.53f)
                quadTo(8.66f, 12f, 12f, 12f)
                quadTo(15.34f, 12f, 17.28f, 14.53f)
                quadTo(18.93f, 13.76f, 20.64f, 14.76f)
                quadTo(22.68f, 15.94f, 22.49f, 18.3f)
                quadTo(22.45f, 18.79f, 21.99f, 18.95f)
                quadTo(20.39f, 19.51f, 18.71f, 19.5f)
                close()
                moveTo(16.43f, 15.93f)
                lineTo(16.43f, 15.92f)
                quadTo(14.88f, 13.5f, 12f, 13.5f)
                quadTo(9.13f, 13.5f, 7.58f, 15.91f)
                quadTo(7.58f, 15.93f, 7.57f, 15.94f)
                quadTo(7.56f, 15.95f, 7.55f, 15.96f)
                quadTo(6.76f, 17.21f, 6.75f, 18.7f)
                quadTo(6.75f, 18.74f, 6.75f, 18.77f)
                quadTo(6.75f, 18.86f, 6.75f, 18.95f)
                quadTo(9.2f, 20.25f, 12f, 20.25f)
                quadTo(14.8f, 20.25f, 17.25f, 18.95f)
                quadTo(17.25f, 18.86f, 17.25f, 18.76f)
                lineTo(17.25f, 18.74f)
                quadTo(17.25f, 18.71f, 17.25f, 18.68f)
                quadTo(17.23f, 17.19f, 16.43f, 15.93f)
                close()
                moveTo(15.75f, 6.75f)
                quadTo(15.75f, 10.5f, 12f, 10.5f)
                quadTo(8.25f, 10.5f, 8.25f, 6.75f)
                quadTo(8.25f, 3f, 12f, 3f)
                quadTo(15.75f, 3f, 15.75f, 6.75f)
                close()
                moveTo(8.25f, 9.75f)
                quadTo(8.25f, 12.75f, 5.25f, 12.75f)
                quadTo(2.25f, 12.75f, 2.25f, 9.75f)
                quadTo(2.25f, 6.75f, 5.25f, 6.75f)
                quadTo(8.25f, 6.75f, 8.25f, 9.75f)
                close()
                moveTo(21.75f, 9.75f)
                quadTo(21.75f, 12.75f, 18.75f, 12.75f)
                quadTo(15.75f, 12.75f, 15.75f, 9.75f)
                quadTo(15.75f, 6.75f, 18.75f, 6.75f)
                quadTo(21.75f, 6.75f, 21.75f, 9.75f)
                close()
                moveTo(14.25f, 6.75f)
                quadTo(14.25f, 4.5f, 12f, 4.5f)
                quadTo(9.75f, 4.5f, 9.75f, 6.75f)
                quadTo(9.75f, 9f, 12f, 9f)
                quadTo(14.25f, 9f, 14.25f, 6.75f)
                close()
                moveTo(6.75f, 9.75f)
                quadTo(6.75f, 8.25f, 5.25f, 8.25f)
                quadTo(3.75f, 8.25f, 3.75f, 9.75f)
                quadTo(3.75f, 11.25f, 5.25f, 11.25f)
                quadTo(6.75f, 11.25f, 6.75f, 9.75f)
                close()
                moveTo(20.25f, 9.75f)
                quadTo(20.25f, 8.25f, 18.75f, 8.25f)
                quadTo(17.25f, 8.25f, 17.25f, 9.75f)
                quadTo(17.25f, 11.25f, 18.75f, 11.25f)
                quadTo(20.25f, 11.25f, 20.25f, 9.75f)
                close()
                moveTo(18.09f, 15.83f)
                quadTo(18.59f, 16.86f, 18.71f, 18f)
                quadTo(19.87f, 18.01f, 20.99f, 17.69f)
                quadTo(20.89f, 16.64f, 19.88f, 16.05f)
                quadTo(18.97f, 15.52f, 18.09f, 15.83f)
                close()
                moveTo(5.29f, 18f)
                quadTo(5.41f, 16.86f, 5.91f, 15.83f)
                quadTo(5.03f, 15.53f, 4.12f, 16.05f)
                quadTo(3.12f, 16.64f, 3.01f, 17.69f)
                quadTo(4.13f, 18.01f, 5.29f, 18f)
                close()
            }
        }.build()
}
