// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val UserPlus: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "UserPlus",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(2.25f, 19.23f)
                lineTo(2.25f, 19.12f)
                quadTo(2.25f, 16.17f, 4.34f, 14.09f)
                quadTo(6.42f, 12f, 9.38f, 12f)
                quadTo(12.33f, 12f, 14.41f, 14.09f)
                quadTo(16.5f, 16.17f, 16.5f, 19.12f)
                lineTo(16.5f, 19.23f)
                quadTo(16.5f, 19.66f, 16.14f, 19.88f)
                quadTo(13.02f, 21.76f, 9.37f, 21.75f)
                quadTo(5.76f, 21.75f, 2.67f, 19.91f)
                quadTo(2.56f, 19.86f, 2.47f, 19.77f)
                quadTo(2.25f, 19.55f, 2.25f, 19.23f)
                close()
                moveTo(3.76f, 18.81f)
                quadTo(6.36f, 20.25f, 9.38f, 20.25f)
                quadTo(12.38f, 20.25f, 14.99f, 18.81f)
                quadTo(14.89f, 16.68f, 13.35f, 15.15f)
                quadTo(11.71f, 13.5f, 9.38f, 13.5f)
                quadTo(7.04f, 13.5f, 5.4f, 15.15f)
                quadTo(3.86f, 16.68f, 3.76f, 18.81f)
                close()
                moveTo(13.5f, 6.38f)
                quadTo(13.5f, 8.08f, 12.29f, 9.29f)
                quadTo(11.08f, 10.5f, 9.38f, 10.5f)
                quadTo(7.67f, 10.5f, 6.46f, 9.29f)
                quadTo(5.25f, 8.08f, 5.25f, 6.38f)
                quadTo(5.25f, 4.67f, 6.46f, 3.46f)
                quadTo(7.67f, 2.25f, 9.38f, 2.25f)
                quadTo(11.08f, 2.25f, 12.29f, 3.46f)
                quadTo(13.5f, 4.67f, 13.5f, 6.38f)
                close()
                moveTo(12f, 6.38f)
                quadTo(12f, 3.75f, 9.38f, 3.75f)
                quadTo(6.75f, 3.75f, 6.75f, 6.38f)
                quadTo(6.75f, 9f, 9.38f, 9f)
                quadTo(12f, 9f, 12f, 6.38f)
                close()
                moveTo(18.75f, 7.5f)
                lineTo(18.75f, 9.75f)
                lineTo(21f, 9.75f)
                quadTo(21.31f, 9.75f, 21.53f, 9.97f)
                quadTo(21.75f, 10.19f, 21.75f, 10.5f)
                quadTo(21.75f, 10.81f, 21.53f, 11.03f)
                quadTo(21.31f, 11.25f, 21f, 11.25f)
                lineTo(18.75f, 11.25f)
                lineTo(18.75f, 13.5f)
                quadTo(18.75f, 13.81f, 18.53f, 14.03f)
                quadTo(18.31f, 14.25f, 18f, 14.25f)
                quadTo(17.69f, 14.25f, 17.47f, 14.03f)
                quadTo(17.25f, 13.81f, 17.25f, 13.5f)
                lineTo(17.25f, 11.25f)
                lineTo(15f, 11.25f)
                quadTo(14.69f, 11.25f, 14.47f, 11.03f)
                quadTo(14.25f, 10.81f, 14.25f, 10.5f)
                quadTo(14.25f, 10.19f, 14.47f, 9.97f)
                quadTo(14.69f, 9.75f, 15f, 9.75f)
                lineTo(17.25f, 9.75f)
                lineTo(17.25f, 7.5f)
                quadTo(17.25f, 7.19f, 17.47f, 6.97f)
                quadTo(17.69f, 6.75f, 18f, 6.75f)
                quadTo(18.31f, 6.75f, 18.53f, 6.97f)
                quadTo(18.75f, 7.19f, 18.75f, 7.5f)
                close()
            }
        }.build()
}
