// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Variable: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "Variable",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(7.86f, 8.25f)
                lineTo(9.3f, 7.36f)
                quadTo(9.92f, 6.98f, 10.6f, 7.22f)
                quadTo(11.28f, 7.47f, 11.51f, 8.16f)
                lineTo(12.23f, 10.31f)
                lineTo(13.6f, 8.25f)
                quadTo(14.72f, 6.57f, 16.58f, 7.35f)
                lineTo(16.79f, 7.44f)
                quadTo(17.08f, 7.56f, 17.2f, 7.85f)
                quadTo(17.31f, 8.14f, 17.19f, 8.43f)
                quadTo(17.07f, 8.71f, 16.78f, 8.83f)
                quadTo(16.49f, 8.95f, 16.21f, 8.82f)
                lineTo(15.99f, 8.73f)
                quadTo(15.28f, 8.43f, 14.85f, 9.08f)
                lineTo(12.83f, 12.11f)
                lineTo(13.91f, 15.37f)
                lineTo(15.36f, 14.48f)
                quadTo(15.62f, 14.31f, 15.92f, 14.38f)
                quadTo(16.23f, 14.46f, 16.39f, 14.72f)
                quadTo(16.55f, 14.99f, 16.48f, 15.29f)
                quadTo(16.41f, 15.59f, 16.14f, 15.75f)
                lineTo(14.7f, 16.64f)
                quadTo(14.08f, 17.02f, 13.4f, 16.77f)
                quadTo(12.72f, 16.53f, 12.49f, 15.84f)
                lineTo(11.77f, 13.69f)
                lineTo(10.4f, 15.75f)
                quadTo(9.28f, 17.43f, 7.42f, 16.65f)
                lineTo(7.21f, 16.56f)
                quadTo(6.92f, 16.43f, 6.8f, 16.15f)
                quadTo(6.69f, 15.86f, 6.81f, 15.57f)
                quadTo(6.93f, 15.29f, 7.22f, 15.17f)
                quadTo(7.51f, 15.05f, 7.79f, 15.17f)
                lineTo(8.01f, 15.26f)
                quadTo(8.72f, 15.57f, 9.15f, 14.92f)
                lineTo(11.17f, 11.89f)
                lineTo(10.09f, 8.63f)
                lineTo(8.64f, 9.52f)
                quadTo(8.38f, 9.69f, 8.08f, 9.62f)
                quadTo(7.78f, 9.54f, 7.61f, 9.28f)
                quadTo(7.45f, 9.01f, 7.52f, 8.71f)
                quadTo(7.59f, 8.41f, 7.86f, 8.25f)
                close()
                moveTo(5.44f, 3.28f)
                quadTo(3.75f, 7.47f, 3.75f, 12f)
                quadTo(3.75f, 16.54f, 5.44f, 20.72f)
                quadTo(5.56f, 21.01f, 5.44f, 21.29f)
                quadTo(5.31f, 21.58f, 5.03f, 21.7f)
                quadTo(4.74f, 21.81f, 4.45f, 21.69f)
                quadTo(4.17f, 21.57f, 4.05f, 21.28f)
                quadTo(2.25f, 16.83f, 2.25f, 12f)
                quadTo(2.24f, 7.18f, 4.05f, 2.72f)
                quadTo(4.17f, 2.43f, 4.45f, 2.31f)
                quadTo(4.74f, 2.19f, 5.03f, 2.31f)
                quadTo(5.31f, 2.42f, 5.43f, 2.71f)
                quadTo(5.56f, 2.99f, 5.44f, 3.28f)
                close()
                moveTo(20.21f, 2.75f)
                quadTo(21.75f, 7.19f, 21.75f, 12f)
                quadTo(21.75f, 16.81f, 20.21f, 21.25f)
                quadTo(20.11f, 21.54f, 19.83f, 21.68f)
                quadTo(19.55f, 21.81f, 19.25f, 21.71f)
                quadTo(18.96f, 21.61f, 18.82f, 21.33f)
                quadTo(18.69f, 21.05f, 18.79f, 20.75f)
                quadTo(20.25f, 16.56f, 20.25f, 12f)
                quadTo(20.25f, 7.44f, 18.79f, 3.25f)
                quadTo(18.69f, 2.95f, 18.82f, 2.67f)
                quadTo(18.96f, 2.39f, 19.25f, 2.29f)
                quadTo(19.55f, 2.19f, 19.83f, 2.33f)
                quadTo(20.11f, 2.46f, 20.21f, 2.75f)
                close()
            }
        }.build()
}
