// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val VideoCameraSlash: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "VideoCameraSlash",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(2.03f, 3.97f)
                lineTo(2.97f, 4.91f)
                quadTo(3.65f, 4.5f, 4.5f, 4.5f)
                lineTo(13.5f, 4.5f)
                quadTo(16.5f, 4.5f, 16.5f, 7.5f)
                lineTo(16.5f, 8.69f)
                lineTo(19.94f, 5.25f)
                quadTo(20.65f, 4.54f, 21.57f, 4.92f)
                quadTo(22.5f, 5.31f, 22.5f, 6.31f)
                lineTo(22.5f, 17.69f)
                quadTo(22.5f, 18.69f, 21.57f, 19.07f)
                quadTo(20.65f, 19.46f, 19.94f, 18.75f)
                lineTo(16.5f, 15.31f)
                lineTo(16.5f, 16.5f)
                quadTo(16.5f, 17.35f, 16.09f, 18.03f)
                lineTo(17.03f, 18.97f)
                quadTo(17.25f, 19.19f, 17.25f, 19.5f)
                quadTo(17.25f, 19.81f, 17.03f, 20.03f)
                quadTo(16.81f, 20.25f, 16.5f, 20.25f)
                quadTo(16.19f, 20.25f, 15.97f, 20.03f)
                lineTo(0.97f, 5.03f)
                quadTo(0.75f, 4.81f, 0.75f, 4.5f)
                quadTo(0.75f, 4.19f, 0.97f, 3.97f)
                quadTo(1.19f, 3.75f, 1.5f, 3.75f)
                quadTo(1.81f, 3.75f, 2.03f, 3.97f)
                close()
                moveTo(4.11f, 6.05f)
                lineTo(14.95f, 16.89f)
                quadTo(15f, 16.71f, 15f, 16.5f)
                lineTo(15f, 7.5f)
                quadTo(15f, 6f, 13.5f, 6f)
                lineTo(4.5f, 6f)
                quadTo(4.29f, 6f, 4.11f, 6.05f)
                close()
                moveTo(16.5f, 13.19f)
                lineTo(21f, 17.69f)
                lineTo(21f, 6.31f)
                lineTo(16.5f, 10.81f)
                lineTo(16.5f, 13.19f)
                close()
                moveTo(12f, 19.5f)
                lineTo(4.5f, 19.5f)
                quadTo(1.5f, 19.5f, 1.5f, 16.5f)
                lineTo(1.5f, 9f)
                quadTo(1.5f, 8.69f, 1.72f, 8.47f)
                quadTo(1.94f, 8.25f, 2.25f, 8.25f)
                quadTo(2.56f, 8.25f, 2.78f, 8.47f)
                quadTo(3f, 8.69f, 3f, 9f)
                lineTo(3f, 16.5f)
                quadTo(3f, 18f, 4.5f, 18f)
                lineTo(12f, 18f)
                quadTo(12.31f, 18f, 12.53f, 18.22f)
                quadTo(12.75f, 18.44f, 12.75f, 18.75f)
                quadTo(12.75f, 19.06f, 12.53f, 19.28f)
                quadTo(12.31f, 19.5f, 12f, 19.5f)
                close()
            }
        }.build()
}
