// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val ViewfinderCircle: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "ViewfinderCircle",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(15.75f, 12f)
                quadTo(15.75f, 15.75f, 12f, 15.75f)
                quadTo(8.25f, 15.75f, 8.25f, 12f)
                quadTo(8.25f, 8.25f, 12f, 8.25f)
                quadTo(15.75f, 8.25f, 15.75f, 12f)
                close()
                moveTo(14.25f, 12f)
                quadTo(14.25f, 9.75f, 12f, 9.75f)
                quadTo(9.75f, 9.75f, 9.75f, 12f)
                quadTo(9.75f, 14.25f, 12f, 14.25f)
                quadTo(14.25f, 14.25f, 14.25f, 12f)
                close()
                moveTo(21f, 16.5f)
                lineTo(21f, 18f)
                quadTo(21f, 21f, 18f, 21f)
                lineTo(16.5f, 21f)
                quadTo(16.19f, 21f, 15.97f, 20.78f)
                quadTo(15.75f, 20.56f, 15.75f, 20.25f)
                quadTo(15.75f, 19.94f, 15.97f, 19.72f)
                quadTo(16.19f, 19.5f, 16.5f, 19.5f)
                lineTo(18f, 19.5f)
                quadTo(19.5f, 19.5f, 19.5f, 18f)
                lineTo(19.5f, 16.5f)
                quadTo(19.5f, 16.19f, 19.72f, 15.97f)
                quadTo(19.94f, 15.75f, 20.25f, 15.75f)
                quadTo(20.56f, 15.75f, 20.78f, 15.97f)
                quadTo(21f, 16.19f, 21f, 16.5f)
                close()
                moveTo(16.5f, 3f)
                lineTo(18f, 3f)
                quadTo(21f, 3f, 21f, 6f)
                lineTo(21f, 7.5f)
                quadTo(21f, 7.81f, 20.78f, 8.03f)
                quadTo(20.56f, 8.25f, 20.25f, 8.25f)
                quadTo(19.94f, 8.25f, 19.72f, 8.03f)
                quadTo(19.5f, 7.81f, 19.5f, 7.5f)
                lineTo(19.5f, 6f)
                quadTo(19.5f, 4.5f, 18f, 4.5f)
                lineTo(16.5f, 4.5f)
                quadTo(16.19f, 4.5f, 15.97f, 4.28f)
                quadTo(15.75f, 4.06f, 15.75f, 3.75f)
                quadTo(15.75f, 3.44f, 15.97f, 3.22f)
                quadTo(16.19f, 3f, 16.5f, 3f)
                close()
                moveTo(7.5f, 21f)
                lineTo(6f, 21f)
                quadTo(3f, 21f, 3f, 18f)
                lineTo(3f, 16.5f)
                quadTo(3f, 16.19f, 3.22f, 15.97f)
                quadTo(3.44f, 15.75f, 3.75f, 15.75f)
                quadTo(4.06f, 15.75f, 4.28f, 15.97f)
                quadTo(4.5f, 16.19f, 4.5f, 16.5f)
                lineTo(4.5f, 18f)
                quadTo(4.5f, 19.5f, 6f, 19.5f)
                lineTo(7.5f, 19.5f)
                quadTo(7.81f, 19.5f, 8.03f, 19.72f)
                quadTo(8.25f, 19.94f, 8.25f, 20.25f)
                quadTo(8.25f, 20.56f, 8.03f, 20.78f)
                quadTo(7.81f, 21f, 7.5f, 21f)
                close()
                moveTo(7.5f, 4.5f)
                lineTo(6f, 4.5f)
                quadTo(4.5f, 4.5f, 4.5f, 6f)
                lineTo(4.5f, 7.5f)
                quadTo(4.5f, 7.81f, 4.28f, 8.03f)
                quadTo(4.06f, 8.25f, 3.75f, 8.25f)
                quadTo(3.44f, 8.25f, 3.22f, 8.03f)
                quadTo(3f, 7.81f, 3f, 7.5f)
                lineTo(3f, 6f)
                quadTo(3f, 3f, 6f, 3f)
                lineTo(7.5f, 3f)
                quadTo(7.81f, 3f, 8.03f, 3.22f)
                quadTo(8.25f, 3.44f, 8.25f, 3.75f)
                quadTo(8.25f, 4.06f, 8.03f, 4.28f)
                quadTo(7.81f, 4.5f, 7.5f, 4.5f)
                close()
            }
        }.build()
}
