// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Wifi: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "Wifi",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(1.39f, 8.14f)
                quadTo(5.79f, 3.75f, 12f, 3.75f)
                quadTo(18.21f, 3.75f, 22.61f, 8.14f)
                quadTo(22.83f, 8.36f, 22.83f, 8.67f)
                quadTo(22.83f, 8.98f, 22.61f, 9.2f)
                quadTo(22.39f, 9.42f, 22.08f, 9.42f)
                quadTo(21.77f, 9.42f, 21.55f, 9.2f)
                quadTo(17.59f, 5.25f, 12f, 5.25f)
                quadTo(6.41f, 5.25f, 2.45f, 9.2f)
                quadTo(2.23f, 9.42f, 1.92f, 9.42f)
                quadTo(1.61f, 9.42f, 1.39f, 9.2f)
                quadTo(1.17f, 8.98f, 1.17f, 8.67f)
                quadTo(1.17f, 8.36f, 1.39f, 8.14f)
                close()
                moveTo(4.58f, 11.33f)
                quadTo(7.65f, 8.25f, 12f, 8.25f)
                quadTo(16.35f, 8.25f, 19.42f, 11.33f)
                quadTo(19.64f, 11.54f, 19.64f, 11.86f)
                quadTo(19.64f, 12.17f, 19.42f, 12.39f)
                quadTo(19.2f, 12.61f, 18.89f, 12.61f)
                quadTo(18.58f, 12.61f, 18.36f, 12.39f)
                quadTo(15.73f, 9.75f, 12f, 9.75f)
                quadTo(8.27f, 9.75f, 5.64f, 12.39f)
                quadTo(5.42f, 12.61f, 5.11f, 12.61f)
                quadTo(4.79f, 12.61f, 4.58f, 12.39f)
                quadTo(4.36f, 12.17f, 4.36f, 11.86f)
                quadTo(4.36f, 11.54f, 4.58f, 11.33f)
                close()
                moveTo(7.76f, 14.51f)
                quadTo(9.52f, 12.75f, 12f, 12.75f)
                quadTo(14.48f, 12.75f, 16.24f, 14.51f)
                quadTo(16.46f, 14.73f, 16.46f, 15.04f)
                quadTo(16.46f, 15.35f, 16.24f, 15.57f)
                quadTo(16.02f, 15.79f, 15.71f, 15.79f)
                quadTo(15.4f, 15.79f, 15.18f, 15.57f)
                quadTo(13.86f, 14.25f, 12f, 14.25f)
                quadTo(10.14f, 14.25f, 8.82f, 15.57f)
                quadTo(8.6f, 15.79f, 8.29f, 15.79f)
                quadTo(7.98f, 15.79f, 7.76f, 15.57f)
                quadTo(7.54f, 15.35f, 7.54f, 15.04f)
                quadTo(7.54f, 14.73f, 7.76f, 14.51f)
                close()
                moveTo(13.06f, 18.75f)
                lineTo(12.53f, 19.28f)
                quadTo(12.31f, 19.5f, 12f, 19.5f)
                quadTo(11.69f, 19.5f, 11.47f, 19.28f)
                lineTo(10.94f, 18.75f)
                quadTo(10.72f, 18.53f, 10.72f, 18.22f)
                quadTo(10.72f, 17.91f, 10.94f, 17.69f)
                lineTo(10.94f, 17.69f)
                quadTo(12f, 16.63f, 13.06f, 17.69f)
                quadTo(13.28f, 17.91f, 13.28f, 18.22f)
                quadTo(13.28f, 18.53f, 13.06f, 18.75f)
                close()
            }
        }.build()
}
