// GENERATED by convert_image_to_imagevector — do not edit; re-trace instead.
package io.github.ronjunevaldoz.tailwind.icons.outline

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Wrench: ImageVector by lazy {
    ImageVector
        .Builder(
            name = "Wrench",
            defaultWidth = 24f.dp,
            defaultHeight = 24f.dp,
            viewportWidth = 24f,
            viewportHeight = 24f,
        ).apply {
            path(fill = SolidColor(Color.Black)) {
                // color-agnostic — tint at the call site
                moveTo(22.5f, 6.75f)
                lineTo(22.5f, 6.75f)
                quadTo(22.5f, 9.06f, 20.8f, 10.62f)
                quadTo(19.1f, 12.18f, 16.8f, 11.98f)
                quadTo(15.13f, 11.84f, 14.49f, 12.62f)
                lineTo(7.34f, 21.3f)
                quadTo(6.04f, 22.88f, 4.04f, 22.42f)
                quadTo(2.05f, 21.95f, 1.58f, 19.95f)
                quadTo(1.12f, 17.96f, 2.7f, 16.66f)
                lineTo(11.38f, 9.51f)
                quadTo(12.16f, 8.87f, 12.02f, 7.2f)
                quadTo(11.76f, 4.2f, 14.22f, 2.46f)
                quadTo(16.67f, 0.73f, 19.41f, 1.96f)
                quadTo(19.69f, 2.09f, 19.8f, 2.38f)
                quadTo(19.91f, 2.67f, 19.79f, 2.96f)
                quadTo(19.73f, 3.08f, 19.63f, 3.18f)
                lineTo(16.67f, 6.14f)
                quadTo(17.01f, 6.99f, 17.86f, 7.33f)
                lineTo(20.82f, 4.37f)
                quadTo(21.04f, 4.15f, 21.35f, 4.15f)
                quadTo(21.66f, 4.15f, 21.88f, 4.37f)
                quadTo(21.98f, 4.46f, 22.04f, 4.59f)
                quadTo(22.5f, 5.61f, 22.5f, 6.75f)
                close()
                moveTo(21f, 6.75f)
                quadTo(21f, 6.54f, 20.98f, 6.33f)
                lineTo(18.61f, 8.7f)
                quadTo(18.31f, 9f, 17.91f, 8.9f)
                quadTo(15.62f, 8.38f, 15.1f, 6.09f)
                quadTo(15f, 5.69f, 15.3f, 5.39f)
                lineTo(17.69f, 3f)
                quadTo(16.33f, 2.8f, 15.08f, 3.69f)
                quadTo(13.33f, 4.93f, 13.51f, 7.07f)
                quadTo(13.72f, 9.53f, 12.34f, 10.66f)
                lineTo(3.65f, 17.82f)
                quadTo(2.79f, 18.52f, 3.04f, 19.61f)
                quadTo(3.3f, 20.7f, 4.39f, 20.96f)
                quadTo(5.47f, 21.21f, 6.18f, 20.34f)
                lineTo(13.34f, 11.66f)
                quadTo(14.47f, 10.28f, 16.93f, 10.49f)
                quadTo(18.57f, 10.63f, 19.79f, 9.51f)
                quadTo(21f, 8.4f, 21f, 6.75f)
                close()
                moveTo(4.12f, 19.13f)
                lineTo(4.12f, 19.12f)
                quadTo(4.12f, 18.81f, 4.34f, 18.59f)
                quadTo(4.56f, 18.38f, 4.87f, 18.38f)
                lineTo(4.88f, 18.38f)
                quadTo(5.19f, 18.38f, 5.41f, 18.59f)
                quadTo(5.62f, 18.81f, 5.62f, 19.12f)
                lineTo(5.62f, 19.13f)
                quadTo(5.62f, 19.44f, 5.41f, 19.66f)
                quadTo(5.19f, 19.88f, 4.88f, 19.88f)
                lineTo(4.87f, 19.88f)
                quadTo(4.56f, 19.88f, 4.34f, 19.66f)
                quadTo(4.12f, 19.44f, 4.12f, 19.13f)
                close()
            }
        }.build()
}
